### ISSUE TITLE
Static/Dynamic linking of sqlite shadows symbols needed for RTree* callbacks

### ISSUE THREAD

**Issue by sjg5d8** [xerial/sqlite-jdbc#10]
This issue effects mainly using deprecated functions in [spatialite](http://www.gaia-gis.it/gaia-sins/). 
- RTreeWithin
- RTreeContains
- RTreeIntersects
- RTreeDistWithin

via the `sqlite3_rtree_geometry_callback`

If one does a search for RTreeIntersects they will find lots of 

```
[SQLITE_ERROR] SQL error or missing database (no such function: RTreeIntersects)
```

And when traced through with a debugger the calls will seemingly disappear. Like in this [issue](https://github.com/zhm/node-spatialite/issues/2) (same effect, not xerial related)

What happens is that the JNI lib that xerial loads, calls to `select load_extension('mod_spatialite')` which then dynamically loads `libsqlite` makes a call to `sqlite3_rtree_geometry_callback`. The callbacks are registered in this second copy of sqlite, not the original. So when one attempts to call RTreeIntersects, the sqlite engine loaded by xerial knows nothing about it. [Bermuda Triangle](http://en.wikipedia.org/wiki/Bermuda_Triangle) of function calls. The solution for those needing a quick hack is link in your `libsqlite` from the system.

In `Makefile`

```
-       $(CC) $(CFLAGS) -o $@ $(SQLITE_OUT)/*.o $(LINKFLAGS)
-       $(STRIP) $@
+       $(CC) $(CFLAGS) -o $@ $(SQLITE_OUT)/NativeDB.o $(LINKFLAGS)
```

in `Makefile.common`

```
-Default_LINKFLAGS := -shared
+Default_LINKFLAGS := -shared -L/usr/local/lib -lsqlite3
```

**Comment by gotson** [comment]
Is this still happening on the latest version?

**Comment by gotson** [comment]
Closing this as no feedback was received.
