### ISSUE TITLE
Inaccurate floating point values since 3.43.0.0

### ISSUE THREAD

**Issue by InitFlo** [xerial/sqlite-jdbc#1002]
**Describe the bug**
Since 3.43.0.0 some precision of numbers is lost.

**To Reproduce**
```java
@Test
public void sqliteTest() throws SQLException {
	var testValue = new BigDecimal("3.14");

	try (var conn = DriverManager.getConnection("jdbc:sqlite::memory:")) {
		try (var createTblStmt = conn.prepareStatement("create table foo(nr number(10,2));")) {
			createTblStmt.execute();
		}
		try (var insStmt = conn.prepareStatement("insert into foo(nr) values(?);")) {
			insStmt.setBigDecimal(1, testValue);
			insStmt.execute();
		}

		try (var selStmt = conn.prepareStatement("select nr from foo;")) {
			if (selStmt.execute()) {
				try (var selResult = selStmt.getResultSet()) {
					var col1Value = selResult.getBigDecimal(1);
					assertEquals(testValue, col1Value);
				}
			}
		}
	}
}
```

**Expected behavior**
I expected 3.14 as the returned column value, but it is 3.1399999999999997.

**Environment (please complete the following information):**
 - OS: Windows 11
 - CPU architecture: x86_64
 - sqlite-jdbc version 3.43.2.1

**Comment by gotson** [comment]
Maybe check https://github.com/xerial/sqlite-jdbc/issues/927

It's unlikely that it's coming from the driver. Can you try with sqlite cli and compare between versions using the cli? It's most probably coming from sqlite itself.

**Comment by gotson** [comment]
Why is your table created with a number type and not real/double/float affinity if you want to store doubles in it?

**Comment by gotson** [comment]
You could also add any slf4j implementation and enable trace logs to show what exact sql statements are used.

**Comment by InitFlo** [comment]
The issue is not present in [sqlite-tools-win32-x86-3420000.zip ](https://sqlite.org/2023/sqlite-tools-win32-x86-3420000.zip) and [sqlite-tools-win32-x86-3430200.zip](https://sqlite.org/2023/sqlite-tools-win32-x86-3430200.zip).

Yes, there were changes in sqlite: https://www.sqlite.org/changes.html. Probably

> 6. Enhancements to the [decimal extension](https://www.sqlite.org/floatingpoint.html#decext)
c) If X is a floating-point value, then the decimal(X) function now does a full expansion of that value into its exact decimal equivalent.

is the cause. There is the behaviour of both cli-Versions different.

Php had similar problems, see https://sqlite.org/forum/forumpost/abc65bec19475130.

Can you force force sqlite to use the slower algorithm that gives full accuracy? I would prefer it at the cost a few nanosecods. The jni overhead might be bigger.

**Comment by gotson** [comment]
> Can you force sqlite to use the slower algorithm that gives full accuracy? I would prefer it at the cost a few nanosecods. The jni overhead might be bigger.

Without even knowing where/why it happens, no.

**Comment by gotson** [comment]
I've added [some tests](https://github.com/gotson/sqlite-jdbc/blob/1d532eb9ea2ea81091692ae2464b5246b5171753/src/test/java/org/sqlite/PrepStmtTest.java#L836-L875) to run on CI, which fail on Windows only: https://github.com/gotson/sqlite-jdbc/actions/runs/6649079467/job/18067046014

The 3 tests represent different [column affinity](https://www.sqlite.org/datatype3.html).

You can see [in the code](https://github.com/xerial/sqlite-jdbc/blob/main/src/main/java/org/sqlite/jdbc3/JDBC3PreparedStatement.java#L217-L219) of `setBigDecimal` that we use the `String` representation of the `BigDecimal`, which is then [passed](https://github.com/xerial/sqlite-jdbc/blob/main/src/main/java/org/sqlite/core/DB.java#L895-L895) to Sqlite using `bind_text`. I believe this is done to avoid losing precision by converting into another Java type.

I don't see any good way to bind a `BigDecimal` using Sqlite: https://www.sqlite.org/c3ref/bind_blob.html

For me that's a Sqlite behaviour, nothing we can do in the driver about it.

**Comment by gotson** [comment]
Note that if you specify the column as `number(15)` its affinity will be `numeric` (rule 5 in [section 3.1](https://www.sqlite.org/datatype3.html)).

The windows binaries are built using [dockcross](https://github.com/xerial/sqlite-jdbc/blob/master/Makefile#L136)
