### ISSUE TITLE
executing "insert into table1(col1, col2) select col1, col2 from table2;" with database is locked

### ISSUE THREAD

**Issue by dotw** [xerial/sqlite-jdbc#101]
I'm using setAutoCommit(false) mode. I got database is locked after executing "insert into table1(col1, col2) select col1, col2 from table2;". no idea what happened. anyone help?

**Comment by gitblit** [comment]
```sql
insert into table1(col1, col2) select col1, col2 from table2;
```

That does not look like a valid statement.  I will assume you have overcome this hurdle since no one has replied before now and you have not followed-up.
