### ISSUE TITLE
Cannot package with jlink since version 3.43.2.1

### ISSUE THREAD

**Issue by rsribeiro** [xerial/sqlite-jdbc#1022]
**Describe the bug**
A small project I have, which has a dependency on sqlite-jdbc, cannot be packaged with jlink anymore since version 3.43.2.1.

That version downgraded slf4j-api dependency to version 1.7, which does not work with jlink.

Version 3.43.2.0 of sqlite-jdbc pulled version 2.0 of slf4j, which worked just fine with jlink.

**To Reproduce**
Have sqlite-jdbc 3.43.2.1 or later as a dependency and try packaging with jlink

**Expected behavior**
Package without issues

**Logs**
[ERROR] Error: automatic module cannot be used with jlink: org.slf4j from file:///.../org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36.jar

**Environment (please complete the following information):**
 - OS: Windows 10
 - CPU architecture: x86_64
 - sqlite-jdbc version 3.43.2.1 or later

**Additional context**

**Comment by gotson** [comment]
Probably something you should report to slf4j, no?

**Comment by rsribeiro** [comment]
I've looked into it a bit more and I can workaround this problem by pulling the slf4j 2.0 dependency into my project, thus overriding the sqlite-jdbc dependency on 1.x and solving my issue.

About reporting to slf4j, I believe 1.x is no longer under active development. They did already implement full jpms/modularisation support on version 2.0.
