### ISSUE TITLE
Compile desktop binaries with -DHAVE_USLEEP=1

### ISSUE THREAD

**Issue by illumi** [xerial/sqlite-jdbc#104]
There seems to be some separation between Bitbucket and GitHub where issues are still being updated there. This seems to be related to Bitbucket issues 129 and 205.

**Comment by gitblit** [comment]
Definitely related to [Bitbucket-129](https://bitbucket.org/xerial/sqlite-jdbc/issues/129).  I don't see any relationship to [Bitbucket-205](https://bitbucket.org/xerial/sqlite-jdbc/issues/129).
