### ISSUE TITLE
Java 8 Compatibility

### ISSUE THREAD

**Issue by noahtk** [xerial/sqlite-jdbc#105]
Hi,

This driver does not appear to work with Java 8 with the standard configuration.  If the driver requires additional steps to fully work in Java 8, please include them in the ReadMe.

**Comment by gitblit** [comment]
You'll have to be more clear.  It has worked fine for me in J8.

**Comment by noahtk** [comment]
Thanks, it may be my team's JVM configuration causing the issue then.

**Comment by gitblit** [comment]
I assume whatever J8 issue you have has been resolved.
