### ISSUE TITLE
Update release to 3.44.02

### ISSUE THREAD

**Issue by JCodeShelver** [xerial/sqlite-jdbc#1050]
Is it possible to bump this project up to SQLite 3.44.02? I'm unsure if there is currently compatibility issues, but since the README says that the project release version is kept up to date, and it has been over a month since 3.44.02 came out, it'd be nice to see a new release.

**Comment by gotson** [comment]
we are already on 3.44.1

**Comment by JCodeShelver** [comment]
I meant 3.44.2, but now they're on 3.45.0
