### ISSUE TITLE
Is getGeneratedKeys() permanently deprecated?

### ISSUE THREAD

**Issue by prrvchr** [xerial/sqlite-jdbc#1061]
Hi all,

It seems that you are determined not to implement the **getGeneratedKeys()** method.
I don't really understand what prevents this from happening.

If you want to use mass inserts with the command `INSERT INTO mytable (Col1, Col2) VALUES (data1, data2), (data1, data2), ...` this is the only method that allows you to recover the primary keys generated automatically in a single pass.

Thanks for your help.

**Comment by gotson** [comment]
there is no such support in SQLite to retrieve multiple generated values. You can use a `RETURNING` clause if you want to get multiple IDs.

**Comment by gotson** [comment]
> If this works, wouldn't it be smarter to integrate this into sqlite-jdbc to make the use of its API fully compatible?

feel free to send a PR

**Comment by prrvchr** [comment]
Here is a [possible implementation](https://github.com/xerial/sqlite-jdbc/pull/1067) of **getGeneratedKeys()**.
I was not able to test because I cannot compile, but I am ready to test if I have an archive available.

**Comment by prrvchr** [comment]
Can anyone give me instructions on how to compile?
Thanks.

**Comment by prrvchr** [comment]
Well I have a version which integrates the modifications and which remains to be tested. For now everything is working fine...
I understand that editing the SQL commands in the sqlite-jdbc driver may seem a bit messy, but in fact I am convinced that this is the right way to do it because:
- It makes the driver fully compatible with JDBC.
- This does not prevent the old way of working (select last_insert_id) which by the way was already doing a bit of the same thing.
- Although this correction seems a bit simplistic, I think it will prove particularly robust.

The archive if you want to test: [sqlite-jdbc-3.45.1.2-SNAPSHOT.jar](https://github.com/prrvchr/sqlite-jdbc/releases/download/3.45.1.2-SNAPSHOT/sqlite-jdbc-3.45.1.2-SNAPSHOT.jar)

**Comment by prrvchr** [comment]
Well, I produced a version that allows you to follow the JDBC specifications to the letter, but @gotson doesn't seem ready to integrate it.

I believe that it refuses to modify the SQL requests that the driver processes even though this is the only way to follow the JDBC specifications. It's a shame.

For the moment a version is available on my fork of [sqlite-jdbc](https://github.com/prrvchr/sqlite-jdbc).

**Comment by prrvchr** [comment]
I have just updated [sqlite-jdbc-3.45.1.3-SNAPSHOT.jar](https://github.com/prrvchr/sqlite-jdbc/releases/download/3.45.1.2-SNAPSHOT/sqlite-jdbc-3.45.1.3-SNAPSHOT.jar) to comply with JDBC 4.1, namely:

- The `java.sql.DatabaseMetaData.supportsGetGeneratedKeys()` method answers `true`.
- The `java.sql.DatabaseMetaData.generatedKeyAlwaysReturned()` method answers `true`.
- The `java.sql.Statement.executeUpdate(String sql, int _autoGeneratedKeys_)` method works as follows:
  - If _autoGeneratedKeys_ is equal to `java.sql.Statement.RETURN_GENERATED_KEYS` and the SQL command begins with `INSERT` or `REPLACE` and it only includes one SQL command then the records affected by the SQL command will be accessible by the `java.sql.Statement.getGeneratedKeys()` method (all columns in the table will be returned).
  - Otherwise the SQL command will be executed without influencing the operation of `getGenerateKeys()` which allows you to interweave queries before having to retrieve the records using `getGeneratedKeys()`...
- The `java.sql.Statement.executeLargeUpdate(String sql, int _autoGeneratedKeys_)` method works like the previous one...
- The `java.sql.Statement.executeUpdate(String sql, String[] _columnNames_)` method allows you to get only the requested _columnNames_ in `getGeneratedKeys()`.
- The `java.sql.Statement.executeLargeUpdate(String sql, String[] _columnNames_)` method works like the previous one...
- The `java.sql.Statement.executeUpdate(String sql, int[] _columnIndex_)` method is not supported.
- The `java.sql.Statement.executeLargeUpdate(String sql, int[] _columnIndex_)` method is not supported.
- The `java.sql.Statement.execute(String sql, int _autoGeneratedKeys_)` method is not supported (you need to use `executeUpdate()` then `getGenratedKeys()` methods).
- The `java.sql.Statement.execute(String sql, String[] _columnNames_)` method is not supported (you need to use `executeUpdate()` then `getGenratedKeys()` methods).
- The `java.sql.Statement.execute(String sql, int[] _columnIndex_)` method is not supported.
- The `java.sql.Connection.prepareStatement(String sql,  int _autoGeneratedKeys_)` method work same as `executeUpdate(String sql, int _autoGeneratedKeys_)`.
- - The `java.sql.Connection.prepareStatement(String sql,  String[] _columnNames_)` method work same as `executeUpdate(String sql, String[] _columnNames_)`.
- The `java.sql.Connection.prepareStatement(String sql, int[] _columnIndex_)` method is not supported.

I would like to point out to you that the new operating mode of this driver is not at all the same as that used in the gotson driver. It **probably requires rewriting your programs but it follows JDBC specifications**.
