### ISSUE TITLE
Why refuse what IBM is doing with DB2 for JDBC 4.1

### ISSUE THREAD

**Issue by prrvchr** [xerial/sqlite-jdbc#1069]
Please don't be offended by my insistence on JDBC 4.1 support, this is **only to improve your driver**.

This request follows my [PR](https://github.com/xerial/sqlite-jdbc/pull/1067) which was refused and the production of a [sqlite-jdbc archive](https://prrvchr.github.io/sqlite-jdbc/) compatible with JDBC 4.1.

If we look in detail at the [JDBC 4.1 driver for DB2](https://www.ibm.com/docs/en/db2/11.5?topic=applications-retrieving-auto-generated-keys-insert-statement), we can see that their JDBC driver oversubscribes SQL commands passed to the driver. It suffixes all SQL commands starting with `INSERT` with `SELECT FROM`.

So my question is simple: Why refuse what IBM does in its driver and therefore refuse to port xerial sqlite-jdbc to JDBC 4.1?

**Comment by gotson** [comment]
We already stated the position of this driver.
