### ISSUE TITLE
Implement DatabaseMetaData#getRowIdLifetime

### ISSUE THREAD

**Issue by onacit** [xerial/sqlite-jdbc#1070]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
IMHO, [DatabaseMetaData#getRowIdLifetime()](https://docs.oracle.com/en/java/javase/21/docs/api/java.sql/java/sql/DatabaseMetaData.html#getRowIdLifetime()) may just return the [RowIdLifeTime#ROWID_UNSUPPORTED](https://docs.oracle.com/en/java/javase/21/docs/api/java.sql/java/sql/RowIdLifetime.html#ROWID_UNSUPPORTED) instead throwing a `SQLFeatureNotSupportedException`.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by gotson** [comment]
From the SQLite [documentation](https://www.sqlite.org/lang_createtable.html#rowid) it seems the rowid can be modified with an `UPDATE` statement, thus they would not qualify as "lifetime", no ?

> Rowid values may be modified using an UPDATE statement in the same way as any other column value can, either using one of the built-in aliases ("rowid", "oid" or "_rowid_") or by using an alias created by an integer primary key.
