### ISSUE TITLE
Cannot use driver in netbeans with version higer than 3.42.0.1

### ISSUE THREAD

**Issue by Tran-Hong-Quan** [xerial/sqlite-jdbc#1085]
I was trying to connect to my sqlite database using 
            Class.forName("org.sqlite.JDBC");
            String url = "jdbc:sqlite:myDB.db";
            conn = DriverManager.getConnection(url);
It works fine on version equal or lower than 3.42.0.1, but not on higher version
![image](https://github.com/xerial/sqlite-jdbc/assets/95110396/4110672e-bb8b-4278-8f3d-9c279ba2d508)

**Comment by gotson** [comment]
You need to include slf4j

**Comment by Tran-Hong-Quan** [comment]
I added slf4j.jar to the project but it still doesn't work. I think I will use the older version because my main purpose is just to study
![image](https://github.com/xerial/sqlite-jdbc/assets/95110396/465adc28-8b68-4e39-8b6f-a44300298ac3)
