### ISSUE TITLE
"Load the JDBC driver org.sqlite.JDBC from your code. (see the example below) "

### ISSUE THREAD

**Issue by alexeyr** [xerial/sqlite-jdbc#109]
This is what the readme says, but the example doesn't mention `org.sqlite.JDBC`. I assume this is no longer necessary in the JDBC4 driver; what about the JDBC3 one?

**Comment by gitblit** [comment]
One of the improvements in JDBC4 is automatic driver registration so you do not have to manually load anything.  `sqlite-jdbc` is a JDBC4 driver.  While it is compiled for Java 5, I see references to classes that are part of Java 6 so I doubt it would even work correctly in a JDBC3 environment (Java <=5) anymore.

**Comment by gitblit** [comment]
Fixed readme.
