### ISSUE TITLE
Unsatisfied Link Error when REdeploying 3.8.7 in Tomcat 7.0.56

### ISSUE THREAD

**Issue by andrewcooke** [xerial/sqlite-jdbc#11]
If I use 3.8.6 or 3.8.7 in a war file and undeploy and then deploy the application, I get an `UnsatisfiedLinkError: org.sqlite.core.NativeDB._open(Ljava/lang/String;I)V`.  If I restart Tomcat everything works fine, so I guess it's actually not so bad for production, but for development it's frustrating.

This is with a Maven project, bundling the sqlite-jdbx jar inside the war.  I haven't tried a separate jar (as was recommended for 3.8.6 with multiple applications).  Should I try that?

This is on Centos 6.5 with OpenJDK 1.7.0_65.

Is this a known issue?  A bug?  Normal behaviour?  Any help appreciated.  Thanks.

**Comment by gitblit** [comment]
It's unclear if this is still a problem but I would guess it is not, based on how `SQLiteJDBCLoader` works.  If the current version of the driver still exhibits the same behavior, please submit a PR with a proposal of how you might improve this use-case.
