### ISSUE TITLE
Fat jar with REGEXP and other common extensions?

### ISSUE THREAD

**Issue by ryanhamilton** [xerial/sqlite-jdbc#1125]
Hi,
I'm the author of qStudio an SQL IDE for data analysts that includes drivers for sqlite: https://www.timestored.com/qstudio/
Currently I embed https://github.com/xerial/sqlite-jdbc but users have raised an issue with REGEXP missing (https://github.com/timeseries/qstudio/issues/50) .
THis issue has been raised 4 times on your repo: https://github.com/xerial/sqlite-jdbc/issues?q=is%3Aissue++regexp

Would you consider releasing a "Fat" JDBC driver with REGEXP and other standard calls?

**Alternatives**
1. I create a bundle or add REGEXP for qStudio. -> can't as we support 30+ databases and I can't support them to that level.
2. Let the user bring their own jar -> this is currently possible in qStudio but 90% of users don't have the skills to add it. 99% don't have the skill to build such a jar.
3. ?

**Comment by gotson** [comment]
it's already supported as user functions, it won't be added as default. If REGEXP is really necessary, it should be requested at SQLite and added in the C code.
