### ISSUE TITLE
Support virtual file systems

### ISSUE THREAD

**Issue by BullyWiiPlaza** [xerial/sqlite-jdbc#113]
Check out my question on StackOverflow [here](http://stackoverflow.com/questions/37525302/sqlite-virtual-file-system).

**Comment by xerial** [comment]
We anyway need to copy the file to local disk since sqlite doesn't work for non-local files. If you can provide URL of the file, it would work as:
https://github.com/xerial/sqlite-jdbc/blob/master/Usage.md#reading-database-files-in-classpaths-or-network-read-only
