### ISSUE TITLE
Insert String value to Integer column

### ISSUE THREAD

**Issue by looly** [xerial/sqlite-jdbc#1143]
**Describe the bug**

When I use JDBC to build a `PreparedStatement` and use `setObject` method to insert to database, a String value can insert to a Integer column.

**To Reproduce**

I use Hutool wrap the sql and insert to db.

```java
final Db db = Db.of(DbConfig.of().setUrl("jdbc:sqlite:d:/test/test.db"));
db.insert(Entity.of("user").set("age", "testStr2"));
```

and `age` column is a INTEGER column.

![image](https://github.com/user-attachments/assets/b79ec0f8-25b6-43a0-add3-5680b5d36594)

![image](https://github.com/user-attachments/assets/2a830574-8fc0-43e6-b78f-082ee14beda2)

**Expected behavior**

**Logs**

**Environment (please complete the following information):**
 - OS: Windows 11
 - CPU x86_64
 - sqlite-jdbc version 3.46.0.0

**Additional context**

**Comment by gotson** [comment]
SQLite doesn't care about types.
