### ISSUE TITLE
Temporary Database

### ISSUE THREAD

**Issue by ynixt** [xerial/sqlite-jdbc#1147]
Can we use sqlite temporary database with this driver? I know that the driver supports in-memory, but it is not the same:

> Even though a disk file is allocated for each temporary database, in practice the temporary database usually resides in the in-memory pager cache and hence there is very little difference between a pure in-memory database created by ":memory:" and a temporary database created by an empty filename. The sole difference is that a ":memory:" database must remain in memory at all times whereas parts of a temporary database might be flushed to disk if the database becomes large or if SQLite comes under memory pressure.

**Comment by gotson** [comment]
If you don't pass a file name it should be a temporary database. Seems documented here: https://github.com/xerial/sqlite-jdbc/blob/master/USAGE.md#how-to-use-memory-databases

**Comment by ynixt** [comment]
I hadn't noticed because the documentation says "memory database" instead of "temporary database". In short, it was my fault. Thanks.

**Comment by gotson** [comment]
> I hadn't noticed because the documentation says "memory database" instead of "temporary database". In short, it was my fault. Thanks.

i was not aware of the difference to be honest, the documentation could use some updated wording i guess

**Comment by ynixt** [comment]
> > I hadn't noticed because the documentation says "memory database" instead of "temporary database". In short, it was my fault. Thanks.
> 
> i was not aware of the difference to be honest, i have updated the wording in the documentation

Thank you for that, it's easier to understand.

The "memory database" is **always** on the memory and **doesn't** have any file. On the other hand, the "temporary database" creates a file in the temp path of the system, and the file is automatically deleted after the connection closes. This temporary file will be used if the database becomes large or if SQLite comes under memory pressure to flush to the disk parts of the database.

Source: https://www.sqlite.org/inmemorydb.html
