### ISSUE TITLE
 Add option to disable the double-quoted string literal misfeature by default

### ISSUE THREAD

**Issue by JesseChavez** [xerial/sqlite-jdbc#1153]
**Is your feature request related to a problem? Please describe.**

It would be good to have a configuration property to disable the misfeature described in the title

Having this will disable undesired behaviour described by the SQLite creator in the following link

https://www.sqlite.org/quirks.html#double_quoted_string_literals_are_accepted

Here is a like of a specific undesired behaviour

https://github.com/rails/rails/issues/27782

**Describe the solution you'd like**

Something we can pass in the connection url would be good.

e.g.

```
jdbc:sqlite:db.sqlite?strict_strings=true
```

**Additional context**

Here is a example how a configuration property was added to library that uses SQLite's C API.

https://github.com/sparklemotion/sqlite3-ruby/pull/317

**Comment by gotson** [comment]
can you explain what you are referring to by "the double-quoted string literal misfeature" ?
