### ISSUE TITLE
armeabi-v7a

### ISSUE THREAD

**Issue by timscriptov** [xerial/sqlite-jdbc#1174]
Lib not have armeabi-va libsqlitejdbc.so

armeabi.so(v5) deprecated

**Comment by gotson** [comment]
please provide more details and follow the issue template

**Comment by timscriptov** [comment]
![image](https://github.com/user-attachments/assets/652df5a7-b490-466c-a3d3-e4396a6e27a3)

**Comment by timscriptov** [comment]
It armeabi-v7a or armeabi?
