### ISSUE TITLE
SQLite and generated keys

### ISSUE THREAD

**Issue by gwenn** [xerial/sqlite-jdbc#1186]
**Describe the bug**

The following statement seems wrong to me:
https://github.com/xerial/sqlite-jdbc/blob/master/USAGE.md#generated-keys
> SQLite has limited support to retrieve generated keys

**Expected behavior**

Because you can use the `INSERT ... RETURNING ...` syntax:
https://sqlite.org/lang_returning.html

The returning clause (if missing) could be generated programmatically by the JDBC driver.

**Comment by gotson** [comment]
> The returning clause (if missing) could be generated programmatically by the JDBC driver.

this is quite complex and out of scope of the driver

**Comment by gwenn** [comment]
> > The returning clause (if missing) could be generated programmatically by the JDBC driver.
> 
> this is quite complex and out of scope of the driver

So this means that only the JDBC driver `has limited support to retrieve generated keys` and **not** SQLite.
