### ISSUE TITLE
Crash on android API 23 and below

### ISSUE THREAD

**Issue by 05nelsonm** [xerial/sqlite-jdbc#1204]
**Describe the bug**
Crashes on Android API 23 and below as a result of logging behavioral changes in b8ea5ca138eec57d8b42fa6033dcd04ff3e47116

~`java.util.logger.Logger` is not available on Android until API 24~
`java.util.function.Supplier` usage is not available until API 24 (when android integrated Java 8 APIs)
The `@FunctionalInterface` annotation is also not an available API until Java 8, so usage of that would be out as well.

**To Reproduce**
Run in emulator API 23. Witness crash.

**Expected behavior**
Should not crash

**Logs**
```
Caused by: java.lang.NoClassDefFoundError: org.sqlite.core.NativeDB$$ExternalSyntheticLambda1
at org.sqlite.core.NativeDB.prepare(NativeDB.java:130)
```

https://github.com/toxicity-io/sqlite-mc/actions/runs/11482174680/job/31954575727?pr=127

**Comment by gotson** [comment]
Android 6 is very old, and this is mostly a Java library, not an Android library. We are not going to do any stretch to support API 23.0

**Comment by 05nelsonm** [comment]
Then why offer support by detection of Android and loading via `System.loadLibrary`, or even the Linux-Android compilations that uses clang api 23 , or the guide for using with Android?

API 23 is **widely** used as the min SDK throughout Android ecosystem. Tons of old phones (particularly in poorer parts of the world) still used...

**Comment by gotson** [comment]
You are confusing things. This library does not target any specific Android API. It is primarily a Java 8 API. If it doesn't work on certain Android APIs, we will not make a stretch to support those. API 23 is from 2015. API 24 is from 2016, and has almost the same [cumulative usage](https://apilevels.com/) as API 23.
