### ISSUE TITLE
Release 3.14.2

### ISSUE THREAD

**Issue by gitblit** [xerial/sqlite-jdbc#131]
After #123, #127, and #128 have been merged we will need new builds of the native libraries for the following architectures on the lowest common denominator OS release or libc version, as appropriate.

There is not a lot of GitHub history for the native libs so, at present, much of the compiling falls to @xerial who will have to tag & deploy a release anyway.

- [x] FreeBSD x86_64 (@alexdupre, done in #157)
- [x] Linux arm (@xerial)
- [x] Linux armhf (@xerial)
- [x] Linux x86 (@xerial)
- [x] Linux x86_64 (@xerial)
- [x] ~~Mac x86~~ (deprecated #152)
- [x] Mac x86_64 (@xerial)
- [x] Windows x86 (@xerial)
- [x] Windows x86_64 (@xerial)

**Comment by srmo** [comment]
Just wanted to jump in and report that I had the same native lib problem as others on Raspian with the current stable. Using a from-scratch-build on the current develop tree works. A fresh 3.13 release is much appreciated :)

If there's anything I can do to help?

**Comment by alexdupre** [comment]
I've tried to rebuild the native library, but I get the following error:
```
"$JAVA_HOME/bin/javac"  -source 1.5 -target 1.5 -sourcepath src/main/java -d target/sqlite-3.13.0-FreeBSD-x86_64 src/main/java/org/sqlite/core/NativeDB.java
warning: [options] bootstrap class path not set in conjunction with -source 1.5
warning: [options] source value 1.5 is obsolete and will be removed in a future release
warning: [options] target value 1.5 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
src/main/java/org/sqlite/SQLiteConfig.java:101: error: cannot find symbol
        return JDBC.createConnection(url, toProperties());
                   ^
  symbol:   method createConnection(String,Properties)
  location: class JDBC
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
4 warnings
gmake[1]: *** [Makefile:41: target/sqlite-3.13.0-FreeBSD-x86_64/org/sqlite/core/NativeDB.class] Error 1
```

I'm too tired to debug it now, but it doesn't seem FreeBSD specific.

**Comment by xerial** [comment]
Now all the native libraries except Mac/x86_64 and FreeBSD/x86_64 can be built with docker. I'll step forward to release 3.14.2

**Comment by xerial** [comment]
Published sqlite-jdbc 3.14.2 to Maven central. I appreciate your patience waiting for a new version such a long time. To overcome my laziness, I have decided to use Docker to build all of the native libraries. Mac x86_64 is no problem since I'm using Mac :)

Building FreeBSD/x86_64 native library can be a future blocker. Need a better solution (Do not support or preparing a cross compiler, etc.)

**Comment by xerial** [comment]
@gitblit When you have a time, please complement the release note in README.md. I guess JSON1 is a big thing for the users.

**Comment by Dunemaster** [comment]
@xerial, thank you so much!
