### ISSUE TITLE
Not implemented BLOB

### ISSUE THREAD

**Issue by donat-mueller** [xerial/sqlite-jdbc#135]
Hi,
I try to retrieve an image as blob and get the message below:
Is this a bug or really a not supported jdbc feature ?

java.sql.SQLException: not implemented by SQLite JDBC driver
    at org.sqlite.jdbc4.JDBC4ResultSet.unused(JDBC4ResultSet.java:320)
    at org.sqlite.jdbc4.JDBC4ResultSet.getBlob(JDBC4ResultSet.java:343)

**Comment by gitblit** [comment]
It turns out this is currently not implemented, so the exception is the truth.  This driver does not implement a lot of the JDBC spec.

**Comment by donat-mueller** [comment]
Thx a lot for the fast reply

**Comment by rishisharan** [comment]
How to fix this issue?

**Comment by xerial** [comment]
sqlite has no support of reading BLOB in streaming manner, so the implementation will be anyway reading the entire data into memory. Using getByte is sufficient.

**Comment by dherges** [comment]
For people coming across SQLite and JPA:

```java
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Lob;

@Entity
public class FooEntity {

  @Id
  public UUID id = UUID.randomUUID();

  @Lob // <-- doesn't work for SELECT statements. INSERT would still work
  public byte[] data;
}
```

Solution:

```java
@Entity
public class FooEntity {

  @Id
  public UUID id = UUID.randomUUID();

  // @Lob --> omitting the annotation does work for SELECT, INSERT, UPDATE, DELETE
  // property will be mapped to a BLOB column
  public byte[] data;
}
```
