### ISSUE TITLE
How can i load db file from classpath?

### ISSUE THREAD

**Issue by zhaowei211628** [xerial/sqlite-jdbc#142]
how can i load db file use keyword "**# classpath**" like this:

jdbc.sqlite.url=jdbc:sqlite::**# classpath**:url.db

or

jdbc.sqlite.url=jdbc:sqlite:**# classpath**:url.db

**Comment by xerial** [comment]
See https://github.com/xerial/sqlite-jdbc/blob/master/Usage.md#reading-database-files-in-classpaths-or-network-read-only
