### ISSUE TITLE
Usage of sqlite-jdbc together with the relocation feature of the Maven shade plugin

### ISSUE THREAD

**Issue by fmannhardt** [xerial/sqlite-jdbc#145]
I would like to use the sqlite in a project where I have to use the relocation feature of the Maven shade plugin to avoid clashes with different versions of the same library being loaded. The Maven shade plugin can relocate all Java classes to a different package name (e.g., org.sqlite to test.org.sqlite). 

Unfortunately, sqlite-jdbc seems to load some of its classes dynamically at runtime in such a way that it is impossible for the Maven shade plugin to adjust the references accordingly. Therefore, all projects that use sqlilte, for example [cqengine](https://github.com/npgall/cqengine/issues/86), cannot be "shaded" entirely.

I created a small standalone test that demonstrates the issue. The test runs the example code of sqlite-jdbc. The JUnit test runs successfull, but when executing the shaded artifact: sqlite[...]-shaded.jar I get the following error:

> java -jar target/sqlite-shade-test-0.0.1-SNAPSHOT-shaded.jar
> java.sql.SQLException: No suitable driver found for jdbc:sqlite:C:\Users[...]AppData\Loca\Temp\test_8871362628708427569.db
>        at java.sql.DriverManager.getConnection(Unknown Source)
>        at java.sql.DriverManager.getConnection(Unknown Source)
>        at test.SQLite.open(SQLite.java:21)
>        at test.SQLite.main(SQLite.java:28)`

I tried to load the correct shaded driver with:

```
        try {
            Class.forName("test.org.sqlite.JDBC");
        } catch (ClassNotFoundException e) {
        }
```

but that leads to a ClassNotFoundException.

Would it be possible to support this use case? 
[sqlite-shade-test.zip](https://github.com/xerial/sqlite-jdbc/files/454772/sqlite-shade-test.zip)

**Comment by xerial** [comment]
@fmannhardt JDBC driver name `org.sqlite.JDBC` is stored in https://github.com/xerial/sqlite-jdbc/blob/master/src/main/resources/java.sql.Driver, 
so if you can overwrite java.sql.Driver file in the shade jar, it would work.

**Comment by fmannhardt** [comment]
Thanks for the answer. I almost forgot about this issue since I found a different solution that does not require shading the JAR at all. 

I tried to overwrite the java.sql.Driver file in the JAR, but that did not work. Then, the next class that is not found is org.sqlite.core.NativeDB:

> Exception in thread "main" java.lang.NoClassDefFoundError: org/sqlite/core/Nativ
> eDB
>         at java.lang.ClassLoader$NativeLibrary.load(Native Method)
>         at java.lang.ClassLoader.loadLibrary0(Unknown Source)
>         at java.lang.ClassLoader.loadLibrary(Unknown Source)
>         at java.lang.Runtime.load0(Unknown Source)
>         at java.lang.System.load(Unknown Source)
>         at test.org.sqlite.SQLiteJDBCLoader.loadNativeLibrary(SQLiteJDBCLoader.j
> ava:227)
>         at test.org.sqlite.SQLiteJDBCLoader.extractAndLoadLibraryFile(SQLiteJDBC
> Loader.java:207)
>         at test.org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLo
> ader.java:290)
>         at test.org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:65)
> 
>         at test.org.sqlite.core.NativeDB.load(NativeDB.java:53)
>         at test.org.sqlite.core.CoreConnection.open(CoreConnection.java:211)
>         at test.org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
>         at test.org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:24)
> 
>         at test.org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:23)
> 
>         at test.org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
>         at test.org.sqlite.JDBC.createConnection(JDBC.java:114)
>         at test.org.sqlite.JDBC.connect(JDBC.java:88)
>         at java.sql.DriverManager.getConnection(Unknown Source)
>         at java.sql.DriverManager.getConnection(Unknown Source)
>         at test.SQLite.open(SQLite.java:21)
>         at test.SQLite.main(SQLite.java:28)
> Caused by: java.lang.ClassNotFoundException: org.sqlite.core.NativeDB
>         at java.net.URLClassLoader.findClass(Unknown Source)
>         at java.lang.ClassLoader.loadClass(Unknown Source)
>         at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
>         at java.lang.ClassLoader.loadClass(Unknown Source)
>         ... 21 more

**Comment by xerial** [comment]
sqlite-jdbc searches native library from the predefined resource folder within the jar: https://github.com/xerial/sqlite-jdbc/blob/master/src/main/java/org/sqlite/SQLiteJDBCLoader.java#L311

For example, needs to be in the same location. 
`/org/sqlite/native/Linux/x86_64/libsqlitejdbc.so`

If this code resolves the native library path to be relative from the current java package name, I think your problem can be solved.

**Comment by md-5** [comment]
Fyi classes containing native methoda can't be relocted regardless

**Comment by xerial** [comment]
@md-5 Good point. So `org.sqlite.core.NativeDB` class should be excluded when using shade-plugin.

**Comment by sic2** [comment]
Hi @xerial 

how do you go about excluding sqlite? Thanks

**Comment by paulvi** [comment]
I ran into "No suitable driver found for jdbc:sqlite:" with `maven-shade-plugin`,
and thanks to hint of @xerial Taro pointing to  
https://github.com/xerial/sqlite-jdbc/blob/master/src/main/resources/java.sql.Driver  
I figured solution as below (similar to spring files)

			
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-shade-plugin</artifactId>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>shade</goal>
						</goals>
						<configuration>
							<transformers>
								<transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
	                                <mainClass>com.company.Server</mainClass>
	                            </transformer>
								<transformer
									implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
									<resource>META-INF/spring.handlers</resource>
								</transformer>
								<transformer
									implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
									<resource>META-INF/spring.schemas</resource>
								</transformer>
								<transformer
									implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
									<resource>META-INF/services/java.sql.Driver</resource>
								</transformer>
							</transformers>
						</configuration>
					</execution>
				</executions>
			</plugin>

SOLVED.

**Comment by ganeshkumarganesan** [comment]
@xerial - I am trying to shade the sqlite-jdbc jar. I've handled the META-INF/services/java.sql.Driver. But I am getting the following exception. It looks like after loading the libsqlitejdbc.so, tried to load NativeDB class in an actual package instead of the shaded package.

Kindly suggest any workarounds.

`Exception in thread "main" java.lang.NoClassDefFoundError: org/sqlite/core/NativeDB
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817)
	at java.lang.Runtime.load0(Runtime.java:810)
	at java.lang.System.load(System.java:1088)
	at sqlite.shaded.SQLiteJDBCLoader.loadNativeLibrary(SQLiteJDBCLoader.java:299)
	at sqlite.shaded.SQLiteJDBCLoader.extractAndLoadLibraryFile(SQLiteJDBCLoader.java:257)
	at sqlite.shaded.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:366)
	at sqlite.shaded.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:68)
	at sqlite.shaded.core.NativeDB.load(NativeDB.java:63)
	at sqlite.shaded.SQLiteConnection.open(SQLiteConnection.java:240)
	at sqlite.shaded.SQLiteConnection.<init>(SQLiteConnection.java:61)
	at sqlite.shaded.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
	at sqlite.shaded.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:21)
	at sqlite.shaded.JDBC.createConnection(JDBC.java:115)
	at sqlite.shaded.JDBC.connect(JDBC.java:90)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at Main.main(Main.java:13)
Caused by: java.lang.ClassNotFoundException: org.sqlite.core.NativeDB
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 19 more`
