### ISSUE TITLE
i have meet a core issuer when i was use sqlite-jdbc-3.8.10.1.jar to creat Connectionon on the  suse10 sp4  system ，but it working at suse11 sp3

### ISSUE THREAD

**Issue by helloxian** [xerial/sqlite-jdbc#146]
i have meet a core issuer when i was use sqlite-jdbc-3.8.10.1.jar to creat connect on the suse10 sp4 system.the process was core down when i creat connect.The java stack as below

 A fatal error has been detected by the Java Runtime Environment:

  SIGFPE (0x8) at pc=0x00002b6a7699680f, pid=7975, tid=0x0000000040040940

 JRE version: Java(TM) SE Runtime Environment (8.0_101-b13) (build 1.8.0_101-b13)
 Java VM: Java HotSpot(TM) 64-Bit Server VM (25.101-b13 mixed mode linux-amd64 compressed oops)
 Problematic frame:
 C  [ld-linux-x86-64.so.2+0x880f]  do_lookup_x+0xcf

 Core dump written. Default location: /opt/oss/server/core or core.7975

 If you would like to submit a bug report, please visit:
   http://bugreport.java.com/bugreport/crash.jsp
 The crash happened outside the Java Virtual Machine in native code.
 See problematic frame for where to report the bug.

---------------  T H R E A D  ---------------

Current thread (0x000000000060d000):  JavaThread "main" [_thread_in_native, id=7976, stack(0x0000000040000000,0x0000000040041000)]

siginfo: si_signo: 8 (SIGFPE), si_code: 1 (FPE_INTDIV), si_addr: 0x00002b6a7699680f

Registers:
RAX=0x000000000f4d007f, RBX=0x0000000000000000, RCX=0x000000004003def0, RDX=0x0000000000000000
RSP=0x000000004003dd60, RBP=0x000000004003df30, RSI=0x000000000f4d007f, RDI=0x00002aaaca8010b9
R8 =0x00002aaacca83ce0, R9 =0x0000000000000000, R10=0x0000000000000000, R11=0x0000000000000000
R12=0x000000004003def0, R13=0x00002aaacca83a30, R14=0x0000000000000000, R15=0x00002aaaca800320
RIP=0x00002b6a7699680f, EFLAGS=0x0000000000010246, CSGSFS=0xffff000000000033, ERR=0x0000000000000000
  TRAPNO=0x0000000000000000

Top of Stack: (sp=0x000000004003dd60)
0x000000004003dd60:   000000004003dfb0 0000000000000000
0x000000004003dd70:   000000004003def0 00002aaaca800428
0x000000004003dd80:   000000000f4d007f 00002aaaca8010b9
0x000000004003dd90:   0000000000000003 00002aaaca8010b8
0x000000004003dda0:   00002aaaca801c72 0000000076ef2c90
0x000000004003ddb0:   0000000000000000 00002aaacca84a90
0x000000004003ddc0:   0000000000000000 0000000000000000
0x000000004003ddd0:   0000000000000038 00002aaacca83d80
0x000000004003dde0:   000000004003df30 000000004003def0
0x000000004003ddf0:   000000000f4d007f 0000000000000000
0x000000004003de00:   00002aaaca8010b9 00002b6a76996bde
0x000000004003de10:   0000000000000000 00002b6a00000001
0x000000004003de20:   0000000000000000 0000000000000000
0x000000004003de30:   0000000000000000 00002b6a76f4f206
0x000000004003de40:   000000004003de60 0000000000000000
0x000000004003de50:   00002aaacca84a70 00002b6a769993c6
0x000000004003de60:   0000006800000001 00002b6a76aaa628
0x000000004003de70:   0000000000000000 00002aaacca83d78
0x000000004003de80:   000000004003dfe8 00002aaacca83a30
0x000000004003de90:   0000007400000001 00002b6a76eedc50
0x000000004003dea0:   000000004003df60 00002b6a76ef3d44
0x000000004003deb0:   00002aaaca801c24 00002b6a7699bc35
0x000000004003dec0:   000000004003dee0 000000004003df23
0x000000004003ded0:   0000000000000060 00002aaaccacd7d0
0x000000004003dee0:   e718e431408ff081 fe3d3f1d0eefd3ea
0x000000004003def0:   0000000000000000 0000000000000000
0x000000004003df00:   074cfb2cc4c365de 00002aaacca83a30
0x000000004003df10:   00002aaaca800000 00002aaacca83a30
0x000000004003df20:   0000000000000006 00002aaaca8083b0
0x000000004003df30:   000000004003e020 00002b6a769983d8
0x000000004003df40:   0000000000000001 0000000000000000
0x000000004003df50:   00002aaaca800428 00002aaacca83a30 

Instructions: (pc=0x00002b6a7699680f)
0x00002b6a769967ef:   44 24 38 49 8b 9d 20 03 00 00 48 8b 44 24 20 48
0x00002b6a769967ff:   89 5c 24 40 41 8b 95 d8 02 00 00 48 89 d3 31 d2
0x00002b6a7699680f:   48 f7 f3 49 8b 85 e0 02 00 00 44 8b 24 90 45 85
0x00002b6a7699681f:   e4 0f 84 87 01 00 00 c7 44 24 4c 00 00 00 00 48 

Register to memory mapping:

RAX=0x000000000f4d007f is an unknown value
RBX=0x0000000000000000 is an unknown value
RCX=0x000000004003def0 is pointing into the stack for thread: 0x000000000060d000
RDX=0x0000000000000000 is an unknown value
RSP=0x000000004003dd60 is pointing into the stack for thread: 0x000000000060d000
RBP=0x000000004003df30 is pointing into the stack for thread: 0x000000000060d000
RSI=0x000000000f4d007f is an unknown value
RDI=0x00002aaaca8010b9: <offset 0x10b9> in /tmp/sqlite-3.8.10.1-49d93b64-fb56-42fd-8342-b2ef97929604-libsqlitejdbc.so at 0x00002aaaca800000
R8 =0x00002aaacca83ce0 is an unknown value
R9 =0x0000000000000000 is an unknown value
R10=0x0000000000000000 is an unknown value
R11=0x0000000000000000 is an unknown value
R12=0x000000004003def0 is pointing into the stack for thread: 0x000000000060d000
R13=0x00002aaacca83a30 is an unknown value
R14=0x0000000000000000 is an unknown value
R15=0x00002aaaca800320: memset+0x320 in /tmp/sqlite-3.8.10.1-49d93b64-fb56-42fd-8342-b2ef97929604-libsqlitejdbc.so at 0x00002aaaca800000

Stack: [0x0000000040000000,0x0000000040041000],  sp=0x000000004003dd60,  free space=247k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [ld-linux-x86-64.so.2+0x880f]  do_lookup_x+0xcf
C  [ld-linux-x86-64.so.2+0xa3d8]  _dl_relocate_object+0x588
C  [ld-linux-x86-64.so.2+0x10955]  dl_open_worker+0x3e5
C  [ld-linux-x86-64.so.2+0xc756]  _dl_catch_error+0x66
C  [libdl.so.2+0x11fa]  dlopen_doit+0x6a
C  0x00002b6a00000001

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  java.lang.ClassLoader$NativeLibrary.load(Ljava/lang/String;Z)V+0
j  java.lang.ClassLoader.loadLibrary0(Ljava/lang/Class;Ljava/io/File;)Z+328
j  java.lang.ClassLoader.loadLibrary(Ljava/lang/Class;Ljava/lang/String;Z)V+48
j  java.lang.Runtime.load0(Ljava/lang/Class;Ljava/lang/String;)V+57
j  java.lang.System.load(Ljava/lang/String;)V+7
j  org.sqlite.SQLiteJDBCLoader.loadNativeLibrary(Ljava/lang/String;Ljava/lang/String;)Z+29
j  org.sqlite.SQLiteJDBCLoader.extractAndLoadLibraryFile(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z+310
j  org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary()V+224
j  org.sqlite. .initialize()Z+0
j  org.sqlite.core.NativeDB.load()Z+19
j  org.sqlite.core.CoreConnection.open(II)V+355
j  org.sqlite.core.CoreConnection.<init>(Ljava/lang/String;Ljava/lang/String;Ljava/util/Properties;)V+133
j  org.sqlite.jdbc3.JDBC3Connection.<init>(Ljava/lang/String;Ljava/lang/String;Ljava/util/Properties;)V+4
j  org.sqlite.jdbc4.JDBC4Connection.<init>(Ljava/lang/String;Ljava/lang/String;Ljava/util/Properties;)V+4
j  org.sqlite.SQLiteConnection.<init>(Ljava/lang/String;Ljava/lang/String;Ljava/util/Properties;)V+4
j  org.sqlite.JDBC.createConnection(Ljava/lang/String;Ljava/util/Properties;)Ljava/sql/Connection;+24
j  org.sqlite.JDBC.connect(Ljava/lang/String;Ljava/util/Properties;)Ljava/sql/Connection;+2
j  java.sql.DriverManager.getConnection(Ljava/lang/String;Ljava/util/Properties;Ljava/lang/Class;)Ljava/sql/Connection;+171
j  java.sql.DriverManager.getConnection(Ljava/lang/String;)Ljava/sql/Connection;+13

**Comment by gotson** [comment]
Closing this as it's very old. Comment if necessary.
