### ISSUE TITLE
Empty ResultSet does not auto-close Statement

### ISSUE THREAD

**Issue by doe300** [xerial/sqlite-jdbc#148]
The following code does not close the Statement, if the ResultSet is empty (has no results):

```
Statement stmt = con.createStatement();
stmt.closeOnCompletion();  //now closing the ResultSet should close the Statement
ResultSet res = stmt.executeQuery("...");
res.close();
stmt.isOpen();  // will return true
```

The source for this error is `JDBC3Statement#getResultSet()` which sets the `isOpen` flag for the ResultSet depending on whether `resultsWaiting` is set. If no results are waiting, the ResultSet is not set to open and a call to `JDBC4ResultSet#close()` does not close the initiating Statement.

**Comment by gotson** [comment]
Is this still happening on the latest version?

**Comment by gotson** [comment]
Cannot reproduce, it probably got fixed.
