### ISSUE TITLE
Docs: How to build .jar, libs using Makefile

### ISSUE THREAD

**Issue by mike-whittaker-work** [xerial/sqlite-jdbc#150]
OK, I can run 'make linux-armhf' - this generates a libsqlitejdbc.so file down in target

But what I would expect to find somewhere would be
a) a libsqlite.so file (optionally) for use from other languages
b) an sqlite-jdbc.jar file for Java purposes - in target/ I just find the unjarred class files - do I need to make the .jar file manually ?
c) a means to package these into a (eg.) Debian/Opkg container for installation
d) some documentation of the above process in the README files

**Comment by gitblit** [comment]
Hi Mike,

1. This project builds a single native library per OS/arch which contains the combined Java JNI interface code and the compiled SQLite library.  It does not produce a SQLite native library for use by other languages.  This project uses the amalgamated source distribution from SQLite combined with our own [JNI C source](https://github.com/xerial/sqlite-jdbc/blob/master/src/main/java/org/sqlite/core/NativeDB.c).
2. The makefile should call Apache Maven to build the jar file and run the Java JDBC unit tests; this assumes you have Maven and the JDK installed.  When I execute plain `make` the build script builds the .so for my current machine and then properly starts up Maven to execute all unit tests and produce a Maven jar suitable for Maven deployment.
3. The build process does not build any package suitable for distribution through a Linux package manager.  This is beyond the current scope of the project.
4. I agree the documentation is lacking.

**Comment by mike-whittaker-work** [comment]
Thanks - so the combined lib also contains the SQLite 'C' API ? Just to confirm ! That seems to be what you are saying.
I want to cross-build for linux-armhf; I could dig around in the makefile to work it out myself, but what would be the high-level make target to use, to get the jar file built as well as the linux-armhf lib ?
Regards.

**Comment by Atomic-Bean** [comment]
As of the latest release, `make deploy`, which should make a jar file, fails whereas `mvn install` does make a jar file located in the `target/` directory.

It would be much appreciated if the readme was updated to show how to build the jar yourself since, unlike the readme claims, the releases no longer contain the jar.

**Comment by gotson** [comment]
Seems the question was answered, i'm closing this. Comment if necessary.
