### ISSUE TITLE
Drop support for 32-bit Mac OS X

### ISSUE THREAD

**Issue by xerial** [xerial/sqlite-jdbc#152]
According to https://en.wikipedia.org/wiki/Mac_OS_X_Snow_Leopard, MaxOS X Snow Leopard (7 years ago!) is the last release of Mac that support 32-bit CPU architecture.

I have been using VMWare image (Mac OS X Tiger 10.5) to build the native libraries for 32-bit Mac, but it lacks Java 7 support, so we anyway cannot use the current JDBC4 based implementations on 32-bit Mac OS X.

I would like to drop the support for 32-bit Mac OS X because of these technical difficulties. 

@gitblit Any thought?

**Comment by gitblit** [comment]
Kill it.

**Comment by xerial** [comment]
:)

**Comment by cordje** [comment]
@xerial thanks for coming back to this project to update it to the latest sqlite version, much appreciated!

**Comment by xerial** [comment]
Done.
