### ISSUE TITLE
BusyHandlerTest is relatively unstable for slow machines

### ISSUE THREAD

**Issue by xerial** [xerial/sqlite-jdbc#158]
- I often see BusyHandlerTest failure when running tests on VMWare.

**Comment by jlask** [comment]
Not just a VMWare issue, Windows 7 machine I have is not a slow machine but it still gets BusyHandlerTest failures.
I have to run the maven package a few times before I get a successful snapshot build of 3.15.2 and 3.16.1.

**Comment by gotson** [comment]
Closing this as it's very old. Tests are reliable on CI, shouldn't be a problem anymore. Comment if necessary.
