### ISSUE TITLE
FTS5 Support on Windows is missing

### ISSUE THREAD

**Issue by compengi** [xerial/sqlite-jdbc#177]
Hello everyone,

I'm using the fts4 extension and I noticed that since SQLite version 3.9.0 a more mature version of fts5 was  released as well. Since this jdbc driver rocks SQLite version 3.14.2, already makes me wonder why isn't included.

I tried to create an fts5 table but I get an SQLITE_ERROR:

[SQLITE_ERROR] SQL error or missing database (no such module: fts5)

Interestingly enough, the build flag was enabled since this commit https://github.com/xerial/sqlite-jdbc/commit/28882dd0ecbdf4af20c146a2f9c3a96096b99e6f which makes me wonder why I'm receiving this error.

**Comment by xerial** [comment]
@compengi FTS5 actually in-place and works fine. I saw this error when you specify column names for the keyword search. FTS5 requires using `(table name) MATCH 'keyword'`.

**Comment by xerial** [comment]
@compengi See https://github.com/xerial/sqlite-jdbc/blob/8df0b6ccee1a58958cb3b8724a25a0640b2c547b/src/test/java/org/sqlite/ExtensionTest.java#L53 for example.

**Comment by compengi** [comment]
@xerial no the it errors on CREATE.

I ran the test you mentioned on macOS 10.12.1 it went through, on Windows 10 it failed for FTS5.

java.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (no such module: fts5)

	at org.sqlite.core.DB.newSQLException(DB.java:890)
	at org.sqlite.core.DB.newSQLException(DB.java:901)
	at org.sqlite.core.DB.execute(DB.java:810)
	at org.sqlite.core.CoreStatement.exec(CoreStatement.java:74)
	at org.sqlite.jdbc3.JDBC3Statement.execute(JDBC3Statement.java:61)
	at com.exocad.bra.report.parser.test.ExtensionTest.extFTS5(ExtensionTest.java:52)

Please re-open this ticket.

**Comment by xerial** [comment]
OK. Then the title should be FTS5 support on Windows.

**Comment by xerial** [comment]
@compengi I cannot reproduce this error with `mvn test`, which includes test cases for FTS5. I'm using Windows 8.

**Comment by xerial** [comment]
@compengi Could you try using the latest snapshot jar? https://oss.sonatype.org/content/repositories/snapshots/org/xerial/sqlite-jdbc/3.15.0-SNAPSHOT/sqlite-jdbc-3.15.0-20161031.182337-4.jar

**Comment by compengi** [comment]
Yup, the tests execute fine on 3.15.0

I thought it was already added since 3.9.0?

**Comment by compengi** [comment]
I apologize. Something interesting just happened.

I commented out the gradle dependency to try your library. After uncommenting it back, I ran the tests and they went through!

I guess it was a gradle/maven/intellij dependency issue.

Sorry for the confusion :/

I think it's safe to close this ticket.

**Comment by xerial** [comment]
Thanks for the confirmation!
