### ISSUE TITLE
Support to fill on Date with javabeans

### ISSUE THREAD

**Issue by javlaks** [xerial/sqlite-jdbc#18]
It would be possible if you can transform internally the Long value of date to Date?
I did use Apache Commons DbUtils, and it has one feature that is awesome, the ability to create the objects with a BeanProcessor.

This can obtain the data from resultset and fill automatically using javabeans. It detects the data type to fill. And it work fine with all data and other Sql Drivers as MySQL, MariaDB, SqlServer.

But when I use with this library, I obtain an error when transform the Date. The problem is because can't transform the Long value of date to Date. So I need to do manually, but with a lot of fields, this is horrible =S

And sometimes occur problem with the Boolean value using this same technique. I'm not totally sure why this happens.

**Comment by gitblit** [comment]
@javlaks Can you provide a unit test which demonstrates the issue?  `ResultSet.getDate()` should already handle marshalling from `long`, `float`, and `String` to `Date`.

As far as `ResultSet.getBoolean()`, I do see that it assumes an integer type in the database and will not work correctly (or at all?) with a `String` type.

**Comment by gotson** [comment]
Is this still happening on the latest version?

**Comment by gotson** [comment]
Closing this as no feedback was received.
