### ISSUE TITLE
Support for Linux - PPC (native library)

### ISSUE THREAD

**Issue by sderas** [xerial/sqlite-jdbc#181]
Good day:

I was wondering if there are plan to get back the Linux PPC native library that used to be in version 3.7.x of the sqlite-jdbc? 
Would it be to hard to add to the current set?

Thanks.

**Comment by xerial** [comment]
Doocker cross compiler image for ppc64 (little endian) is abilable, so it would be possible to resurrect the support:
dockcross/linux-ppc64le

**Comment by sderas** [comment]
Thanks for the answer, I am closing this one.
