### ISSUE TITLE
Add sqlite-jdbc specific tmpdir

### ISSUE THREAD

**Issue by md-5** [xerial/sqlite-jdbc#185]
Would greatly appreciate a property to set where the native libraries get extracted to specifically for jdbc-sqlite, rather than always using java.io.tmpdir.
This is to deal with the relatively common case that end users have /tmp mounted noexec and we can just use a dir in our cwd instead.

**Comment by xerial** [comment]
Done in 		c8905bf

**Comment by md-5** [comment]
Thanks
