### ISSUE TITLE
SQLiteJDBCLoader.cleanup can cause OutOfMemoryError

### ISSUE THREAD

**Issue by dthulson** [xerial/sqlite-jdbc#198]
If the temp directory has too many files, the call to File.listFiles in SQLiteJDBCLoader.cleanup can cause an out of memory error.  In order to filter the file list, listFiles first loads the entire directory into an array, so if the complete list of filenames takes up more memory than the JVM max heap, it will run out of memory.  While that's something users can in theory avoid by managing what goes into the temp directory, if another user on the machine does something unexpected on a shared box (like say generating millions of files in /tmp!) it can render any application using this library suddenly unusable.

It looks like Java7 introduced support for FileVisitor / FileTreeWalker that should avoid that issue regardless of the number of files that are present in the temp path.  I may be able to contribute a patch to use that instead of File.listFiles, but before I take the time to checkout the code / get it building / etc, can you let me know if you are willing to drop support for Java6?  Let me know, thanks.

**Comment by xerial** [comment]
Dropping support for Java6 is fine :)

**Comment by dthulson** [comment]
Should the .lck file be in the temp directory with the file we are considering deleting?  It looks like the existing code drops the directory path when constructing lckFile.  So for example, it might find "/tmp/sqlite-3.16.2-foobar" and then look for "sqlite-3.16.2-foobar.lck" in the current directory instead of in /tmp.  Is that the correct behavior?

**Comment by xerial** [comment]
No. Both should be in /tmp (given by java.io.tempdir or org.sqlite.tempdir). That can be a bug

**Comment by dthulson** [comment]
Ok, sounds good.  I don't have maven / docker etc to do a build, so I had to pull this out into a temp class to test.  So instead of a nice commit to pull, here's the code that I think works:

```
    private static final SimpleFileVisitor<Path> visitor = new SimpleFileVisitor<Path>() {
        private final String prefix = "sqlite-" + getVersion();
        private final String lckSuffix = ".lck";
        
        @Override
        public FileVisitResult visitFile(Path file, BasicFileAttributes attrs) throws IOException {
            if ((file != null) && !Files.isDirectory(file)) {
                Path namePath = file.getFileName();
                if (namePath != null) {
                    String name = namePath.toString();
                    if (name.startsWith(prefix) && !name.endsWith(lckSuffix)) {
                        Path lckFile = file.resolveSibling(name + lckSuffix);
                        if (!Files.exists(lckFile)) {
                            Files.delete(file);
                        }
                    }
                }
            }
            return FileVisitResult.CONTINUE;
        }
    };

    /**
     * Deleted old native libraries e.g. on Windows the DLL file is not removed
     * on VM-Exit (bug #80)
     */
    static void cleanup() {
        try {
            Files.walkFileTree(Paths.get(getTempDir().getAbsolutePath()), EnumSet.of(FileVisitOption.FOLLOW_LINKS), 1, visitor);
        } catch (IOException|SecurityException e) {
            System.err.println("Failed to delete old native lib" + e.getMessage());
        }
    }
```

Definitely worth testing yourself.  You may want to / need to allocate a new FileVisitor instead of reusing the same one.  I'm not sure about getVersion using SQLiteJDBCLoader.class in order to init a static final member of that class, I just stubbed getVersion out for my testing.

Anyway, sorry I can't get you a better patch.

**Comment by xerial** [comment]
Thanks. I'll take a look
