### ISSUE TITLE
pragma values not read in from db

### ISSUE THREAD

**Issue by jpenglert** [xerial/sqlite-jdbc#204]
Pragma values are not read in from DB when establishing a connection. I noticed this while attempting to use the "user_version" pragma to track schema changes. Setting the "user_version" pragma will write to the DB but opening that DB later on will not populate SQLConfig with any pragma values from the DB.

Could all of the pragma values be read in from the DB and cached in SQLConfig when opening a DB?

Current workaround in kotlin:

    fun readUserVersionPragma(ds: SQLiteDataSource) {
        val stmt = connection.createStatement()
        try {
            val rs = stmt.executeQuery("PRAGMA ${SQLiteConfig.Pragma.USER_VERSION.pragmaName}")
            if (rs.next()) {
                val value = rs.getInt(1)
                ds.setUserVersion(value)
            }
        }
        finally {
            stmt?.close()
        }
    }

**Comment by gotson** [comment]
Shouldn't be done by the driver IMO, but by the application.

Closing as very old, please comment if necessary.
