### ISSUE TITLE
Download Link Dysfunctional on Readme Page

### ISSUE THREAD

**Issue by tzm41** [xerial/sqlite-jdbc#206]
The download link in readme still points to bitbucket, which give 404 when clicked.

**Comment by FalconDrop** [comment]
+1 @tzm41  comment

**Comment by mirrish** [comment]
This worked for me: [http://bitbucket.org/xerial/sqlite-jdbc/downloads/sqlite-jdbc-3.14.2.1.jar](http://bitbucket.org/xerial/sqlite-jdbc/downloads/sqlite-jdbc-3.14.2.1.jar)

**Comment by FalconDrop** [comment]
thanks @mirrish im about to try this now

**Comment by SuperJonotron** [comment]
Download link on the readme and mentioned in this thread are both broken.  Anybody know of another valid jdbc download?

**Comment by tzm41** [comment]
Yes, please use: https://oss.sonatype.org/content/repositories/releases/org/xerial/sqlite-jdbc/3.16.1/sqlite-jdbc-3.16.1.jar

**Comment by xerial** [comment]
Download page at bitbucket is back. https://bitbucket.org/xerial/sqlite-jdbc/downloads/
Let me close this ticket.
