### ISSUE TITLE
Support for Alpine Linux / musl

### ISSUE THREAD

**Issue by lyderic** [xerial/sqlite-jdbc#209]
Hello,

While not impossible, building the jar file for Alpine Linux - that is based on musl and not glibc - is pretty painful and undocumented.

Knowing that Alpine is the most popular small Docker image, I would suggest that the Linux musl build is included in the default distribution, pullable from Maven Central.

Is that realistic?

Thanks,
Lyderic

**Comment by tl-relayr-io** [comment]
sqlite-jdbc tries to use Linux/86_x64 native library added as resources to the jar file. But there is possibility to use another one by setting property org.sqlite.lib.path (in meaning the absolute path to directory where library is stored). There is another optional  org.sqlite.lib.file property.
You can prepare the library for Alpine linux using the source of sqlite-jdbc and file included: docker/Dockerfile.alpine-linux_x86_64
In the first line of that file you can force the version of Alpine linux (eg. "FROM alpine:3.3").

**Comment by gotson** [comment]
Latest version support musl based Linux.
