### ISSUE TITLE
Support for pre-installed SQLite library

### ISSUE THREAD

**Issue by kroggen** [xerial/sqlite-jdbc#210]
Hi!

Sometimes we want to use our modified SQLite library, eg. with [litereplica](http://litereplica.io) or [sqlcipher](https://www.zetetic.net/sqlcipher/) or [SEE](https://www.sqlite.org/see) or even with private modifications.

It would be cool if we could access the pre-installed library from sqlite-jdbc.

Could we do it?

If for some reason this is not possible, it would be good to have an easy way to compile it using our modified SQLite code. Maybe changing the Makefile to accept some parameter were we inform where is the path for the folder containing the SQLite files (sqlite3.c and sqlite3.h)

**Comment by xerial** [comment]
No. Because sqlite-jdbc.so has additional code to the original SQLite. 
We need to re-compile it for every possible combinations of SQLite build options.

**Comment by xerial** [comment]
If your modification to SQLite can be done like this:
https://github.com/xerial/sqlite-jdbc/blob/e3766561261cecadd5eba9cc13cb23c8e1bf0f52/Makefile#L57-L59

It would be possible to use your own SQLite by tweaking Makefile.

**Comment by kroggen** [comment]
Hmmm...

Why do you change the sqlite3.c file to load an extension?

I guess this is not required.

We can call the [sqlite3_load_extension()](https://sqlite.org/c3ref/load_extension.html) function or even use the [load_extension(X,Y)](https://sqlite.org/loadext.html) SQL function.

Is it because you don't want to have the extension library as an external file?

**Comment by kroggen** [comment]
Anyway, if this is required we can still use a modified sqlite3.c file because this small modification may not cause a problem.

The makefile would just use the file already downloaded, then make its own modification you showed and then compile it.

For me it is sufficient, and it will help some people.

I can help testing.

What do you think?

**Comment by xerial** [comment]
FYI https://github.com/xerial/sqlite-jdbc/blob/master/src/main/ext/extension-functions.c
extension-function.c of SQLite has a frequently used functions, and to simplify the loading process for cross platforms (windows, Linux, etc.) these libraries are pre-loaded.

**Comment by kroggen** [comment]
I could change this line:

https://github.com/xerial/sqlite-jdbc/blob/e3766561261cecadd5eba9cc13cb23c8e1bf0f52/Makefile#L18

from this:

`SQLITE_AMAL_DIR=$(TARGET)/$(SQLITE_AMAL_PREFIX)`

to this:

`SQLITE_AMAL_DIR?=$(TARGET)/$(SQLITE_AMAL_PREFIX)`

Just adding the question sign. With this, the variable will receive this value only if it was not previously set.

So those wanting to specify another path can use:

`make SQLITE_AMAL_DIR="/path/to/sqlite-source"`

And the makefile will continue working the same way if we don't set the additional parameter.

BUT, there is the `SQLITE_UNPACKED` variable, that depends on the `SQLITE_ARCHIVE`.

I guess we will have to create (touch) the file referenced at `SQLITE_UNPACKED` if (and only if) `SQLITE_AMAL_DIR` was set in the command line.

Do you have any suggestion?

**Comment by kroggen** [comment]
Hi Taro!

I made some changes. You can check them in this [commit](https://github.com/kroggen/sqlite-jdbc/commit/68f919c1b8379bb9d94e55eee9458fe0f71aca9e).

If you agree, I can make a PR.

It would be nice to rename the variable name too, if possible. From `SQLITE_AMAL_DIR` to `SQLITE_SOURCE`, so the command line would be:

`make SQLITE_SOURCE="/path/to/sqlite-source"`

But if you don't want, it is fine.

It was only tested with gcc.

**Comment by xerial** [comment]
Using `SQLITE_SOURCE` is OK. Please create a PR modified accordingly.

**Comment by kroggen** [comment]
There is an error on travis. I will check and try to fix it.

**Comment by kroggen** [comment]
OK, working now.

The error was because I retyped the modifications instead of copying from my makefile, so there were some typos.

**Comment by xerial** [comment]
Merged #211

**Comment by kroggen** [comment]
Wow, so nice!

Thank you!
