### ISSUE TITLE
Why does Statement and ResultSet classes implement finalize method?

### ISSUE THREAD

**Issue by qiuxiafei** [xerial/sqlite-jdbc#217]
Recently I encountered a GC problem with sqlite-jdbc which was caused by the `finalize` methods in `ResultSet` and `Statement` implementation classes. In my case, the incoming requests varies a lot so that we couldn't fit them into several prepared statement, we had to prepare a statement for each request. 
In java, all objects who implement the `finalize` method will be linked into a `finalize queue` and there `finalize` method will be executed in a serialized way when GC happens. If there's too many objects in the queue, the gc time increase incredibly. And in common java practice, implementing the `finalize` method is NOT a good choice.
So my questions are:
1. What's the purpose of sqlite-jdbc to implement `finalize` method? Is is necessary?
2. If it's necessary, is there a better way for my scenario？

Here comes my testing code:

```java
import java.io.File;
import java.lang.management.ManagementFactory;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ThreadLocalRandom;

/**
 * @author qiuxiafei
 * @date 2017/4/22
 */
public class Query2 {
    private static final int THREAD_NUM = 4;
    private static final int QUERY_PER_THREAD = 4000000;

    public static void main(String[] args) throws InterruptedException {
        System.out.println(ManagementFactory.getRuntimeMXBean().getName());
        long start = System.currentTimeMillis();
        List<Thread> threads = new ArrayList<>();
        for (int i = 0; i < THREAD_NUM; i++) {
            Thread t = new Thread(() -> {
                try {
                    System.err.println("Thread start: " + Thread.currentThread().getId());
                    long queryStart = System.currentTimeMillis();
                    String url = new File("./db.sqlite").getCanonicalFile().toURI().toURL().toString()
                        + "";
                    Connection conn = DriverManager.getConnection("jdbc:sqlite:" + url);


                    for (int j = 0; j < QUERY_PER_THREAD; j++) {
                        PreparedStatement stmt = conn.prepareStatement("select * from test_t where a = ?;");
                        stmt.setInt(1, ThreadLocalRandom.current().nextInt(10000000));
                        ResultSet rs = stmt.executeQuery();
                        while (rs.next()) {
                            rs.getInt(1);
                        }
                        stmt.close();
                        rs.close();
                    }
                    long time = System.currentTimeMillis() - queryStart;
                    double rt = 1.0 * time / QUERY_PER_THREAD;

                    System.out.println(String
                        .format("Thread: %d finish, cost: %d, rt: %.2f", Thread.currentThread().getId(), time, rt));

                } catch (Exception e) {
                    e.printStackTrace();
                }

            });
            threads.add(t);
            t.start();
        }

        for (Thread t : threads) {
            t.join();
        }

        System.err.println("Total cost: " + (System.currentTimeMillis() - start));
    }
}
```
The testing table is created by the following and has 10000000 records:

```sql
create table test_t (a integer primary key, b integer, c integer, d string);
```

**Comment by erhan14** [comment]
We are facing the same issue currently. Is there a workaround that you implemented?

**Comment by qiuxiafei** [comment]
@erhan14 We changed the code and recompiled a new jar.

**Comment by trohwer** [comment]
I think, some native (sqlite3) resources need to be deallocated (see DB.finalize() calls). If people don't call statement.close()
(or the code path is omitted due to exceptions etc.), there would a leak. E.g. in your example, you forget to call close on your connections as well, so that easily happens.
There may be ways to optimize the processing, e.g. speeding up the code, in case close() has been called explicitly or using phantom references.
