### ISSUE TITLE
Please release an update to Maven Central

### ISSUE THREAD

**Issue by gitblit** [xerial/sqlite-jdbc#22]
There are several important improvements stuck in Git:
#8 
#13 
#14 
#27
#30
#31

**Comment by gitblit** [comment]
@xerial How can I assist in moving forward with a new release?  The current stable SQLite is now @ 3.8.9, BTW.

**Comment by gitblit** [comment]
The reason I'm nagging you to push a new release is because the above referenced improvements have significant performance gains - mostly from the SAVEPOINT implementation but also from the PRAGMA url parameters.

I'll give you a concrete example.  I maintain a small/modest ORM project.  As part of that project I unit test & benchmark multiple databases and generate a summary table at the conclusion of the test suite.  You might find this interesting.

<pre>
*******************************************************************************
iciql 0.0.0-SNAPSHOT (PENDING) test suite performance results
      on Oracle Corporation 1.8.0_40-b25, Linux 3.13.0-24-generic, amd64
*******************************************************************************
Name        Config           Version                   Stats/sec  Runtime
-------------------------------------------------------------------------------
SQLite      memory           3.8.8                     19478      0.2s  (1.0x)
SQLite      memory           3.8.7                     18995      0.2s  (1.0x)
SQLite      wal,norm_sync    3.8.8                     16963      0.3s  (1.1x)
SQLite      wal,no_sync      3.8.8                     15906      0.3s  (1.2x)
SQLite      delete,no_sync   3.8.8                     14781      0.3s  (1.3x)
HSQL        memory           2.3.2                      9031      0.5s  (2.2x)
H2          file             1.4.186 (2015-03-02)       8875      0.5s  (2.2x)
HSQL        file             2.3.2                      5498      0.8s  (3.5x)
H2          tcp              1.4.186 (2015-03-02)       4887      0.9s  (4.0x)
H2          memory           1.4.186 (2015-03-02)       4751      1.0s  (4.1x)
HSQL        tcp              2.3.2                      1804      2.5s  (10.8x)
Derby       memory           10.11.1.1 - (1616546)      1271      3.6s  (15.3x)
SQLite      wal,full_sync    3.8.8                      1013      4.5s  (19.2x)
PostgreSQL  tcp              9.3.6                       687      6.7s  (28.3x)
SQLite      delete,norm_sync 3.8.8                       504      9.1s  (38.6x)
<b>SQLite      delete,full_sync 3.8.8                       369     12.4s  (52.7x)</b>
Derby       file             10.11.1.1 - (1616546)       282     16.3s  (69.1x)
Derby       tcp              10.11.1.1 - (1616546)       248     18.5s  (78.5x)
MySQL       tcp              5.6.19-0ubuntu0.14.04.1     220     20.9s  (88.4x)
<b>SQLite      delete,full sync 3.8.7                       136     33.7s  (139.1x)</b>
-------------------------------------------------------------------------------
</pre>

Note the highlighted differences between 3.8.7 (released) and 3.8.8 (master).  That is solely due to the SAVEPOINT changes merged in #13.

Updates to my ORM project have been sitting in limbo for 6 months waiting for the next release of this project. Please, please, please with sugar on top, can we move forward with a new release?

**Comment by ravermeister** [comment]
so are there any plans in releasing  a new build?

**Comment by gitblit** [comment]
Only the Linux x86 and x64 binaries have been updated to 3.6.9.

@xerial can you build the OSX binaries and Windows binaries?
@alexdupre can you build updated FreeBSD binaries?
@roedll can you build updated Linux/ARM binaries?

**Comment by xerial** [comment]
Just released 3.8.9, but I failed to include FreeBSD binaries. If @alexdupre can build it, I'll welcome the contribution.

**Comment by xerial** [comment]
I'm really sorry for the long delay of a new release. Today is a holiday in Japan, and I finally got a time to work on this.
