### ISSUE TITLE
Exception on Android

### ISSUE THREAD

**Issue by farzad-kafami** [xerial/sqlite-jdbc#222]
I run sample code on android device and and get this exception
`java.sql.SQLException: No suitable driver`
can anyone run this library on android?
can you help me please

**Comment by psini** [comment]
yes but plese spcify more detail. gradle build file with dependency and how you call the driver to get a connection. For android you have to remenber to exctract the right so file in the native dir for packaging

**Comment by gotson** [comment]
Closing this as it is an old issue. Please leave a comment if needed.
