### ISSUE TITLE
PreparedStatements cannot be used for single queries after being used in batches

### ISSUE THREAD

**Issue by wmeehan** [xerial/sqlite-jdbc#229]
Calls to `execute()` check for arity mismatch by comparing the number of params not to the actual number of values, but the [length of the value array](https://github.com/xerial/sqlite-jdbc/blob/master/src/main/java/org/sqlite/core/DB.java#L798). The [value array is the same as the batch array](https://github.com/xerial/sqlite-jdbc/blob/master/src/main/java/org/sqlite/core/DB.java#L798), which means that after a call to `addBatch()`, the array has grown larger than the actual number of values. A potential solution would add an `batchEndPos`, preventing values from being set outside of the current batch and giving an accurate arity check for the current query

**Comment by necouchman** [comment]
I'm not sure if this is related, but I'm running into an issue trying to use this SQLite JDBC driver with MyBatis, and executing multiple select statements at once, on different tables, but using a <foreach> loop to feed the same parameters to both SELECT queries within the same <select></select> block.  The result, at the moment, is an ArrayIndexOutOfBoundsException when it tries to prepare the statement.

This same code works on MySQL, Oracle, PostgreSQL, and SQL Server, as well as H2, but is failing on SQLite.  It looks like what may be happening is that the array index is supposed to get reset to 0 after each query (at the semicolon), or perhaps in each <foreach> loop, but, for some reason in the SQLite driver it is not getting reset there and is just continuing to count up, resulting in it trying to prepare a statement with twice the number of parameters it should be using, which throws the exception.  This sounds similar/related to what is described here, though I'm not entirely certain it is - could be a different issue.

**Comment by gotson** [comment]
Is this still happening on the latest version?

**Comment by gotson** [comment]
Closing this as no feedback was received.
