### ISSUE TITLE
how can I get lastInsertRowId,changes,escapeString,lastErrorCode using sqlite-jdbc?

### ISSUE THREAD

**Issue by baibav** [xerial/sqlite-jdbc#23]
I recently started using sqlite for my new java project but how can I get the values of lastInsertRowId ,number of rows affected on previous query and also an inbuilt method to escape string(not necessary as prepare statement can do the job as well) .

**Comment by kaiwinter** [comment]
I'm using the following snipped which is working fine. For escaping your parameters use the prepared statement.
```java
Connection connection = ...
String query = ...
try (PreparedStatement statement = connection.prepareStatement(query)) {
    int affectedRows = statement.executeUpdate();
    if (affectedRows == 0) {
        throw new SQLException("Insert failed");
    } else {
        ResultSet generatedKeys = statement.getGeneratedKeys();
        if (generatedKeys.next()) {
            long lastInsertRowId = generatedKeys.getLong(1);
        }
    }
}
```

**Comment by gitblit** [comment]
The standard error code is supplied in raised exceptions and as of #119, the extended error code is also included if you cast the raised exception to an `SQLiteException`.
