### ISSUE TITLE
Table locked after query sqlite_master

### ISSUE THREAD

**Issue by jianlins** [xerial/sqlite-jdbc#238]
Hello, I got an table locked error after query sqlite_master. For instance, I tried 
"SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name='INPUT_TABLE'",
then the table "INPUT_TABLE" is locked. And I cannot execute 
"DROP TABLE INPUT_TABLE".

I tried this on sqlite shell, there is no error in shell. So I guess this is due to the jdbc.

Thanks

**Comment by gotson** [comment]
Is this still happening on the latest version?

**Comment by gotson** [comment]
Closing this as no feedback was received.
