### ISSUE TITLE
getPrimaryKeys now working for views

### ISSUE THREAD

**Issue by starhel** [xerial/sqlite-jdbc#239]
**Description**
getPrimaryKeys in sqlite-jdbc raises SQLException with message "Table not found: '...'". In other jdbc (mysql, postgres) it returns empty list. Metabase (BI app) depends on this, so I'd like to fix this in driver. 

**Metabase stacktrace**
` [{:type java.sql.SQLException
   :message Table not found: 'view_table'
   :at [org.sqlite.jdbc3.JDBC3DatabaseMetaData$PrimaryKeyFinder <init> JDBC3DatabaseMetaData.java 1886]}]`

**Comment by xerial** [comment]
Fixed in #239. THanks
