### ISSUE TITLE
Time Literal DateFormat Parsing

### ISSUE THREAD

**Issue by danap** [xerial/sqlite-jdbc#24]
According to the jdbc4.0 ref. which I'm sure a new version is available, the following Date & Time
Literals have the format. 

Date: {d, 'yyyy-mm-dd'}, Time:{t, 'hh:mm:ss'}, Timestamp: {ts, 'yyyy-mm-dd hh:mm:ss.f...'}

I would assume therefore if a TEXT data type field has the contents 2015-03-22 and contents are
returned via getDate() then I would not expect a date parse error would occur. Currently the
getDate() function is using a common DateFormat for all three of the time literals of
{yyyy-MM-dd HH:mm:ss.SSS}.

I would like to propose the SQLiteConfig class define the appropriate static instances of
DEFAULT_DATE_STRING_FORMAT, DEFAULT_TIME_STRING_FORMAT, & DEFAULT_TIMESTAMP_STRING_FORMAT along
with associated instances to be used in the resultSet returns for getDate(), getTime(), and
getTimeStamp(). It appears the setting methods are working appropriately.

If this is acceptable then I could perform the coding and submit for review and update. Perhaps
this issue is similar to open #18? 

Thank you for your work in keeping the best option for the sqlite-jdbc current.

Dana Proctor
MyJSQLView Project Manager

**Comment by danap** [comment]
Hello,

I have implemented the proposal indicated above and done the initial testing. The issue with date
parsing error is no longer occuring. No changes need be done for the setter methods except the
setDateByMilliseconds() method. The changes would define strict definitions to the Date & Time
Literal, as indicated above, with the exception for Timestamps being (yyyy-mm-dd hh:mm:ss).

I can submitt these changes for review if they seem an appropriate solution for date parsing
errors. My review of the initial code does not appear to have these issues because no DateFormat
aspects were not applied.

Dana Proctor
MyJSQLView Project Manager

**Comment by danap** [comment]
Hello,

I have implemented the proposal indicated above and done the initial testing. The issue with date
parsing error is no longer occuring. No changes need be done for the setter methods except the
setDateByMilliseconds() method. The changes would define strict definitions to the Date & Time
Literal, as indicated above, with the exception for Timestamps being (yyyy-mm-dd hh:mm:ss).

I can submitt these changes for review if they seem an appropriate solution for date parsing
errors. My review of the initial code does not appear to have these issues because no DateFormat
aspects were applied.

Dana Proctor
MyJSQLView Project Manager

**Comment by danap** [comment]
Hello,

I have created a Pull request #33 for review to address the issue indicated.

Dana Proctor
MyJQLView Project Manager

**Comment by TuomasKiviaho** [comment]
There's also the `JDBC3PreparedStatement` involved in this when you use `date_class=text`. The `setTime`,  `setTimestamp` and `setDate` do not work as expected.

**Comment by sirajka** [comment]
Is this related to the below exception? If not I can start a new issue.

Using `current_timestamp` in insert statement, SQLite stores it without milliseconds which causes the exception below on a subsequent read.

`Caused by: java.text.ParseException: Unparseable date: "2017-02-10 01:03:29" does not match (\p{Nd}++)\Q-\E(\p{Nd}++)\Q-\E(\p{Nd}++)\Q \E(\p{Nd}++)\Q:\E(\p{Nd}++)\Q:\E(\p{Nd}++)\Q.\E(\p{Nd}++)
	at org.sqlite.date.FastDateParser.parse(FastDateParser.java:299)
	at org.sqlite.date.FastDateFormat.parse(FastDateFormat.java:490)
	at org.sqlite.jdbc3.JDBC3ResultSet.getTimestamp(JDBC3ResultSet.java:529)`

**Comment by danap** [comment]
Hello,

As far I know this issue has been addressed in other
changes implemented over a year ago. My proposed
pull was not accepted.

I would open another issued.

I thought I have requested this be close long ago.

danap.
