### ISSUE TITLE
Travis build failing for openjdk6

### ISSUE THREAD

**Issue by starhel** [xerial/sqlite-jdbc#241]
Ubuntu Trusty 14.04 is now default distribution for build. Because of this, all builds with openjdk6 are failing, but Java 6 is no longer supported and available on Oracle's website. 

There are two (or more) solutions:
1. Add *dist: precise* to *.travis.yml* to force old version of ubuntu.
2. Stop supporting Java 6, which I suggest.

**Comment by xerial** [comment]
#244 (and removed openjdk6 build)
Reported the issue to https://github.com/travis-ci/travis-ci/issues/8199
