### ISSUE TITLE
Update Readme to Point to Github Issues instead of BitBucket Issues

### ISSUE THREAD

**Issue by mlococo** [xerial/sqlite-jdbc#242]
Per #7, github is now the preferred location to report issues, but README.md still points to still points to the bitbucket issues in https://github.com/xerial/sqlite-jdbc/blame/9833b1174b629b5a8956e93e04a88468c95081de/README.md#L32

Should that point to github at this point?

**Comment by mlococo** [comment]
Looks like downloads point to bitbucket as well even though the github repo here has downloadable releases:

1. https://github.com/xerial/sqlite-jdbc/blame/9833b1174b629b5a8956e93e04a88468c95081de/README.md#L5
2. https://github.com/xerial/sqlite-jdbc/blame/9833b1174b629b5a8956e93e04a88468c95081de/README.md#L45
3. https://github.com/xerial/sqlite-jdbc/blame/9833b1174b629b5a8956e93e04a88468c95081de/README.md#L45
4. https://github.com/xerial/sqlite-jdbc/blame/9833b1174b629b5a8956e93e04a88468c95081de/README.md#L288

**Comment by sualeh** [comment]
The build instructions also point to Bitbucket.

**Comment by sualeh** [comment]
@xerial suggests that the download links continue to point to BitBucket.
