### ISSUE TITLE
JVM crashes with segmentation fault

### ISSUE THREAD

**Issue by LMnet** [xerial/sqlite-jdbc#245]
I'm using sqlite-jdbc in the scala app. I deploy this app as a docker container into the local kubernetes cluster. And sometimes my app crashes with segmentation fault. Here are two crash dumps:
https://pastebin.com/jQcjcCTQ
https://pastebin.com/tBKMTvpk

All I do - is validating schema on the app start and reading some data from db. sqlite is using as read-only db. I use simple scala jdbc wrapper called scalikejdbc for db access. I don't have any specific settings or hacks around sqlite.

I have absolutely no idea how to investigate this issue. This crashes occurs ~1-3 times per day. Maybe kubernetes and docker somehow affects?

I found a few issues on the bitbucket about JVM crashes, but they were not helpful.

**Comment by ilysha-v** [comment]
As a result we were fixed that problem when we begin use new connection for every query, and connection opens in thread, where query will be executed. 
As a docs say SQLite have support for shared connections (https://sqlite.org/c3ref/c_config_covering_index_scan.html#sqliteconfigserialized), but looks like there is some problems with that. In our readonly usage mode new connection per query doesnt make some negative impact on perfomance, so I think it can be some kind of solution.

**Comment by gotson** [comment]
Is this still happening on the latest version?
