### ISSUE TITLE
CSV module - feature request

### ISSUE THREAD

**Issue by binkley** [xerial/sqlite-jdbc#250]
I would like to use the csv module to create a virtual table (https://sqlite.org/csv.html).

I found the fts5 module is baked into the jar, but not csv.

**Comment by binkley** [comment]
Some poking reveals the `csv` extension is not baked into SQLite's binaries, it's an add-on from their "misc" collection:

https://www.sqlite.org/src/finfo?name=ext/misc/csv.c

**Comment by takacsot** [comment]
Er even just a fast CSV import. The sqlite CLI is more then 10x faster then batch insert through jdbc driver.

**Comment by gotson** [comment]
You can enable extension loading and load the extension if you need it.
