### ISSUE TITLE
ClassNotFoundException when trying to use SQLite with ONOS app (Maven)

### ISSUE THREAD

**Issue by reservoirman** [xerial/sqlite-jdbc#258]
Hello, I am following the instructions per xerial's website, by adding this dependency to my ONOS app's pom.xml:
https://github.com/xerial/sqlite-jdbc#using-sqlitejdbc-with-maven2

```
<dependencies>
    <dependency>
      <groupId>org.xerial</groupId>
      <artifactId>sqlite-jdbc</artifactId>
      <version>3.8.6</version>
    </dependency>
</dependencies>
```

I saw the jar file download just fine.  I can even import org.sqlite.JDBC just fine as well.  Nonetheless, I still get the following exception:

`java.lang.ClassNotFoundException: org.sqlite.JDBC not found by org.tsg.inspector [181]`

I am not using IntelliJ, strictly through the CLI and Maven for compilation.  Could there be other dependencies that I need?  If you have any insight, that would be great!!

**Comment by sualeh** [comment]
The jar file may not be on your **runtime** classpath, even though it is on your **compile-time** classpath. Please take a look at the following resources:
1. https://stackoverflow.com/questions/30651429/popular-error-org-sqlite-jdbc
2. https://stackoverflow.com/questions/44125407/java-lang-classnotfoundexception-org-sqlite-jdbc-error-in-java-netbeans-8-2

**Comment by reservoirman** [comment]
I thought Maven takes care of adding the jar file to your runtime classpath for you though.  Nonetheless will try tonight.  Thanks!

**Comment by sualeh** [comment]
If you use the command-line interface (CLI as you mentioned above) to run your Java program, Maven will not manage the run-time classpath. Please close this issue when you have solved the issue.

**Comment by gotson** [comment]
Seems the question was answered, i'm closing this. Comment if necessary.
