### ISSUE TITLE
Driver does not allow proper (class) garbage collection

### ISSUE THREAD

**Issue by trohwer** [xerial/sqlite-jdbc#267]
In deployments with dynamic classloaders (e.g. web container), the sqlite driver is not properly garbage collected. Even if one deregisters the driver explicitly from the DriverManager, the global jni references (see NativeDB.c)

static jclass dbclass = 0;
static jclass  fclass = 0;
static jclass  aclass = 0;
static jclass pclass = 0;
static jclass phandleclass = 0;

prevent the classes from being garbage collected. This can be a problem, since that keeps the whole classloader and all associated classes in memory. Another minor leak is the data associated with the deleteOnExit() calls on temporary files, that keep accumulating.

An approach to fix the first problem might be:
- provide native method to clear the static references
- add finalize method or register phantomreference to call this clear method, once sqlite JDBC Driver instance is garbage collected
- reference sqlite JDBC Driver instance from connections to prevent this before all connections are garbage collected

If there is interest in getting this fixed this way, I might work on it.

**Comment by xerial** [comment]
Basically I ageee with your suggested direction. I'd appreciate a PR. Thanks

**Comment by trohwer** [comment]
I found a less intrusive, more elegant solution (see pull request).

**Comment by trohwer** [comment]
One issue with my originally suggested approach is for example, that the driver class org.sqlite.JDBC has a public constructor, so even if the original instance, that is registered with the DriverManager, is gced, users might just create another one. With the references cleared, this will yield an error on the second instance.

**Comment by yigit** [comment]
the PR seems to fix the issue reported here as well:
https://issuetracker.google.com/issues/62473121

**Comment by trohwer** [comment]
Ok, good to know.
Note, that there is still be a minor leak with the deleteOnExit. In practise this should not matter, as this adds only two Strings (for the file paths) per initialization (see DeleteOnExitHook). I have an idea to fix that (try to delete the files right after loadNativeLibrary call; on Unix this should delete the files; on Windows it won't delete the library, but the deleteOnExit apparently does not do this either).

**Comment by yigit** [comment]
@xerial is there an ETA for a release w/ this fix? 
The impact of this issue is rather significant for people using Android's new persistence library.
We can possibly ship a binary w/ the modified Xerial build but we would prefer to have it as a maven dependency to avoid conflicts with other libs that might depend on Xerial.

**Comment by yigit** [comment]
@xerial, sorry to ping again but is it possible for you to take a look at this. We really need this bugfix and would be awesome to depend on new xerial build instead of compiling it ourselves.

**Comment by PaulWoitaschek** [comment]
Any news on this? I need to do a full rebuild every few builds  :(

**Comment by trohwer** [comment]
The fix has been merged now, but in terms of release schedule, you have to ask xerial.

**Comment by sualeh** [comment]
@trohwer - please email me at sualeh@hotmail.com
