### ISSUE TITLE
A CoreConnection can not be shared between threads

### ISSUE THREAD

**Issue by gitblit** [xerial/sqlite-jdbc#28]
`CoreConnection` as written is not thread-safe when parsing dates.  This is due to the use of `public final DateFormat dateFormat` which uses `SimpleDateFormat`.   SimpleDateFormat is known to be thread-*unsafe*.

This becomes a bigger issue with `SQLitePooledConnection` which generates a dynamic proxy of the `CoreConnection`.  I think we should eliminate the `DateFormat` instance and generate one when it's needed from the configured datetime pattern.

I can put together a PR, if you wish.

**Comment by xerial** [comment]
An option is to use jodatime, but it adds a library dependency to sqlite-jdbc. I hope sqlite-jbdc works as a stand-alone library.

If there is a good library in JDK for date parsing, I recommend to use that.

**Comment by xerial** [comment]
Probably #41 fixes this.
