### ISSUE TITLE
Question/Feature request: read from in-memory location

### ISSUE THREAD

**Issue by paulvi** [xerial/sqlite-jdbc#281]
There is use case where we unzip sqlite .db file in file system and that read it as
 
      conn = DriverManager.getConnection("jdbc:sqlite:" + path + "");

Is there possibility to read from in-memory location (e.g. using Java 'java.io.InputStream' or just from array `byte[] bytes`)?

That would eleminate needs for I/O when we just need to read content from memory (e.g. unzipped bytes array.)

**Comment by sualeh** [comment]
sqlite-jdbc interfaces with SQLite native libraries, which need a database file. The driver possibly could unzip a file to a temporary location, before using the database, but we would have to see if there is a widespread need for this enhancement.

**Comment by paulvi** [comment]
I looked through docs at https://www.sqlite.org/inmemorydb.html and the only way to start from `:memory:` database is creating new, not from an existing bytes.

I don't think it should be job of driver to create do (un)zipping, temp file(s) creation, etc.

It seems that this requests, depends on SQLite itself.

**Comment by sualeh** [comment]
Paul, I agree that this does not belong in the JDBC driver

**Comment by paulvi** [comment]
Though could this ticket (or other one) be kept open to see if bunch of people would like to create in-memory instance from bytes/stream?

**Comment by sualeh** [comment]
Paul, I think that creating an in-memory instance from a byte-stream would not be a function of the JDBC driver, if SQLite does not support it, but that it would probably be better implemented as a new project.
