### ISSUE TITLE
SQLITE_MAX_ATTACHED needs to be changed to support at attach of 20 DBs at runtime, but .so is not supporting the same

### ISSUE THREAD

**Issue by RameshUmmalaraju2001** [xerial/sqlite-jdbc#291]
Hi Admin,

We have a requirement to change the SQLITE_MAX_ATTACHED value to support 20 dbs in runtime. We belive java code uses libsqlitejdbc.so for all sqlite functionality.But we couldn't get the source code for libsqlitejdbc.so to rebuild by changing the SQLITE_MAX_ATTACHED. Can you please rebuild or let us know how to rebuild the ".so" to support attach of 20dbs in runtime via java code. 

Kindly update me asap, as this is needed in urgent basis.

Thanks,
Ramesh Ummalaraju
ramesh.ummalaraju1990@gmail.com

**Comment by xerial** [comment]
You can add this kind of configuration around here:
https://github.com/xerial/sqlite-jdbc/blob/master/Makefile#L79

- Install docker to your system
- And run:
```
$ make 
```
Then you can find target/sqlite-jdbc-(version).jar.

If you need a complete sqlite-jdbc jar which supports various OSs, run `make native-all package`

**Comment by gotson** [comment]
Closing as limits can now be changed at runtime.
