### ISSUE TITLE
Build instructions do not mention docker

### ISSUE THREAD

**Issue by aaime** [xerial/sqlite-jdbc#314]
The build instructions do not mention docker among prerequisites:

https://github.com/xerial/sqlite-jdbc/blob/master/README_BUILD.md

Locally (Linux Mint) I had to install docker and then adding the local user to the docker group as mentioned [in this article](https://techoverflow.net/2017/03/01/solving-docker-permission-denied-while-trying-to-connect-to-the-docker-daemon-socket/) to allow the build to proceed.

**Comment by xerial** [comment]
This document is now obsoleted because we are now using docker for cross-building. Thanks for reporting. We should fix these docs.

**Comment by vernyis** [comment]
@xerial any chance on an update on this? I have some sqlite source files (.c, .h, and the .dll's) for supporting encryption, but I'm a bit lost on the build process here. I'm trying to change the Makefile to encourage using my sqlite over the ones that are curl'd, but I'm not having much luck.
