### ISSUE TITLE
SHARED_CACHE is not honoured

### ISSUE THREAD

**Issue by shevek** [xerial/sqlite-jdbc#318]
https://github.com/xerial/sqlite-jdbc/blob/21d68009e6b218a8902399a9bbd33f362c78537d/src/main/java/org/sqlite/SQLiteConfig.java#L81

That's a dead assignment. It ought to setOpenMode(SHAREDCACHE).

**Comment by shevek** [comment]
Dead in master too:
https://github.com/xerial/sqlite-jdbc/blob/master/src/main/java/org/sqlite/SQLiteConfig.java#L72

**Comment by snago** [comment]
Looks like this was fixed in 926e281c03c508d982193d09da6ea2824d5f7e81.

**Comment by gotson** [comment]
Closing as this seems resolved. Comment if necessary.
