### ISSUE TITLE
Support Android ARM 64 (arm64-v8a)

### ISSUE THREAD

**Issue by fabianbergmark** [xerial/sqlite-jdbc#320]
Would it be possible to include a libsqlitejdbc.so for arm64-v8a? If I use the aarch64 I get dlopen failed: library "libc.so.6".

Also, right now I copy the .so files to src/main/jniLibs/CPU_ABI. Is this necessary?

**Comment by xerial** [comment]
@fabianbergmark It seems this logic for detecting the architecture type needs to support arm64-v8a https://github.com/xerial/sqlite-jdbc/blob/master/src/main/java/org/sqlite/util/OSInfo.java#L203

Current implementation always choose a binary built for a specific architecture commonly used in Android.

**Comment by jjcoffman** [comment]
Is there any update on when this issue might get addressed?

**Comment by gotson** [comment]
Should be addressed by #662 and available in the next release.

**Comment by gotson** [comment]
This is available in the latest snapshot, please give it a try.

**Comment by gotson** [comment]
Released as part of `3.39.2.0`
