### ISSUE TITLE
Cancel/stop backup or restore in progress

### ISSUE THREAD

**Issue by SalehHaddawi** [xerial/sqlite-jdbc#324]
I am using backup and restore using the commands : `backup to file_path` and `restore from file_path` it works great but i wonder if there a way to stop or cancel the process .
I tried `statment.cancel()` and colsing the connection but that didn't work.
Is there a way to stop the process?
by the way i'm not very advanced user :)
Thanks.

**Comment by gotson** [comment]
Closing as this is very old, better suited for StackOverflow.
