### ISSUE TITLE
Get exception out of memory 

### ISSUE THREAD

**Issue by avnerbarr** [xerial/sqlite-jdbc#334]
Getting this error after thousands of rows are added to db.

`got exception java.sql.SQLException: [SQLITE_NOMEM]  A malloc() failed (out of memory)`

I see that the database is populating on the disk (the file is growing to a few GB in some cases)

After some time I will get the exception (not right away)

my code is like this

```
val connection = DriverManager.getConnection(s"jdbc:sqlite:/tmp/myDB.db")

def writeBatch(rows: Seq[(String,String)]) = {
      connection.setAutoCommit(false)
      rows.foreach {
        r => {
          val s: PreparedStatement = connection.prepareStatement("INSERT INTO products VALUES (?,?);")
          s.setString(1, r._1)
          s.setString(2, r._2)
          s.addBatch()
        }
      }
      s.executeBatch()
      connection.commit()
  }```

Batch size is commited with between ~50-100 rows

**Comment by gotson** [comment]
Looks like your system was running out of memory. Closing this as old, please comment if necessary.
