### ISSUE TITLE
java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open_utf8([BI)V

### ISSUE THREAD

**Issue by aka-sabha** [xerial/sqlite-jdbc#337]
I try to open an AES128 encrypted Sqlite DB file by providing SEE dlls to the driver.

> -Dorg.sqlite.lib.path="C:\extensions\see\bld"
> -Dorg.sqlite.lib.name="see.dll"

In my source I call as follows

`Connection conn = DriverManager.getConnection("jdbc:sqlite:" + dbAbsoluteFilePath + "?hexkey_mode=sse","","secret");`

The following error occurs when trying to create a jdbc connection

```
java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open_utf8([BI)V
	org.sqlite.core.NativeDB._open_utf8(Native Method)
	org.sqlite.core.NativeDB._open(NativeDB.java:71)
	org.sqlite.core.DB.open(DB.java:174)
	org.sqlite.core.CoreConnection.open(CoreConnection.java:224)
	org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
	org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:25)
	org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:24)
	org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
	org.sqlite.JDBC.createConnection(JDBC.java:114)
	org.sqlite.JDBC.connect(JDBC.java:88)
	java.sql.DriverManager.getConnection(DriverManager.java:664)
	java.sql.DriverManager.getConnection(DriverManager.java:247)
```

**Environment:**

> OS: Win7-64bit
> Java: 1.8.0

**Comment by lparolari** [comment]
Hello,

i'm having the same problem opening a database on android with jdbc connection.
Have you found the solution?

**Comment by 805447391** [comment]
@lparolari  Seem to your, and how we solve this problem?

**Comment by lparolari** [comment]
@805447391 I solved this changing my approach to the solution.
Now my library is taking in input a `ConnectionSource` object, which allows the client to build whatever connection he needs, modulo the implementation of `ConnectionSource` interface.

With this approach I've been able to write something like that in my android app:
```java
DbHelper dbh = new DbHelper(this,"mydb.db",null,1);
Db.init(new AndroidConnectionSource(dbh), /* other params */ );
```
where `Db` is my singularity class which interacts with the database, and `DbHelper` is a class extending `SQLiteOpenHelper` doing nothing special:
```java
public class DbHelper extends SQLiteOpenHelper { 
    public DbHelper(Context context, String name, SQLiteDatabase.CursorFactory factory, int version) {
        super(context, name, factory, version);
    }

    @Override
    public void onCreate(SQLiteDatabase _db) { 
        // your create...
    }

    @Override
    public void onUpgrade(SQLiteDatabase _db, int oldVersion, int newVersion) {
        // your upgrade...
    }

    @Override
    public void onConfigure(SQLiteDatabase db) {
        super.onConfigure(db);
        // ...
    }

    @Override
    public void onOpen(SQLiteDatabase db) {
        super.onOpen(db);
        // ...
    }
}
```

**Comment by gotson** [comment]
Closing this as it's very old. Comment if necessary.
