### ISSUE TITLE
SQLite JDBC internal error: rs.isOpen() on exec error

### ISSUE THREAD

**Issue by darouwan** [xerial/sqlite-jdbc#346]
It is thrown on

at org.sqlite.core.CoreStatement.exec(CpreStatement.java:70)
at org.sqlite.jdbc3.JDBC#Statement.executeQuery(JDBC3Statement.java:83)

when I execute a SQL query. 

The version I am using is 3.20.1

It seems a internal error, and I can do nothing on it. So how to fix it? or how to avoid it?

Thanks!

**Comment by witmoca** [comment]
Would you be so kind as to give more information? OS, system, statement you're trying to execute?
I'm assuming you're getting the "SQLite JDBC internal error: rs.isOpen() on exec." exception?

**Comment by darouwan** [comment]
OS: centos 6.7 64bit
sql: just a simple query like "SELECT a, b from table group by b"

It occurs sometimes, about once per day.

May it be caused by multi-thread safe problem?  As I set the Statement variable as static.
I have change it to a non-static value but it need time to be observed.

**Comment by witmoca** [comment]
If you execute that statement simultaneously somewhere, yes it is. By the definition of java.sql.statement:

> only one ResultSet object per Statement object can be open at the same time

**Comment by gotson** [comment]
Seems the question was answered, i'm closing this. Comment if necessary.
