### ISSUE TITLE
Issue in Concurrent read operation

### ISSUE THREAD

**Issue by JSampathkumar** [xerial/sqlite-jdbc#347]
In my application, I have used Hibernate-Sqlite configuration to access the data from database file. 

Library used : `compile group: 'org.xerial', name: 'sqlite-jdbc', version: '3.23.1'`

It seems, I am seeing CPU utilization is increased about 80% when the 20 to 30 concurrent threads sending to application.

I have analyzed and found the method **"org.sqlite.core.NativeDB.step(Native Method)"** is taking more CPU and also following logs noticed in thread dump.

```
	at org.sqlite.core.NativeDB.step(Native Method)
	- locked <3e9eaaab> (a org.sqlite.core.NativeDB)
	at org.sqlite.core.DB.execute(DB.java:811)
	- locked <3e9eaaab> (a org.sqlite.core.NativeDB)
```
Please let me know why the lock is happened and how to fix this issue.

**Comment by henryoung** [comment]
> In my application, I have used Hibernate-Sqlite configuration to access the data from database file.
> 
> Library used : `compile group: 'org.xerial', name: 'sqlite-jdbc', version: '3.23.1'`
> 
> It seems, I am seeing CPU utilization is increased about 80% when the 20 to 30 concurrent threads sending to application.
> 
> I have analyzed and found the method **"org.sqlite.core.NativeDB.step(Native Method)"** is taking more CPU and also following logs noticed in thread dump.
> 
> ```
> 	at org.sqlite.core.NativeDB.step(Native Method)
> 	- locked <3e9eaaab> (a org.sqlite.core.NativeDB)
> 	at org.sqlite.core.DB.execute(DB.java:811)
> 	- locked <3e9eaaab> (a org.sqlite.core.NativeDB)
> ```
> Please let me know why the lock is happened and how to fix this issue.

Hi JSampathkumar,
I also meet this issue :(
How do you fix it finally?
Thanks.

**Comment by gotson** [comment]
Is this still happening on the latest version?
