### ISSUE TITLE
sqlite-jdbc-3.8.10.1

### ISSUE THREAD

**Issue by xerial** [xerial/sqlite-jdbc#35]
https://www.sqlite.org/releaselog/3_8_10_1.html

**Comment by xerial** [comment]
@gitblit 
FYI, we need to use an older version of glibc to support various type of Linux. 
I usually use CentOS 5 (in VM) with glibc 2.5. The version of glibc can be checked with `ldd --version` command.

**Comment by gitblit** [comment]
Ah.  Ok.  I built with Ubuntu 14.04 LTS.

**Comment by xerial** [comment]
done.
