### ISSUE TITLE
please release an update to bitbucket

### ISSUE THREAD

**Issue by ravermeister** [xerial/sqlite-jdbc#36]
Hi, could you put the new release:
News
    2015 May 11th: sqlite-jdbc-3.8.10.1 release

to the bitbucket download section?
or do I have to compile it from source, because I don't use maven in my Project.

**Comment by gitblit** [comment]
You could just grab it from [here](http://search.maven.org/#artifactdetails|org.xerial|sqlite-jdbc|3.8.10.1|jar).

**Comment by xerial** [comment]
done. https://bitbucket.org/xerial/sqlite-jdbc/downloads
