### ISSUE TITLE
Increasing SQLite limits at runtime

### ISSUE THREAD

**Issue by meletis** [xerial/sqlite-jdbc#387]
Hi everybody, 

I browsed the source code searching for ways to override the default limits. I was mostly interested in the [SQLITE_MAX_COLUMN](https://www.sqlite.org/limits.html) but I couldn't find how to do it in the connection string or in the SQLiteConfig class. Is there really a way to set those limits at runtime?

**Comment by tildedave** [comment]
This is a compile-time parameter so it can't be modified a runtime  I believe you could increase this in your own installation via running `SQLITE_FLAGS="-DSQLITE_MAX_COLUMN=<whatever you want> make".`

**Comment by meletis** [comment]
thanks! I guess that will work!
