### ISSUE TITLE
Different "field type" under different environments for BLOBs.

### ISSUE THREAD

**Issue by dreadolph** [xerial/sqlite-jdbc#388]
Hello I have an issue with library on BLOB field.

1 file database, 1 SELECT statement for return BLOB field.
case 1) Simple Hello world program. 
```java
import java.sql.*;

public class Main {

    public static void main(String[] args) {
        String url = "jdbc:sqlite:/macOSPath";

        try (Connection conn = DriverManager.getConnection(url)) {

                System.out.println("Connection to SQLite has been established.");
                String query = "SELECT ...";


                try (Statement stmt = conn.createStatement())
                {
                    ResultSet rs = stmt.executeQuery(query);

                    ResultSetMetaData metaData = rs.getMetaData();

                    int a1 = metaData.getColumnType(1);
                    int a2 = metaData.getColumnType(2);
                    int a3 = metaData.getColumnType(3);

                    System.out.println(metaData);
                } catch (SQLException e ) {
                        System.out.println(e.getMessage());
                }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
}
```

This return right types, a1,a2,a3 7/2004/4

case 2) All the same, same version of library, but I use Apache NiFi, again Simple configuration, like SELECT and Log. The **same** SELECT statement, same file.

I got and exception inside Apache NiFi code due to library returns NULL for BLOB field.

After some research please take a look on link to code sqlite-jdbc-3.25.2-sources.jar!/org/sqlite/jdbc3/JDBC3ResultSet.java:740
valueType equals 5 for case 1
valueType equals 4 for case 2.

**Comment by dreadolph** [comment]
Additional research,

SQLite JDBC unable to resolve column type (casted to text) if statement returns 0 rows otherwise everything is good.

**Comment by dreadolph** [comment]
After additional research, problem is SQLlite native code, I sent follow example to public email, let wait for response.

`
import java.sql.*;

public class Main {

    public static void main(String[] args) {
        String url = "jdbc:sqlite:<macOS path to file>";

        try (Connection conn = DriverManager.getConnection(url)) {

                System.out.println("Connection to SQLite has been established.");
                String query1 = "SELECT\n" +
                               "      t.GasStats10s_Value as val,\n" +
                               "      t.GasStats10s_Source as source,\n" +
                               "      t.TimeStamp\n" +
                               "FROM GasStats10s t\n" +
                               "WHERE t.TimeStamp >= 0\n" +
                               "ORDER BY t.TimeStamp ASC\n" +
                               "LIMIT 50;";

                String query2 = "SELECT\n" +
                            "      t.GasStats10s_Value as val,\n" +
                            "      t.GasStats10s_Source as source,\n" +
                            "      t.TimeStamp\n" +
                            "FROM GasStats10s t\n" +
                            "WHERE t.TimeStamp >= 15446222410350000\n" +
                            "ORDER BY t.TimeStamp ASC\n" +
                            "LIMIT 50;";

                try (Statement stmt = conn.createStatement())
                {
                    ResultSet rs1 = stmt.executeQuery(query1);

                    ResultSetMetaData metaData1 = rs1.getMetaData();
                    System.out.println("Query 1");

                    System.out.println("Column 1 Type:" + metaData1.getColumnType(1));
                    System.out.println("Column 2 Type:" + metaData1.getColumnType(2));
                    System.out.println("Column 3 Type:" + metaData1.getColumnType(3));

                    ResultSet rs2 = stmt.executeQuery(query2);

                    ResultSetMetaData metaData2 = rs2.getMetaData();
                    System.out.println("Query 2");

                    System.out.println("Column 1 Type:" + metaData2.getColumnType(1));
                    System.out.println("Column 2 Type:" + metaData2.getColumnType(2));
                    System.out.println("Column 3 Type:" + metaData2.getColumnType(3));
                } catch (SQLException e ) {
                        System.out.println(e.getMessage());
                }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
}
`

Results 

`
Connection to SQLite has been established.
Query 1 (50 records)
Column 1 Type:7
Column 2 Type:2004
Column 3 Type:4
Query 2 (0 records)
Column 1 Type:7
Column 2 Type:0
Column 3 Type:4
`

**Comment by gotson** [comment]
Is this still happening on the latest version?
