### ISSUE TITLE
ResultSet.getX before ResultSet.next

### ISSUE THREAD

**Issue by darkyp** [xerial/sqlite-jdbc#398]
Hello everyone,

I'm not sure if this is much of an issue but I encountered it in a code review and seemed a bit out of spec to me, so I decided to report it.

The ResultSet interface docs states

"Initially the cursor is positioned before the first row. The next method moves the cursor to the next row"

However with sqlite-jdbc one can directly access column values from the first record (provided the ResultSet is not empty) without first calling next to actually move to the first record. I see the DB.execute needs to step, still I think it might be better to have a kind of checkRowPos in the getX methods with a row == 0 check, and throw the appropriate exception, e.g. "Before start of result set".
The above reference to the function name and the error are taken from the mysql connector.

Hence to summarise, having the following code:

ResultSet rs = db.createStatement().executeQuery("SELECT 1 AS id WHERE 1 = 0");
// rs.next();
rs.getInt("id");

I would expect to have an error thrown at the third line.

**Comment by gotson** [comment]
Is this still happening on the latest version?

**Comment by gotson** [comment]
> I would expect to have an error thrown at the third line.

There's nothing in the Javadoc that requires this:
> Throws:
[SQLException](https://docs.oracle.com/javase/8/docs/api/java/sql/SQLException.html) - if the columnIndex is not valid; if a database access error occurs or this method is called on a closed result set

**Comment by gotson** [comment]
Closing this as no feedback was received.
