### ISSUE TITLE
Invalid link for jdbc driver on http://www.liquibase.org/sqlite.html

### ISSUE THREAD

**Issue by ABD01451** [xerial/sqlite-jdbc#40]
http://www.liquibase.org/sqlite.html shows a link to jdbc driver : 
              http://www.zentus.com/sqlitejdbc/ 
That just shows a google developer's social links and doesn't return the driver:
Could you please provide a link that works?  
Please verify also that driver name would still be:
               org,sqlite.JDBC

**Comment by xerial** [comment]
This one is the original sqlite-jdbc driver, developed by David.
