### ISSUE TITLE
Update to 3.25.2 Black Duck Binary Analysis have vulnerabilities

### ISSUE THREAD

**Issue by tigershi** [xerial/sqlite-jdbc#402]
the org/sqlite/native/FreeBSD/x86_64/libsqlitejdbc.so file can't upgrade from 3.15.1 to 3.25.2
the org/sqlite/native/Linux/armv6/libsqlitejdbc.so file can't upgrade from 3.20.0 to 3.25.2

**Comment by tigershi** [comment]
[sqlite-jdbc-3252jar-2019-02-15-064101.pdf](https://github.com/xerial/sqlite-jdbc/files/2868078/sqlite-jdbc-3252jar-2019-02-15-064101.pdf)

**Comment by gotson** [comment]
Is this still happening on the latest version?
