### ISSUE TITLE
Wrong implementation of type affinity?

### ISSUE THREAD

**Issue by fireandfuel** [xerial/sqlite-jdbc#403]
I'm using sqlite with hibernate, using https://github.com/gwenn/sqlite-dialect as dialect. I stumbled across an exception generated by hibernate `org.hibernate.MappingException: No Dialect mapping for JDBC type: 0` when running a select query on a table. JDBC type 0 is defined by `java.sql.Types.NULL`.

I reported this [issue](https://github.com/gwenn/sqlite-dialect/issues/14) to the owner of the dialect, including a fix for this issue on the dialect (I found it in a bug report at a fork of the dialect) and they pointed out that it's an driver issue and rejected my fix:

> Don't fix the dialect, fix the [driver](https://github.com/xerial/sqlite-jdbc/blob/a170d6d31db864316b042004040e356590358355/src/main/java/org/sqlite/jdbc3/JDBC3ResultSet.java#L834).
> 
> https://docs.oracle.com/javase/6/docs/api/java/sql/ResultSetMetaData.html#getColumnType(int)
> 
> > Retrieves the designated column's SQL type.
> 
> Not the value type...
> 
> And https://sqlite.org/datatype3.html
> 
> > In order to maximize compatibility between SQLite and other database engines, and so that the example above will work on SQLite as it does on other SQL database engines, SQLite supports the concept of "type affinity" on columns. The type affinity of a column is the recommended type for data stored in that column.
> 
> 'NULL' is not listed among type affinities: 'TEXT', 'NUMERIC', 'INTEGER', 'REAL', 'BLOB'.

Source: https://github.com/gwenn/sqlite-dialect/issues/14#issuecomment-464126757

I currently applied the fix I found on the dialect, but I'm not happy to work this issue around.
Type affinity is great, but is the driver broken or the dialect?

**Comment by witmoca** [comment]
The driver does default to NULL instead of NUMERIC. This seems easily fixed.
