### ISSUE TITLE
org.sqlite.jdbc3.JDBC3ResultSet.getDouble()

### ISSUE THREAD

**Issue by jmiguelf** [xerial/sqlite-jdbc#407]
this should return NULL or Double.NaN, returning zero is just stupid, how can i see if a value is null if this allways return 0 ?

return 0; -> return Double.NaN;

**Comment by gwenn** [comment]
https://docs.oracle.com/javase/7/docs/api/java/sql/ResultSet.html#wasNull()

**Comment by jmiguelf** [comment]
That works in some cases, but I’m using jeasyorm... and without recompiling one of them the correct result can’t be obtained

**Comment by jmiguelf** [comment]
sqlite-jdbc is the problem, because it return data that isn't in the database... it return 0 with a field NULL... that is the problem, i've mension jeasyorm just because the not so great solution (wasNull()) dont do the job... it just tells that the last value was a null, but i dont know wich one is the last one read from the table

**Comment by gwenn** [comment]
As well as [pgjdbc](https://github.com/pgjdbc/pgjdbc/blob/fe7eda3d2e56d70b83294b7534d6386501599c37/pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java#L2336).
And I guess all jdbc drivers.
https://docs.oracle.com/javase/7/docs/api/java/sql/ResultSet.html#getDouble(int)
> if the value is SQL NULL, the value returned is 0

**Comment by witmoca** [comment]
Indeed, the standard requires a zero and not NULL be returned. All jdbc compliant drivers should adhere to the standard. This is definitely not a bug.

**Comment by jmiguelf** [comment]
Ok I didn’t read the standards, but with every database I’ve worked, at least the NaN is returned in case of a null.

**Comment by witmoca** [comment]
Considering this isn't an issue, unless there are further questions I suggest this issue be closed.
