### ISSUE TITLE
armv6 support outdated to SQLite version 3.21.0

### ISSUE THREAD

**Issue by Christian77777** [xerial/sqlite-jdbc#409]
I created a Java Program that utilizes the current version of sqlite-jdbc version 3.27.2
I read in the patch notes of the readme that it supports SQLite version 3.25.2, which is important for my needs because version 3.24.0 added UPSERT functionality.
The Database functions just as intended on my Windows x64 computer, but running the shaded Jar on my armv6 Raspberry Pi zero w, it crashes when it reaches an UPSERT statement.
I decided to run _SELECT sqlite_version();_ and sure enough, it returned 3.21.0  on the Pi.
Are the armv6 native libraries going to be updated past 3.24.0 any time soon?
Because I took at look at the files in _/src/main/resources/org/sqlite/native/Linux/_, and its as if every single Linux OS library was updated to 3.27.2 except for armv6, the one I am running.
#408 
To be fair, I also noticed in the README_BUILD.md something about compiling for the raspberry pi, are users supposed to compile on their own for raspberry pi? Reading some of the other issues and the readme, I got the feeling it would already be prepared in the jar. Otherwise, what is the right step to take if there is no issue here?

**Comment by md-5** [comment]
There's a comment in Makefile, seems dockcross isn't currently supported for the pi due to : https://github.com/dockcross/dockcross/issues/190

**Comment by Christian77777** [comment]
Ah shoot, of course someone already filed this issue, I knew I couldn't be the only one. I guess Ill be waiting then

**Comment by xerial** [comment]
@Christian77777 Yeah. Dockcross suddenly stopped working for armv6. This was around https://github.com/xerial/sqlite-jdbc/commit/a6e80cf646116852a42a89c4423c1cb60ad052ef

**Comment by xerial** [comment]
When I was owning raspberry Pi, I can build sqlite-jdbc using `make native` command. It will take a long time, so using an older version of dockcross docker image might be better. But I don't know how to use an older docker image of dockcross.

**Comment by md-5** [comment]
I don't own a raspberry pi at all, but I think it was more that raspbian upgraded a library where dockcross didn't, rather than any active change by dockcross.

**Comment by Christian77777** [comment]
I managed to execute "make native" properly on my pi, and got the resulting files. It turns out my exact pi architecture is armhf, not armv6. But anyway, it seems there is one last step to export the jar, as "make" doesn't seem to work. Looks like all the $(CC) variables dont resolve to anything, probably because "Linux-armhf" variables don't exist in the Makefile.common. Any suggestions for the "_CCFLAGS" variable, or should I just copy from armv6? The other 5 variables make sense to copy from Linux-armv6, but please correct me if I am wrong.
Otherwise, thanks for the clarification.

**Comment by Christian77777** [comment]
I managed to compile the native code on my pi, and finish compiling the jar on a different system. Ran into a space limit, requiring the second system. I guess this resolves the issue for me, and for anyone else looking for the Raspberry pi version
