### ISSUE TITLE
Compile With -Os by Default

### ISSUE THREAD

**Issue by md-5** [xerial/sqlite-jdbc#410]
As seen here: https://www.sqlite.org/footprint.html

There is virtually no performance difference between versions of SQLite compiled with a high level optimization, and those optimized for size. Accordingly there is the recommendation:

"the SQLite developers recommend compiling SQLite using GCC-7 with the -Os optimization setting."

This recommendation is also made in the README.md of the latest version of SQLite: `  $ CFLAGS="-Os" ./configure`

Given that this reduces binary size by circa 50%, and sqlite-jdbc packages a lot of different binary versions I feel like such a change is advantageous in dropping overall library footprint.

Interested to know other's thoughts.

Also would be a good opportunity to visit the outdated armv6 (https://github.com/xerial/sqlite-jdbc/issues/409) and freebsd binaries.

**Comment by md-5** [comment]
I rebuilt all the default binaries with this option and got a -1MB, or 15% reduction in jar size: https://github.com/xerial/sqlite-jdbc/compare/master...md-5:master

Would probably be closer to 20% or more if all the binaries were rebuilt.

**Comment by xerial** [comment]
Good to know that. The reduction with this change was 6011892 / 6733696 = 0.89 (11% reduction).

**Comment by xerial** [comment]
Applied in #412
