### ISSUE TITLE
Can I use SQLite specific statment?

### ISSUE THREAD

**Issue by ivanooi** [xerial/sqlite-jdbc#414]
Hi all,

Can I use SQLite specific statment?
example : 
full text search
insert or replace 

Thanks

**Comment by jeffque** [comment]
@ivanooi , indeed you can and should.

I use (wildly) `INSERT OR REPLACE` and tested `INSERT OR IGNORE`. For those DMLs, I use the `executeUpdate` method in an instance of `Statement` or `PreparedStatement`.

**Comment by gotson** [comment]
Seems the question was answered, i'm closing this. Comment if necessary.
