### ISSUE TITLE
JNI weak global reference in NativeDB.c might be GCed before use

### ISSUE THREAD

**Issue by penguinfirst** [xerial/sqlite-jdbc#419]
In Issue #267 the initialization of dbclass/fclass/aclass/pclass/phandleclass (NativeDB.c) was changed to JNI weak global reference and a JNI_OnUnload function was added to avoid memory leak. But according to the JNI specification about Weak Global Reference, the Java object refed by a weak global reference still might be GCed, so a weak global reference should be changed to a strong ref to ensure its validity before used.
I wonder if it is better to change weak global ref (dbclass ... phandleclass) to global ref before used and then delete global ref to avoid memory leak.

P.S. JNI Specification about Weak Global Reference 
 (https://docs.oracle.com/en/java/javase/12/docs/specs/jni/functions.html#weak-global-references)

"Unlike normal global references, a weak global reference allows the underlying Java object to be garbage collected."

"Since garbage collection may occur while native methods are running, objects referred to by weak global references can be freed at any time. While weak global references can be used where global references are used, it is generally inappropriate to do so, as they may become functionally equivalent to NULL without notice."

"To overcome this inherent limitation, it is recommended that a standard (strong) local or global reference to the same object be acquired using the JNI functions NewLocalRef or NewGlobalRef, and that this strong reference be used to access the intended object."

**Comment by trohwer** [comment]
No, I don't think there is an issue here: The (in the native code weakly) referenced object are all class object. The classloader will have a strong reference to them while a native call is in progress.
