### ISSUE TITLE
Problem with upsert

### ISSUE THREAD

**Issue by likeanowl** [xerial/sqlite-jdbc#420]
Hi!
Tried to execute an UPSERT query and got an exception (sqlite-jdbc version is 3.27.2.1):
```
org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (near "on": syntax error)
	at org.sqlite.core.DB.newSQLException(DB.java:909)
	at org.sqlite.core.DB.newSQLException(DB.java:921)
	at org.sqlite.core.DB.throwex(DB.java:886)
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:127)
	at org.sqlite.core.DB.prepare(DB.java:227)
	at org.sqlite.jdbc3.JDBC3Statement.execute(JDBC3Statement.java:60)

```

My UPSERT example is very simple:
```
insert into statsData
   select * from tempStatsData
   where true
   on conflict (uniqueConstraint) do update
   set changesCount = changesCount + tempStatsData.changesCount;
```

Execution is performed via standard statements, like this:
```
try (Statement statement = connectionOpt.get().createStatement()) {
       statement.execute(upsertStatDaily);
} catch (SQLException e) {
       e.printStackTrace();
}
```

So, can you please clarify, how should `upsert` queries be executed? 
Thanks!

**Comment by xerial** [comment]
It seems `where true` is invalid SQL syntax. How about `where 1=1` or removing this where clause?

**Comment by likeanowl** [comment]
Thanks for quick reply!
Pretty same with `where 1=1`, without `where` the exception is slight different:
```
org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (near "do": syntax error)
```
but I guess it's related to parsing problem discribed there (bottom): https://www.sqlite.org/lang_UPSERT.html

Also, I've found something strange: wanted to make sure that driver has right version, but `meta.getDriverVersion()` output is `3.21.0.1` and this may be an issue. But this is very strange, because in my build.gradle I have classPath dependency on latest sqlite-jdbc version: 
`compileClasspath group: 'org.xerial', name: 'sqlite-jdbc', version: '3.27.2.1'`

I'll double-check, may be it's overwritten by some of my other dependencies.

**Comment by likeanowl** [comment]
Sure, found it. It was overwritten by another dependency.
Sorry for bothering! :)
