### ISSUE TITLE
wrong masking of sqlite system tables

### ISSUE THREAD

**Issue by Orfanik** [xerial/sqlite-jdbc#427]
Hi, 

related to
org.sqlite.jdbc3.JDBC3DatabaseMetaData.getTables

there are a small problem of masking sqlite system table starts with "sqlite_".
Current masking is : LIKE 'sqlite_%'
But this prevent using user table starts with "sqlite" too!  Because : 
https://www.sqlite.org/lang_expr.html
"A percent symbol ("%") in the LIKE pattern matches any sequence of zero or more characters in the string. **An underscore ("_") in the LIKE pattern matches any single character in the string.**"

Suggestion from sqltile:
If the optional ESCAPE clause is present, then the expression following the ESCAPE keyword must evaluate to a string consisting of a single character. This character may be used in the LIKE pattern to include literal percent or underscore characters. The escape character followed by a percent symbol (%), underscore (_), or a second instance of the escape character itself matches a literal percent symbol, underscore, or a single escape character, respectively. 

The suggested new mask: LIKE 'sqlite\\_%' ESCAPE '\\'

**Comment by gotson** [comment]
Is this still happening on the latest version?

**Comment by Orfanik** [comment]
Hi, it is ok now, thx
