### ISSUE TITLE
Release for SQLite 3.28.0?

### ISSUE THREAD

**Issue by soc** [xerial/sqlite-jdbc#430]
Hey @xerial,

what would be necessary to cut a new release for SQLite 3.28?

Thanks,

Simon

**Comment by SHAGO7932** [comment]
Hello World

**Comment by kyenos** [comment]
Thanks! Looking forward to the merge.

**Comment by xerial** [comment]
Released sqlite-jdbc 3.28.0

**Comment by soc** [comment]
Thank you!
