### ISSUE TITLE
File descriptor leaked when opening an illegal file as sqlite database

### ISSUE THREAD

**Issue by hofmandl1** [xerial/sqlite-jdbc#431]
Reproducer:
  * open a random .exe file as db (probably works with other non-sqlite files as well) using SQliteConfig.createConnection("jdbc:sqlite:path-to-file.exe")
  * catch the resulting Exception (Sqlite ErrorCode is NotADb) and keep the java process running

Result:
  * with a process inspector or similar you should be able to see, that the java process still has the db-file open
  * on windows it will not be possible to delete the file

I have tracked the problem down to the SQLiteConnection-constructor with code similar to this:

    public SQLiteConnection(String url, String fileName, Properties prop) throws SQLException {
        this.db = open(url, fileName, prop);
        SQLiteConfig config = db.getConfig();
        this.connectionConfig = db.getConfig().newConnectionConfig();
        config.apply(this);
    }

the file is opened in the open() call and the exception is thrown in config.apply(). Also there seems to be no GC finalizer that cleans up when the DB-instance is collected.

**Comment by Andy-2639** [comment]
A possible fix could be:
```java
    public SQLiteConnection(String url, String fileName, Properties prop) throws SQLException {
        try {
            this.db = open(url, fileName, prop);
            SQLiteConfig config = db.getConfig();
            this.connectionConfig = db.getConfig().newConnectionConfig();
            config.apply(this);
        } catch (Throwable t) {
            try {
                if (this.db != null) {
                    db.close();
                }
            } catch (Exception e) {
                t.addSuppressed(e);
            }
            throw t;
        }
    }
```

**Comment by SHAGO7932** [comment]
Hello World
