### ISSUE TITLE
ppc64 openjdk execstack error

### ISSUE THREAD

**Issue by 0x08** [xerial/sqlite-jdbc#436]
Hello,

When running version 3.28.0 on ppc64 I am getting the following error:

```
OpenJDK 64-Bit Server VM warning: You have loaded library /tmp/sqlite-3.28.0-85c825b5-524d-4d56-97a2-440071c1f923-libsqlitejdbc.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
```

I have tried playing around with the execstack permissions of the ppc64 .so file included in the jar file but to no avail. As far as I understand ppc64 should be supported - it this an issue of 64-bit vs 32-bit? I am running on a 64-bit VM (OpenJDK).

Thanks,

Ben

**Comment by gotson** [comment]
Is this still happening on the latest version?

**Comment by gotson** [comment]
Closing this as no feedback was received.
