### ISSUE TITLE
Major memory leak

### ISSUE THREAD

**Issue by aliakhtar** [xerial/sqlite-jdbc#437]
Details: https://stackoverflow.com/questions/56883748/memory-leak-with-jdbc-sqlite

**Comment by guangwei-qiao** [comment]
I also found physical memory leak issue after close sqlite connection, how to insure release physical memory?

**Comment by aliakhtar** [comment]
@guangwei-qiao I moved from Sqlite to CQEngine and it saved me from a lot of headaches & issues & improved performance a lot. I'd suggest doing the same if you have a primarily read-based workflow.

**Comment by guangwei-qiao** [comment]
> @guangwei-qiao I moved from Sqlite to CQEngine and it saved me from a lot of headaches & issues & improved performance a lot. I'd suggest doing the same if you have a primarily read-based workflow.

Excellent suggestion,! however, my scenario is to save memory, CQEngine is not very suitable!

**Comment by aliakhtar** [comment]
@guangwei-qiao  For saving memory I'd suggest trying Eclipse J9 JDK if you're using Oracle / Hotspot: https://adoptopenjdk.net/

I think CQEngine can also be used with filed based / persistent indexes in which case it won't load the data up front in memory.

**Comment by guangwei-qiao** [comment]
> @guangwei-qiao For saving memory I'd suggest trying Eclipse J9 JDK if you're using Oracle / Hotspot: https://adoptopenjdk.net/
> 
> I think CQEngine can also be used with filed based / persistent indexes in which case it won't load the data up front in memory.

thanks a lot, will try it.

**Comment by A248** [comment]
#528 may have fixed your issue

**Comment by gotson** [comment]
Is this still happening on the latest version?

**Comment by MarkJeronimus** [comment]
The new version seems to lower the memory leak but not eliminate it
