### ISSUE TITLE
Please consider using WeakHashMap for stmts Map in DB.class

### ISSUE THREAD

**Issue by davidhedley** [xerial/sqlite-jdbc#438]
Could you please consider changing the `stmts` HashMap in DB to a WeakHashMap?

We've just spend days tracking down a memory leak in our application which was due to an unclosed PreparedStatement and the only reason it wasn't being GC'd was because of the reference from this HashMap. (It's a long running application which rarely, if ever, closes its open sqlite connections). It would appear that live PreparedStatments consume a considerable amount of off-heap memory which is almost impossible to track in a running Java process and so although the Java heap was a managable size, the Java process itself grew unbounded until the computer ran out of memory.

**Comment by gotson** [comment]
Is this still happening on the latest version?

**Comment by davidhedley** [comment]
I don't know to be honest. We went through our code and ensured that all PreparedStatements were being closed and haven't had a recurrence.
Looking at the implementation in 3.36.0.3 it seem `stmts` still a HashMap so I guess the issue remains.

**Comment by gotson** [comment]
> I don't know to be honest. We went through our code and ensured that all PreparedStatements were being closed and haven't had a recurrence.

I think that was what needed to be done, those resources need to be closed.

Will close the issue.
