### ISSUE TITLE
Cannot drop temporary table while an unrelated result set is open

### ISSUE THREAD

**Issue by jubax** [xerial/sqlite-jdbc#439]
It is not possible to drop an unrelated temporary table while any result set is open. See the test case below.

Note that while the test case might look a bit arbitrary this is a simplified version of what could happen when multiple result sets are open at the same time. The code below runs fine in H2 and MS SQL Server.

I don't know if this is an error in SQLite or in the JDBC driver.

```
@Test
public void testSqliteDropTmpTable() throws Exception {
    try (Connection connection = DriverManager.getConnection("jdbc:sqlite::memory:")) {
        connection.setAutoCommit(false);

        // create table a
        try (PreparedStatement statement = connection.prepareStatement("CREATE TABLE a (att1 INT PRIMARY KEY);")) {
            statement.execute();
        }
        try (PreparedStatement statement = connection.prepareStatement("INSERT INTO a VALUES(42);")) {
            statement.execute();
        }

        // create table b
        try (PreparedStatement createTableStatement = connection.prepareStatement("CREATE TEMP TABLE b (att1 INT);")) {
            createTableStatement.execute();
        }

        try (PreparedStatement statement = connection.prepareStatement("SELECT * FROM a")) {
            try (ResultSet rs = statement.executeQuery()) {
                if (rs.next()) {
                    // When executing the next statement an exception is thrown. Is it really the case that it is not possible to drop
                    // unrelated tables while a ResultSet is open?
                    /*
                    org.sqlite.SQLiteException: [SQLITE_LOCKED]  A table in the database is locked (database table is locked)
                    at org.sqlite.core.DB.newSQLException(DB.java:941)
                    at org.sqlite.core.DB.newSQLException(DB.java:953)
                    at org.sqlite.core.DB.execute(DB.java:854)
                    at org.sqlite.jdbc3.JDBC3PreparedStatement.execute(JDBC3PreparedStatement.java:56)
                    */
                    try (PreparedStatement dropTableStatement = connection.prepareStatement("DROP TABLE b")) {
                        dropTableStatement.execute();
                    }
                }
            }
        }
    }
}
```

**Comment by witmoca** [comment]
I could not find any reference to this in the current documentation (https://www.sqlite.org/docs.html).

After some googling I did stumble upon an article on the cvstrac wiki. 
`https://www2.sqlite.org/cvstrac/wiki?p=DatabaseIsLocked` 
This information is old, so it might not be valid anymore. It does seem to describe the situation rather well however. In the absense of other sources, I think it's reasonable to consider this to still be true. 


> [...] Here are other reasons for getting an SQLITE_LOCKED error:
    Trying to CREATE or DROP a table or index while a SELECT statement is still pending. 
    [...] As of check-in [3902] (2007-05-02 after version 3.3.17) this is now allowed for CREATE statement. 

So summarized: You are not allowed to drop any tables while a select statement is still pending. For the jdbc that means that the ResultSet has to be closed first. 

This used to be the rule for other DDL statments as well, but CREATE has been allowed since 2007

**Comment by gotson** [comment]
Seems the question was answered, i'm closing this. Comment if necessary.

**Comment by jubax** [comment]
I adapted my code a long time ago, so this is not pressing for me. But it is still a bug which only exists in SQLite and no other database. It would be cool if this would be fixed.
