### ISSUE TITLE
Segfault after update of native SQLite to 3.29.0 on Mac (Homebrew)

### ISSUE THREAD

**Issue by stranljip** [xerial/sqlite-jdbc#442]
SQLite 3.29.0 has been released on July, 10th. Is there already a plan to update to that version?

**Comment by stranljip** [comment]
... not a place - of course I meant a *plan*

**Comment by witmoca** [comment]
SQlite-jdbc usually gets updated when the amount of pull requests warrants it. 
It does not update for every SQLite release. 
The short answer is `It gets updated when it gets updated`.

If you look at the release history, you'll get a good idea of the frequency of updates.

> **Note for this issue: New recommended compile time option in 3.29.0, see [sqlite changelog](https://www.sqlite.org/changes.html)**

**Comment by stranljip** [comment]
OK - I was asking, because of a Mac issue. We are using Spatialite/SQLite and since the Home-brew version of SQLite updated to 3.29.0 we get the following Segfault:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000163556396, pid=2316, tid=79879
#
# JRE version: OpenJDK Runtime Environment (11.0.3+7) (build 11.0.3+7)
# Java VM: OpenJDK 64-Bit Server VM (11.0.3+7, mixed mode, tiered, compressed oops, g1 gc, bsd-amd64)
# Problematic frame:
# C  [sqlite-3.28.0-692f8140-47bd-43df-ba90-0eeb070155a8-libsqlitejdbc.jnilib+0xa396]  Java_org_sqlite_core_NativeDB_clear_1progress_1handler+0x6d1c
```
The error can be omitted by rolling back sqlite to 3.28.0 (and pinning it there ...)

**Comment by gotson** [comment]
Is this still happening on the latest version?

**Comment by gotson** [comment]
Closing this as no feedback was received.

**Comment by kurtraschke** [comment]
I can reproduce with v3.39.2: [hs_err_pid45685.log](https://github.com/xerial/sqlite-jdbc/files/10407820/hs_err_pid45685.log)

**Comment by gotson** [comment]
> I can reproduce with v3.39.2: [hs_err_pid45685.log](https://github.com/xerial/sqlite-jdbc/files/10407820/hs_err_pid45685.log)

since you are not OP, and the original issue was asking about update, could you create a new issue and provide all necessary information for troubleshooting in the issue template?
