### ISSUE TITLE
UnsatisfiedLinkError during Bamboo build of Android project with Room

### ISSUE THREAD

**Issue by DavidMihola** [xerial/sqlite-jdbc#444]
I am sorry for having to raise this issue again but none of the solutions offered in other issues are working for me.
We are currently switching our Android from Realm to AndroidX Room. During the annotation processing step our builds are failing with the usual stacktrace:
```

13-Aug-2019 10:54:48 | e: [kapt] An exception occurred: java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open_utf8([BI)V
-- | --
13-Aug-2019 10:54:48 | at org.sqlite.core.NativeDB._open_utf8(Native Method)
13-Aug-2019 10:54:48 | at org.sqlite.core.NativeDB._open(NativeDB.java:78)
13-Aug-2019 10:54:48 | at org.sqlite.core.DB.open(DB.java:195)
13-Aug-2019 10:54:48 | at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:243)
13-Aug-2019 10:54:48 | at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:61)
13-Aug-2019 10:54:48 | at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
13-Aug-2019 10:54:48 | at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:21)
13-Aug-2019 10:54:48 | at org.sqlite.JDBC.createConnection(JDBC.java:116)
13-Aug-2019 10:54:48 | at androidx.room.verifier.DatabaseVerifier$Companion.create(DatabaseVerifier.kt:83)
13-Aug-2019 10:54:48 | at androidx.room.processor.DatabaseProcessor.doProcess(DatabaseProcessor.kt:81)
13-Aug-2019 10:54:48 | at androidx.room.processor.DatabaseProcessor.process(DatabaseProcessor.kt:57)
13-Aug-2019 10:54:48 | at androidx.room.RoomProcessor$DatabaseProcessingStep.process(RoomProcessor.kt:60)
13-Aug-2019 10:54:48 | at com.google.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:330)
13-Aug-2019 10:54:48 | at com.google.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:181)
13-Aug-2019 10:54:48 | at org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.process(annotationProcessing.kt:99)
```
This only happens when building on our company's Bamboo CI servers. On these, for security reasons, the `tmp` partition is mounted with the `noexec` flag and the admins are not open to removing this flag.

As a workaround, I tried creating a new `tmp` folder within the build's working directory and pointing `java.io.tmpdir` to that directory.

It seems that the folder is created correctly:
```

13-Aug-2019 10:54:08 | + mkdir /appl/bamboo/bamboo-agent-home-4/xml-data/build-dir/MP-AN6-JOB1/tmp
-- | --
13-Aug-2019 10:54:08 | + chmod a+x /appl/bamboo/bamboo-agent-home-4/xml-data/build-dir/MP-AN6-JOB1/tmp
13-Aug-2019 10:54:08 | + ls -lah /appl/bamboo/bamboo-agent-home-4/xml-data/build-dir/MP-AN6-JOB1/tmp
13-Aug-2019 10:54:08 | total 8.0K
13-Aug-2019 10:54:08 | drwxr-xr-x.  2 bamboo bamboo 4.0K Aug 13 10:54 .
13-Aug-2019 10:54:08 | drwxr-xr-x. 30 bamboo bamboo 4.0K Aug 13 10:54 ..
```
and that the environment variable is also set up correctly:
```
GRADLE_OPTS=-Djava.io.tmpdir=/appl/bamboo/bamboo-agent-home-4/xml-data/build-dir/MP-AN6-JOB1/tmp
```
Also, some files are created in that directory - this is the output of another script running after the failing Gradle build:
```
13-Aug-2019 10:54:49 | + ls -lah /appl/bamboo/bamboo-agent-home-4/xml-data/build-dir/MP-AN6-JOB1/tmp
-- | --
13-Aug-2019 10:54:49 | total 8.0K
13-Aug-2019 10:54:49 | drwxr-xr-x.  2 bamboo bamboo 4.0K Aug 13 10:54 .
13-Aug-2019 10:54:49 | drwxr-xr-x. 32 bamboo bamboo 4.0K Aug 13 10:54 ..
13-Aug-2019 10:54:49 | -rw-r--r--.  1 bamboo bamboo    0 Aug 13 10:54 kotlin-compiler-in-61-5400239858562433123.alive
```

Am I trying something obviously wrong here? Should I instead file an issue for AndroidX Room?

Thank you very much for any advice!

**Comment by tildedave** [comment]
Haven't tested this myself, but it looks like you might be able use the system property `org.sqlite.tmpdir` to control where the native binary gets placed (the cause of your UnsatisfiedLinkError is that it can't load the native library at boot time): https://github.com/xerial/sqlite-jdbc/blob/0c47e5d7ef62dec692523cbde138b9054c9cee91/src/main/java/org/sqlite/SQLiteJDBCLoader.java#L69

**Comment by DavidMihola** [comment]
@tildedave: Thank you very much for your reply and sorry for taking so long to get back to you!

Unfortunately, that wasn't enough - since the error was occurring during the KAPT (Kotlin annotation processing) step I had to also pass the property to the Kotlin daemon by adding this to my Gradle command:
> -Dkotlin.daemon.jvm.options="-Djava.io.tmpdir=/appl/bamboo/bamboo-agent-home-5/xml-data/build-dir/MP-AN6-JOB1/tmp"

Source: https://issuetracker.google.com/issues/111631291#comment3

Unfortunately, my _tests_ are still running into the same exception though...
