### ISSUE TITLE
JDBC3DatabaseMetaData.getColumns seems to ignore schema when issuing "PRAGMA table_info" command

### ISSUE THREAD

**Issue by AshwinJay** [xerial/sqlite-jdbc#448]
It looks like the `table_info` command that is issued in the `getColumns` call is ignoring the Schema name.

It should've been `PRAGMA schema.table_info(table-name)` instead of `PRAGMA table_info(table-name);`

**Ref:** 
- https://github.com/xerial/sqlite-jdbc/blob/master/src/main/java/org/sqlite/jdbc3/JDBC3DatabaseMetaData.java#L1239
- https://www.sqlite.org/pragma.html#pragma_table_info

**Comment by gotson** [comment]
Is this still happening on the latest version?

**Comment by gotson** [comment]
Do you have any issue stemming from that, and if yes could you provide some details ?

**Comment by gotson** [comment]
Closing this as no feedback was received.
