### ISSUE TITLE
Suggest that errorLogCallback supported

### ISSUE THREAD

**Issue by forchid** [xerial/sqlite-jdbc#453]
SQLite 3 supports [**The Error And Warning Log**](https://www.sqlite.org/errlog.html), but not found in sqlite-jdbc.

**Comment by patrickjuchli** [comment]
A year later, I'd like to bump this up. This would be very useful for long-running applications.

**Comment by rechvs** [comment]
I’d love to see this as well.
In case some pointers (no pun intended) would help in moving this forward: [this](https://github.com/gwenn/sqlite-jna/blob/master/src/main/java/org/sqlite/SQLite.java) seems to be one way of doing it.

**Comment by gotson** [comment]
How would that be made available in the driver though ? Would this be through the JDBC warnings (#483) ?

**Comment by gotson** [comment]
Closing this as no feedback was received.
