### ISSUE TITLE
Foreign Keys with eclipselink

### ISSUE THREAD

**Issue by Slav4ik** [xerial/sqlite-jdbc#46]
I'm trying to create a database with eclipselink and java persistence.
The framework creates some foreign keys for table joining but the SQLite will not accept it.
I guess SQLite doesn't support  the ALTER TABLE ADD CONSTRAINT instruction.

This is the error:
[EL Warning]: 2015-08-17 15:22:24.052--ServerSession(1249457275)--Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (near "CONSTRAINT": syntax error)
Error Code: 1
Call: ALTER TABLE MWE ADD CONSTRAINT FK_MWE_FORMERELEMENT_ID FOREIGN KEY (FORMERELEMENT_ID) REFERENCES MWE (ID)
Query: DataModifyQuery(sql="ALTER TABLE MWE ADD CONSTRAINT FK_MWE_FORMERELEMENT_ID FOREIGN KEY (FORMERELEMENT_ID) REFERENCES MWE (ID)")

**Comment by gitblit** [comment]
Sadly SQLite does not support ALTER at all.

-J

**Comment by gitblit** [comment]
Hopefully someday SQLite will support ALTER.  Until then you will have to perform some variant of the following...

1. Create a temp table
2. Copy content from current table to temp table
3. Drop current table
4. Rename temp table
