### ISSUE TITLE
getGeneratedKeys() only returns one ID on multiple insertions

### ISSUE THREAD

**Issue by alesimula** [xerial/sqlite-jdbc#468]
If i make multiple insertions in one query

`INSERT INTO 'mytable' ('id', 'name') VALUES
  ('1', 'alex'),
  ('2', 'jean');`

The ResultSet of getGeneratedKeys() will only hold the ID of the last entry

**Comment by gotson** [comment]
I think that's the default behaviour of SQLite to return a single value. You can check about [RETURNING](https://www.sqlite.org/lang_returning.html).

**Comment by gotson** [comment]
Closing this in favor of #329
