### ISSUE TITLE
Incompatibility setQueryTimeout() : JDK Statement  and  JDBC3Statement  implementation

### ISSUE THREAD

**Issue by gkamgang** [xerial/sqlite-jdbc#47]
Hello,
I am facing a problem using JDBC3Statement  sqlite implementation of Statement.

The JDK API says about Statement.setQueryTimeout() 

```
          seconds - the new query timeout limit in seconds; zero means there is no limit.
```

The JDBC3Statement   implementation do this : 

```
    public void setQueryTimeout(int seconds) throws SQLException {
        if (seconds < 0)
            throw new SQLException("query timeout must be >= 0");
        conn.setBusyTimeout(1000 * seconds);
    }
```

By setting 0 to setQueryTimeout, I expected to have an unlimit busy timeout, but I got a totally diferent result. 
Are you aware of this  ? 

Thanks,

**Comment by gotson** [comment]
Will be fixed by #91 i believe
