### ISSUE TITLE
Can't parse the .sqlite files

### ISSUE THREAD

**Issue by SachiAnn90** [xerial/sqlite-jdbc#475]
Hi, 

 I want to read the tables and columns from the .sqlite file using java or spring boot. Becasue I need to validate those table information which is in the .sqlite file. So Is there any method parse the file?

**Comment by pawelsalawa** [comment]
Open the file and execute `SELECT sql FROM sqlite_master` - you will get DDL statements for all tables, indexes, etc.

**Comment by gotson** [comment]
Closing this, as this is not driver related. Better suited for StackOverflow.
