### ISSUE TITLE
jdbc getWarnings() not implemented

### ISSUE THREAD

**Issue by johnspurlock** [xerial/sqlite-jdbc#483]
I'm unable to read non-fatal warnings after executing failed updates (say, after a fk constraint fails) via the standard getWarnings() calls (e.g. at the [connection](https://docs.oracle.com/javase/7/docs/api/java/sql/Connection.html#getWarnings()) level).  Quick peek at the code suggests this info is not implemented.

Is there a way to plumb this info up to make it available?  Either via jdbc getWarnings() or off of DB/NativeDB?

Thanks,
\- John

**Comment by gotson** [comment]
What kind of warnings would you expect ? I am not familiar with JDBC warnings, but i suppose they would carry some information coming from the underlying database.

**Comment by johnspurlock** [comment]
I'm confused, all of the information you asked for is in the initial comment.

I'd expect all non-fatal errors (errors that do not prevent execution) to be available in the standard getWarnings() calls, either at the connection level (linked above), or at the individual object level, i.e. the [Statement](https://docs.oracle.com/javase/7/docs/api/java/sql/Statement.html#getWarnings()), PreparedStatement, CallableStatement, ResultSet etc

[SQLWarning](https://docs.oracle.com/javase/7/docs/api/java/sql/SQLWarning.html) is a subclass of SQLException

i.e. any warnings that appear in other sqlite clients but are unavailable using this library (say, after a fk constraint fails)

**Comment by gotson** [comment]
> i.e. any warnings that appear in other sqlite clients but are unavailable using this library (say, after a fk constraint fails)

Maybe provide some context or examples, as you seem to have a fair idea of what you expect and nothing of that was mentioned in the initial comment.

**Comment by johnspurlock** [comment]
> I am not familiar with JDBC warnings

🤔 still confused - this project is a SQLite JDBC Driver, right?  Warnings have been part of the jdbc spec for over 20 years

https://www.google.com/search?q=jdbc+specification+%22getWarnings%22

**Comment by gotson** [comment]
You're not really helping your case here with this attitude.

**Comment by gotson** [comment]
Closing this as no feedback was received.
