### ISSUE TITLE
NativeDB#load initialization is racy

### ISSUE THREAD

**Issue by thinred** [xerial/sqlite-jdbc#484]
I understand that if multiple threads manage to get to this method, the writes to isLoaded and loadSucceeded will be racy. Some synchronization should be performed around these variables.

See https://github.com/xerial/sqlite-jdbc/blob/ddd8fd3294cb3a8eea5f3e003702dbeb52d3327a/src/main/java/org/sqlite/core/NativeDB.java#L59-L66.

**Comment by gotson** [comment]
Seems like `SQLiteJDBCLoader.initialize()` is [synchronized](https://github.com/xerial/sqlite-jdbc/blob/3d04d7df0c89240add2c92189adb30b6cb7e6ae0/src/main/java/org/sqlite/SQLiteJDBCLoader.java#L60), so shouldn't be a problem, no?

**Comment by gotson** [comment]
Closing this as no feedback was received.
