### ISSUE TITLE
PRIMARY and not null

### ISSUE THREAD

**Issue by gMan1990** [xerial/sqlite-jdbc#485]
```plain
CREATE TABLE IdPrimaryNotNull (
  "id" integer NOT NULL,
  PRIMARY KEY ("id")
);

sqlite> INSERT INTO IdPrimaryNotNull("id") VALUES (null);
Query OK - 1 row affected (0.01 sec)
```
```plain
CREATE TABLE IdPrimary (
  "id" integer,
  PRIMARY KEY ("id")
);

> INSERT INTO IdPrimary("id") VALUES (null);
Query OK - 1 row affected (0.01 sec)
```

What's the difference ?

**Comment by gwenn** [comment]
https://sqlite.org/lang_createtable.html#rowid
> if a rowid table has a primary key that consists of a single column and the declared type of that column is "INTEGER" in any mixture of upper and lower case, then the column becomes an alias for the rowid.

```
> SELECT rowid, id FROM IdPrimary;
1|1
```

**Comment by A248** [comment]
When using SQLite, you should always add a NOT NULL constraint to the primary key. For other RDMSes which are standard-compliant this is not an issue, because primary keys are implicitly not null.

> According to the SQL standard, PRIMARY KEY should always imply NOT NULL. Unfortunately, due to a bug in some early versions, this is not the case in SQLite.
