### ISSUE TITLE
Specify extract sqlite resource path

### ISSUE THREAD

**Issue by i-am-vt** [xerial/sqlite-jdbc#489]
When the sqlite file is in the the **resources** of a **jar** package, it will be extract to **java.io.tmpdir**.

Although it is a persistent file, some scheduled tasks under unix will clear the temporary directory.

Can a variable property be added to control the directory where the sqlite file is extracted? 

Just like the method **SQLiteJDBCLoader.getTempDir ()** used to control jnilib files.

**Comment by michael-o** [comment]
There is `org.sqlite.tmpdir`.

**Comment by gotson** [comment]
Closing this as the answer was given.
