### ISSUE TITLE
java.sql.SQLException: Query returns results when execute DDL statement

### ISSUE THREAD

**Issue by nikialeksey** [xerial/sqlite-jdbc#497]
Enviroment:
- `Java 1.8`
- `org.xerial:sqlite-jdbc:3.31.1`

Code:
```java
import org.junit.Test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;

public class SqliteBug {
    @Test
    public void bug() throws Exception {
        final Connection c = DriverManager.getConnection(
            "jdbc:sqlite::memory:"
        );

        final PreparedStatement stmt1 = c.prepareStatement(
            "CREATE TABLE t (t TEXT)"
        );
        stmt1.executeUpdate();
        stmt1.close();

        final PreparedStatement stmt2 = c.prepareStatement(
            "ALTER TABLE t RENAME TO t2"
        );
        stmt2.executeUpdate(); // java.sql.SQLException: Query returns results
        stmt2.close();
    }
}
```

```java
Query returns results
java.sql.SQLException: Query returns results
	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:92)
	at com.example.SqliteBug.bug(SqliteBug.java:31)
	...
```

**Comment by michael-o** [comment]
What type of result?

**Comment by nikialeksey** [comment]
@michael-o I've jist updated the description. I think It should work without any exception.

**Comment by michael-o** [comment]
That's interesting. Does it work with filebased DBs too? I assume that the `create table` statement returns 1 for the column created and that value is retained for the second run: https://github.com/xerial/sqlite-jdbc/blob/d28a8aaa4e1ca6d0795a2926b918d7c22c21cc2b/src/main/java/org/sqlite/core/CorePreparedStatement.java#L47

**Comment by nikialeksey** [comment]
@michael-o Yes, for filebased DBs the same exception

**Comment by michael-o** [comment]
That actually interesting, I am dumping a subset of an Oracle DB into SQLite with create table statements, but don't do any alter table.

**Comment by nikialeksey** [comment]
This test works fine with [h2](https://h2database.com/html/main.html) driver

**Comment by gotson** [comment]
Just tried the code above and it works on the latest `master`. I will close this.

**Comment by nikialeksey** [comment]
Thanks!
