### ISSUE TITLE
make: *** No rule to make target `clean-native'.  Stop.

### ISSUE THREAD

**Issue by Roman-Mueller-Hainbach** [xerial/sqlite-jdbc#499]
I'm trying to compile under Windows in order to add some custom compiler flags (I want to increase MAX_ATTACHED).
I've installed Docker and cloned the Git repository directly in "C:\sqlite-jdbc". I'm running the MinGW shell to invoke "make".
Strangely `make clean-native` works just fine, but running any of the targets involving docker (native-all, win64, linux64 or any other) fails when it comes to `docker run ... bash - c 'make clean-native ...`. Might be a problem with finding the Makefile when running this docker command.
Any help is greatly appreciated.

If you want to see the log, here it is:
`$ make native-all package
perl -p -e "s/sqlite3_api;/sqlite3_api = 0;/g" \
            target/sqlite-amalgamation-3310100/sqlite3ext.h > target/sqlite-3.31.1-Windows-x86_64/sqlite3ext.h
perl -p -e "s/^opendb_out:/  if(!db->mallocFailed && rc==SQLITE_OK){ rc = RegisterExtensionFunctions(db); }\nopendb_out:/;" \
            target/sqlite-amalgamation-3310100/sqlite3.c > target/sqlite-3.31.1-Windows-x86_64/sqlite3.c.tmp
perl -p -e "s/#if SQLITE_LIKE_DOESNT_MATCH_BLOBS/  \"JDBC_EXTENSIONS\",\n#if SQLITE_LIKE_DOESNT_MATCH_BLOBS/;" \
            target/sqlite-3.31.1-Windows-x86_64/sqlite3.c.tmp > target/sqlite-3.31.1-Windows-x86_64/sqlite3.c
cat src/main/ext/*.c >> target/sqlite-3.31.1-Windows-x86_64/sqlite3.c
gcc -o target/sqlite-3.31.1-Windows-x86_64/sqlite3.o -c -Itarget/sqlite-3.31.1-Windows-x86_64 -Itarget/sqlite-amalgamation-3310100 -D_JNI_IMPLEMENTATION_ -Ilib/inc_win -Os   -I"C:\Program Files\Java\jdk1.8.0_241/include" -I"C:\Program Files\Java\jdk1.8.0_241/include/win32" \
            -DSQLITE_ENABLE_LOAD_EXTENSION=1 \
            -DSQLITE_HAVE_ISNAN \
            -DSQLITE_HAVE_USLEEP \
            -DHAVE_USLEEP=1 \
            -DSQLITE_ENABLE_COLUMN_METADATA \
            -DSQLITE_CORE \
            -DSQLITE_ENABLE_FTS3 \
            -DSQLITE_ENABLE_FTS3_PARENTHESIS \
            -DSQLITE_ENABLE_FTS5 \
            -DSQLITE_ENABLE_JSON1 \
            -DSQLITE_ENABLE_RTREE \
            -DSQLITE_ENABLE_STAT4 \
            -DSQLITE_THREADSAFE=1 \
            -DSQLITE_DEFAULT_MEMSTATUS=0 \
            -DSQLITE_DEFAULT_FILE_PERMISSIONS=0666 \
            -DSQLITE_MAX_VARIABLE_NUMBER=250000 \
            -DSQLITE_MAX_MMAP_SIZE=1099511627776 \
             \
            target/sqlite-3.31.1-Windows-x86_64/sqlite3.c
target/sqlite-3.31.1-Windows-x86_64/sqlite3.c: In function 'openDatabase':
target/sqlite-3.31.1-Windows-x86_64/sqlite3.c:162445:48: warning: implicit declaration of function 'RegisterExtensionFunctions'; did you mean 'RegisterEventSourceW'? [-Wimplicit-function-declaration]
   if(!db->mallocFailed && rc==SQLITE_OK){ rc = RegisterExtensionFunctions(db); }
                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~
                                                RegisterEventSourceW
"$JAVA_HOME/bin/javac"  -d target/common-lib -sourcepath src/main/java -h target/common-lib src/main/java/org/sqlite/core/NativeDB.java
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: src\main\java\org\sqlite\jdbc3\JDBC3Connection.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
mv target/common-lib/org_sqlite_core_NativeDB.h target/common-lib/NativeDB.h
gcc -Itarget/sqlite-3.31.1-Windows-x86_64 -Itarget/sqlite-amalgamation-3310100 -D_JNI_IMPLEMENTATION_ -Ilib/inc_win -Os   -I"C:\Program Files\Java\jdk1.8.0_241/include" -I"C:\Program Files\Java\jdk1.8.0_241/include/win32" -I target/common-lib -c -o target/sqlite-3.31.1-Windows-x86_64/NativeDB.o src/main/java/org/sqlite/core/NativeDB.c
gcc -Itarget/sqlite-3.31.1-Windows-x86_64 -Itarget/sqlite-amalgamation-3310100 -D_JNI_IMPLEMENTATION_ -Ilib/inc_win -Os   -I"C:\Program Files\Java\jdk1.8.0_241/include" -I"C:\Program Files\Java\jdk1.8.0_241/include/win32" -o target/sqlite-3.31.1-Windows-x86_64/sqlitejdbc.dll target/sqlite-3.31.1-Windows-x86_64/NativeDB.o target/sqlite-3.31.1-Windows-x86_64/sqlite3.o -Wl,--kill-at -shared -static-libgcc
cp target/sqlite-3.31.1-Windows-x86_64/sqlitejdbc.dll /tmp/sqlitejdbc.dll
strip /tmp/sqlitejdbc.dll
cp /tmp/sqlitejdbc.dll target/sqlite-3.31.1-Windows-x86_64/sqlitejdbc.dll
cp target/sqlite-3.31.1-Windows-x86_64/sqlitejdbc.dll src/main/resources/org/sqlite/native/Windows/x86_64/sqlitejdbc.dll
cp target/sqlite-3.31.1-Windows-x86_64/sqlitejdbc.dll target/classes/org/sqlite/native/Windows/x86_64/sqlitejdbc.dll
./docker/dockcross-windows-x86 -a --rm bash -c 'make clean-native native CROSS_PREFIX=i686-w64-mingw32.static- OS_NAME=Windows OS_ARCH=x86'
make: *** No rule to make target 'clean-native'.  Stop.
make: *** [win32] Error 2`

**Comment by gotson** [comment]
MAX_ATTACHED is now available at runtime via limits, see #568. Closing this, please comment if still an issue.
