### ISSUE TITLE
Support OSGI

### ISSUE THREAD

**Issue by cristcost** [xerial/sqlite-jdbc#51]
I would like to use the library inside OSGi environment, and for it to work smoothly OSGi manifest should be added to the output JAR

**Comment by cristcost** [comment]
Hi, 
if this is implemented, the sqlite-jdbc could be easily used inside OSGi environment, and I would like to use it in Apache Karaf and Servicemix.

I could try to develop and provide a simple patch for this feature. Would you evaluate to release it if I do it?
Off course I'll test it before proposing the a pull request.

Basically, if everything goes smoothly, no line of java code will be modified and it will only added a plugin in the pom.xml

This plugin, maven-bundle-plugin, will be configured like in this project: https://github.com/cristcost/sensormix/blob/master/sensormix-datamodel-api/pom.xml

It will change the MANIFEST.MF by adding OSGi headers. Actually this sqlite-jdbc's manifest has these headers automatically generated:

Archiver-Version = Plexus Archiver
Created-By = Apache Maven 3.2.3
Manifest-Version = 1.0
Build-Jdk = 1.8.0_40
Built-By = leo

The intent is that using the maven-bundle-plugin, the following headers will be added:
Bundle-ManifestVersion
Bundle-SymbolicName
Bundle-Version
Bundle-Name
Bundle-Vendor
Export-Package
Import-Package

Thank you to provide me feedback on the interest

**Comment by andyjefferson** [comment]
See this commit https://github.com/andyjefferson/sqlite-jdbc/commit/eb812fdeaf2f06e0db7d2501b3311f2dd7513d56   to my sqlite-jdbc repo, based around how DataNucleus OSGi tags are created using Maven. Can add as a pull request at some point, or maybe you can adapt it if not meeting your needs

**Comment by cristcost** [comment]
Yeah, that should work!

I anyway prefer to configure the bundle symbolic name and description as the maven project:

<Bundle-SymbolicName>${project.artifactId}</Bundle-SymbolicName>
<Bundle-Description>${project.description}</Bundle-Description>

(or <Bundle-SymbolicName>${project.artifactId};singleton:=true</Bundle-SymbolicName>  to use the "singleton" options but I have never used it before).

I'll try your branch anyway and tell you if it work for me.

**Comment by xerial** [comment]
Released sqlite-jdbc-3.8.11.2 with #54 and let me know if this works or not.
Thanks!

**Comment by cristcost** [comment]
Hi,
the OSGi bundle works correctly :+1:
