### ISSUE TITLE
Doesn't support 64 bit android system.

### ISSUE THREAD

**Issue by gaorongfu** [xerial/sqlite-jdbc#511]
I copy org/sqlite/native/linux/android-arm/libslitejdbc.so to libs folder of my android project in Android Studio. When I run the package in my phone, I got the exception that libslitejdbc.so is 32 bit, not 64 bit.
I copy org/sqlite/native/linux/aarch64/libslitejdbc.so to libs folder of my android project in Android Studio. When I run the package in my phone, I got the exception that libc.so.6 not found...

**Comment by mipastgt** [comment]
Are there any plans to support 64 bit android systems? Support for it is mandatory now:
https://android-developers.googleblog.com/2019/01/get-your-apps-ready-for-64-bit.html

**Comment by michael-o** [comment]
Why don't you compile the shared object yourself?

**Comment by gotson** [comment]
Added in #662. Will be available once a release is done.

**Comment by gotson** [comment]
This is available in the latest snapshot, please give it a try.

**Comment by gotson** [comment]
Released as part of `3.39.2.0`
