### ISSUE TITLE
Statement.setFetchDirection non-compliant?

### ISSUE THREAD

**Issue by shevek** [xerial/sqlite-jdbc#515]
```
     * Gives the driver a hint as to the direction in which
     * rows will be processed in <code>ResultSet</code>
     * objects created using this <code>Statement</code> object.  The
     * default value is <code>ResultSet.FETCH_FORWARD</code>.
```

Giving this hint causes an exception.

```
java.sql.SQLException: ResultSet closed
	at org.sqlite.core.CoreResultSet.checkOpen(CoreResultSet.java:76)
	at org.sqlite.jdbc3.JDBC3ResultSet.setFetchDirection(JDBC3ResultSet.java:125)
	at org.sqlite.jdbc3.JDBC3Statement.setFetchDirection(JDBC3Statement.java:326)
```

**Comment by witmoca** [comment]
This JDBC only supports FETCH_FORWARD. 

https://github.com/xerial/sqlite-jdbc/blob/bb91612de41c4fec90a4736916c1a486b19855d5/src/main/java/org/sqlite/jdbc3/JDBC3ResultSet.java#L124-L129

The `checkOpen()` failed for you though, so something might've been going wrong. In any case, the function does not do anything useful.

**Comment by shevek** [comment]
Yes, the issue is that I want to write generic JDBC code which works on all database servers, and sqlite behaving differently doesn't help.

It's quite right - the statement and result set are NOT open before I execute the statement, but the call is still legal according to JDBC, also Postgresql, Oracle, Teradata, etc. Calling it on the statement is a message of intent with regard to a FUTURE ResultSet.
