### ISSUE TITLE
Function javadoc about aggregate not being supported, outdated?

### ISSUE THREAD

**Issue by aaime** [xerial/sqlite-jdbc#519]
The main Function javadoc states:
``<p>Aggregate functions are not yet supported, but coming soon.</p>``
see:
https://github.com/xerial/sqlite-jdbc/blob/master/src/main/java/org/sqlite/Function.java#L53

However there is a sub-class Function.Aggregate that seems to be doing just that. Is the javadoc outdated?

**Comment by tildedave** [comment]
I noticed this a few months back too; I think it's just outdated.  You could submit a PR to fix it if you wanted.
