### ISSUE TITLE
armv7 sqlite is compiled with IDIV

### ISSUE THREAD

**Issue by crnflke** [xerial/sqlite-jdbc#524]
The included ARMV7 sqlite library in 3.32.3.1 is compiled with idiv instructions which are not supported on some Cortex-A series processors (for example the Cortex-A8 and the Cortex-A9 do not include it).

The dockcross people have spotted the same issue (https://github.com/dockcross/dockcross/issues/290) and have a special dockcross for this - https://github.com/dockcross/dockcross/tree/master/linux-armv7a

I did a test recompile with this alternate dockcross image and this then worked correctly on our system (although as a note the CROSS_PREFIX changes to
```
/usr/xcc/arm-cortexa8_neon-linux-gnueabihf/bin/arm-cortexa8_neon-linux-gnueabihf- 
```

If you want to ship both versions then it is possible to determine if an ARM processor has it as it seems to indicate it in /proc/cpuinfo. On our imx6 we get

```
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpd32 
```

And the internet suggests that a Cortex A-15 will yield
```
Features : swp half thumb fastmult vfp edsp thumbee neon vfpv3 tls vfpv4 idiva idivt
```
(source: https://pyra-handheld.com/boards/threads/omap5432-at-home.75874/)

**Comment by xerial** [comment]
Thanks for the report! 

So it seems just using linux-armv7a dockcross image will fork for the maximum compatibilities. Let me try this cross compiler version.
