### ISSUE TITLE
When use sqlite-jdbc 3.32.*, actually it uses 3.15.1 in effective pom

### ISSUE THREAD

**Issue by TsanChao** [xerial/sqlite-jdbc#529]
in my pom.xml
![image](https://user-images.githubusercontent.com/10399848/90369917-1978f200-e09f-11ea-9f8f-c0f4562286da.png)
in effective pom:
![image](https://user-images.githubusercontent.com/10399848/90369946-239af080-e09f-11ea-8d9c-653e52287fe5.png)

**Comment by xerial** [comment]
I don't think this is the issue of sqlite-jdbc itself. Could you check other libraries that might be using sqlite-jdbc as a transitive dependency?

**Comment by michael-o** [comment]
`mvn dependency:analyze`

**Comment by gotson** [comment]
Closing this, please leave a comment if this is still an issue.
