### ISSUE TITLE
Cannot compile version 3.32.3.2 with SEE version (SQLite Encryption Extension)

### ISSUE THREAD

**Issue by mhanna** [xerial/sqlite-jdbc#530]
I used to compile the sqlite-jdbc with the equivalent SEE version without any issues.
but this particular version seems to not able to get compiled with SEE (without SEE it's compiles).

This is quoting of what i've talked to the SEE developer.

`Hi,

I'm trying to compile this version but getting the following errors

the only thing i do is, after successfully compiling this version (without SEE), 

adding the sqlite3-see-aes256-ofb.c. to src/main/ext and recompile generates the following errors..

any advice?

I managed to compile previous versions (last one before this version was 3.27.1)

target/sqlite-3.32.3-Linux-x86_64/sqlite3.c:253838:13: error: redefinition of ‘setRawDateNumber’

 static void setRawDateNumber(DateTime *p, double r){

             ^

target/sqlite-3.32.3-Linux-x86_64/sqlite3.c:22024:13: note: previous definition of ‘setRawDateNumber’ was here

 static void setRawDateNumber(DateTime *p, double r){

             ^

target/sqlite-3.32.3-Linux-x86_64/sqlite3.c:253863:12: error: redefinition of ‘parseDateOrTime’

 static int parseDateOrTime(

            ^

target/sqlite-3.32.3-Linux-x86_64/sqlite3.c:22049:12: note: previous definition of ‘parseDateOrTime’ was here

 static int parseDateOrTime(

            ^

target/sqlite-3.32.3-Linux-x86_64/sqlite3.c:253896:12: error: redefinition of ‘validJulianDay’

 static int validJulianDay(sqlite3_int64 iJD){

            ^

target/sqlite-3.32.3-Linux-x86_64/sqlite3.c:22082:12: note: previous definition of ‘validJulianDay’ was here

 static int validJulianDay(sqlite3_int64 iJD){

            ^

target/sqlite-3.32.3-Linux-x86_64/sqlite3.c:253903:13: error: redefinition of ‘computeYMD’

 static void computeYMD(DateTime *p){

             ^

target/sqlite-3.32.3-Linux-x86_64/sqlite3.c:22089:13: note: previous definition of ‘computeYMD’ was here

 static void computeYMD(DateTime *p){

             ^

target/sqlite-3.32.3-Linux-x86_64/sqlite3.c:253932:13: error: redefinition of ‘computeHMS’

 static void computeHMS(DateTime *p){

             ^

target/sqlite-3.32.3-Linux-x86_64/sqlite3.c:22118:13: note: previous definition of ‘computeHMS’ was here

 static void computeHMS(DateTime *p){

             ^

target/sqlite-3.32.3-Linux-x86_64/sqlite3.c:253951:13: error: redefinition of ‘computeYMD_HMS’

 static void computeYMD_HMS(DateTime *p){

             ^

target/sqlite-3.32.3-Linux-x86_64/sqlite3.c:22137:13: note: previous definition of ‘computeYMD_HMS’ was here

 static void computeYMD_HMS(DateTime *p){

             ^

target/sqlite-3.32.3-Linux-x86_64/sqlite3.c:253959:13: error: redefinition of ‘clearYMD_HMS_TZ’

 static void clearYMD_HMS_TZ(DateTime *p){

             ^

target/sqlite-3.32.3-Linux-x86_64/sqlite3.c:22145:13: note: previous definition of ‘clearYMD_HMS_TZ’ was here

 static void clearYMD_HMS_TZ(DateTime *p){

             ^

target/sqlite-3.32.3-Linux-x86_64/sqlite3.c:253997:12: error: redefinition of ‘osLocaltime’

 static int osLocaltime(time_t *t, struct tm *pTm){

            ^

target/sqlite-3.32.3-Linux-x86_64/sqlite3.c:22183:12: note: previous definition of ‘osLocaltime’ was here

 static int osLocaltime(time_t *t, struct tm *pTm){

            ^

target/sqlite-3.32.3-Linux-x86_64/sqlite3.c:254036:22: error: redefinition of ‘localtimeOffset’

 static sqlite3_int64 localtimeOffset(

                      ^

target/sqlite-3.32.3-Linux-x86_64/sqlite3.c:22222:22: note: previous definition of ‘localtimeOffset’ was here

 static sqlite3_int64 localtimeOffset(

                      ^

target/sqlite-3.32.3-Linux-x86_64/sqlite3.c:254107:3: error: conflicting types for ‘aXformType’`

This is what SEE developer responds about this issue

"
I looked at this project on GitHub.  It appears that they have set up
the makefile such that it would *only* build using non-SEE source code
downloaded from the public SQLite website.  I do not see a way to
substitute an alternative "sqlite3.c" file - which is what you need to
do.

I would suggest contacting the developers of sqlite-jdbc and ask them
how you can compile their library using a non-standard "sqlite3.c"
source file obtained from some source other than the public SQLite
download page.  If anybody knows how to do that, they will.  I am not
familiar with their project. "

**Comment by gotson** [comment]
Is this still an issue?

**Comment by mhanna** [comment]
yes, if you can make a new version for sqlite-jdbc that will be able to compile with the equivalent SEE version it will be great.

**Comment by gotson** [comment]
Reading the SEE website, you should replace the amalgamation with the file you got from SEE.

You mention a couple things:

> adding the sqlite3-see-aes256-ofb.c. to src/main/ext and recompile generates the following errors..

This is for extensions, while what you have is a complete amalgamation.

> I managed to compile previous versions (last one before this version was 3.27.1)

Can you maybe provide some details on how you did that ?

---

If i understand correctly, this ticket is more of a question on how you can build the project with the SEE file you already have, is that a fair assessment ?

**Comment by mhanna** [comment]
What i generally do is

1. Change the sqlite max attached dbs from 10 (default) to max 125

- this is done by clonning sqlite-jdbc [https://github.com/xerial/sqlite-jdbc/], 
- build the relevant release (make) 
- change the max attached dbs for all the os-platforms 
- sed -i 's|define SQLITE_MAX_ATTACHED 10|define SQLITE_MAX_ATTACHED 125|' target/*/sqlite3.c

2. add the SEE extension

- cp see-sources/see-aes256-ofb.c sqlite-jdbc/src/main/ext 
- Enable encryption + thread saftey + FTS
- vi sqlite-jdbc/Makefile.common
- update to
SQLITE_FLAGS := -DSQLITE_HAS_CODEC=1 -DSQLITE_ENABLE_FTS4 -DSQLITE_THREADSAFE=1 $($(target)_SQLITE_FLAGS)

3. build the custom version
- make

**Comment by gotson** [comment]
> * cp see-sources/see-aes256-ofb.c sqlite-jdbc/src/main/ext

I think what you need go change is this. It should replace the full amalgamation.

**Comment by gotson** [comment]
Check #464 and #466, seems like there is support for external amalgamation file

**Comment by gotson** [comment]
@mhanna i have updated the documentation [for using external amalgamation](https://github.com/xerial/sqlite-jdbc/blob/master/CONTRIBUTING.md#build-with-an-external-amalgamation-archive).

Given SEE is provided as a source `.c` file, you could try 2 different ways:

1. Compile as object, and give that to our makefile:
  - Follow instructions 3.2 from [here](https://www.sqlite.org/see/doc/release/www/readme.wiki)
  - pass the generated `.a` file in `SQLITE_OBJ`, and the `sqlite3.h` in `SQLITE_HEADER`, as explained [here](https://github.com/xerial/sqlite-jdbc/blob/master/CONTRIBUTING.md#build-with-an-external-amalgamation-archive)
2. Prepare a source directory, and pass that to our makefile:
  - Prepare a directory with `sqlite3.h` from SEE, and the flavor of SQLite SEE you need renamed as `sqlite3.c`
  - `make native SQLITE_SOURCE="/path/to/that/directory"`

**Comment by mhanna** [comment]
@gotson Thanks. looks good.

However, The SEE's sqlite3.h is not really needed, only sqlite3.c
So i managed to finish the build by replacing the target/sqlite-amalgamation-<version>/sqlite3.c by the SEE's one

**Comment by gotson** [comment]
Glad you worked it out. As long as the source file you get from SEE is the same version as the one downloaded by the amalgamation, it should work fine, but using the header from the same package would remove uncertainties!
