### ISSUE TITLE
Download link is broken

### ISSUE THREAD

**Issue by FrancoisGuillem** [xerial/sqlite-jdbc#531]
Hi,

The download link in the README file is not working anymore.  Where can we get the  .jar file?

**Comment by xerial** [comment]
Thanks. I didn't aware bitbucket, where jar files were hosted, closed Mercurial based repository. 

You can download jar files from Maven as a workaround:
https://repo1.maven.org/maven2/org/xerial/sqlite-jdbc/3.32.3.2/

**Comment by xerial** [comment]
Fixed
