### ISSUE TITLE
How Do I Solve CVSS Vulnerabilities in an Earlier Version?

### ISSUE THREAD

**Issue by g00229729** [xerial/sqlite-jdbc#538]
We used sqlite-jdbc 3.32.3 for trial. However, during vulnerability scanning, the version information of some vulnerabilities in this version is 3.21.0 or 3.23.1, and the specific file is libsqlitejdbc.so. What are the causes and how to handle the vulnerabilities?

**Comment by michael-o** [comment]
> How Do I Solve CVSS Vulnerabilities in an Earlier Version?

Upgrade!

**Comment by gotson** [comment]
We only support latest versions. 

> > How Do I Solve CVSS Vulnerabilities in an Earlier Version?
> 
> Upgrade!

This!
