### ISSUE TITLE
First Button 'download' says on click - "This Link is not valid anymore"

### ISSUE THREAD

**Issue by jonas-weimar** [xerial/sqlite-jdbc#539]
In the readme the link 'download - "https://bitbucket.org/xerial/sqlite-jdbc/downloads"' doesn't work anymore. Shows me this when I click on it.

![Bildschirmfoto 2020-09-08 um 15 50 33](https://user-images.githubusercontent.com/38507420/92485506-52623d80-f1eb-11ea-8ae7-bcd5a44f1c7e.png)

**Comment by xerial** [comment]
Fixed the link. Thanks for reporting
