### ISSUE TITLE
FreeBSD native binaries status

### ISSUE THREAD

**Issue by gotson** [xerial/sqlite-jdbc#542]
Hi,

I noticed that the freebsd native binaries are 4 years old, but despite searching the repo I couldn't find a clear explanation about why the native binaries are not available for recent versions.

Would you be able to summarize the status or blockers about compiling those native binaries? 

Thanks

**Comment by despair86** [comment]
no automation CI available - i'm on a sun ultra (amd64) which also doesn't get binaries, have to build them myself using `gmake native` and `mvn install` (don't forget to patch `Makefile.common` to use `cc` instead of `gcc` on bsd (clang)

**Comment by michael-o** [comment]
@gotson Please read: https://github.com/xerial/sqlite-jdbc/issues/495

**Comment by michael-o** [comment]
I would highly prefer that the JAR would come in two flavors: with and w/o native binaries.

**Comment by gotson** [comment]
> @gotson Please read: #495

I was hoping from a status from the maintainer. 

My understanding is that adding native binaries that are not buildable in a reproducible way (ie docker and dockcross) is not the way forward, because they will be outdated very quickly. 

None of the open PRs address the issue of adding docker cross compilation for freebsd if I am correct.

**Comment by michael-o** [comment]
@gotson Why? If you can build flawlessly with clang in a Jail and this works for ports, why not have it in ports?

**Comment by gotson** [comment]
Probably because if it was the case the PR would have been merged? I'm just making an educated guess here, but that wouldn't work on windows, right?
