### ISSUE TITLE
Temp files on linux removed but still kept and disk space is not released

### ISSUE THREAD

**Issue by slavag** [xerial/sqlite-jdbc#547]
Hi,
We have server component that run on linux server (Java 8) , recently I found that somehow lost almost 4.2TB from 5TB of disk space. So used lsof to find (deleted) files, which are deleted but still holded by process that still running. And I found that  largest file (4.2TB) is in sqlite temp dir (which we set at the begging of the process , and only once). Now when process is still running I checked content of the sqlite.tmp directory and it's empty, but lsof displays that there was a temp file (etilqs_227e251304a26dca) , it's deleted but still locked by process.
Please see attached screenshot.

<img width="1001" alt="Screen Shot 2020-10-08 at 15 30 56" src="https://user-images.githubusercontent.com/511540/95460452-a47ab800-097d-11eb-97a1-e3bc72e8e010.png">

As those files solely managed by Sqlite and our process is not aware about them, can it be that SQLite doesn't close file descriptor to this file and leaves it locked ? 
Once process is finished the disk space freed.
Please advise.
Thanks

**Comment by slavag** [comment]
During that I found that process is somehow stuck on:
java.lang.Thread.State: RUNNABLE
	at org.sqlite.core.NativeDB.step(Native Method)
	- locked <0x000000012a233708> (a org.sqlite.core.NativeDB)
	at org.sqlite.core.DB.executeBatch(DB.java:806)
	- locked <0x000000012a233708> (a org.sqlite.core.NativeDB)
	at org.sqlite.core.CorePreparedStatement.executeBatch(CorePreparedStatement.java:72)

Please advise.

**Comment by dkfellows** [comment]
The most obvious possible source of problems is failing to close resources (connections, statements, result sets) or keeping transactions open. (Also make sure that transaction start has a timeout and that you're keeping transactions short if you can.) I'm not saying that those are definitely your problem, but it's really a very good idea to verify that they aren't…

**Comment by gotson** [comment]
@slavag is this still a problem ?

**Comment by gotson** [comment]
Closing this as no feedback was received.
