### ISSUE TITLE
When we use 3.32.3.1,  appears “ libsqlitejdbc.so : cannot map segment bug from shared target”

### ISSUE THREAD

**Issue by elfysuen** [xerial/sqlite-jdbc#554]
Our operating system is Galaxy kylin v4.2, the chip is ARM chip,When we use 3.32.3.1,  appears “ libsqlitejdbc.so : cannot map segment bug from shared target”

**Comment by michael-o** [comment]
Does SQLite work at all? Have you tried to write a simple C program and call it?

**Comment by elfysuen** [comment]
No,SQLite  file is normal，when this file is used, so temporary files are generated every time the file is called.

**Comment by michael-o** [comment]
That is expected. I would recommend to remove all native libraries from your JAR and place the native library on the system where `java.library.path` picks up. I have added that recently to this library: https://github.com/xerial/sqlite-jdbc/commit/bb91612de41c4fec90a4736916c1a486b19855d5.

**Comment by elfysuen** [comment]
ok,thanks
