### ISSUE TITLE
Problem with using sqlite-jdbc from self-contained application on Linux

### ISSUE THREAD

**Issue by nocach** [xerial/sqlite-jdbc#556]
Hi,
  I have a question about using library from bundled environment created by  Java Packager on Linux (Fedora 31 - 64bit). After creating rpm package using jpackager (using 1.8 java sdk) and installing it on the system, I'm getting following error:

`symbol lookup error: /tmp/sqlite-3.32.3-afe34c11-93ab-4c31-9d2d-9aa26ae2b08f-libsqlitejdbc.so: undefined symbol: pthread_mutexattr_init`

I tried to play with compile and linked flags in Makefile.common to see if it will resolved the issue, but with no luck. After using -pthread or -lpthread I'm getting another similar error:

`symbol lookup error: /tmp/jna-1659220596/jna5673263922947169578.tmp: undefined symbol: pthread_once`

Application runs without issues if started from Intellij Idea using same sdk. Any help or direction will be appreciated as this blocks a possibility to distribute my app.

**Comment by michael-o** [comment]
Does your pthread implementation provide this function at all?

**Comment by nocach** [comment]
I'm not really familiar with compiling and linking c++ code, could you please tell me how to check that? I have gcc version 9.2.1 installed.

**Comment by michael-o** [comment]
Please open `pthread.h` from `/usr/include` and search for the symbol. It is a POSIX definition, it should be there. Even my stoneage RHEL 7 has it:
```
$ grep -r pthread_mutexattr_init /usr/include/
/usr/include/pthread.h:extern int pthread_mutexattr_init (pthread_mutexattr_t *__attr)
/usr/include/bits/libc-lock.h:  __pthread_mutexattr_init (&__attr);                  \
/usr/include/bits/libc-lock.h:extern int __pthread_mutexattr_init (pthread_mutexattr_t *__attr);
/usr/include/bits/libc-lock.h:# pragma weak __pthread_mutexattr_init
/usr/include/c++/4.8.2/x86_64-redhat-linux/32/bits/gthr-default.h:__gthrw(pthread_mutexattr_init)
/usr/include/c++/4.8.2/x86_64-redhat-linux/32/bits/gthr-default.h:      __r = __gthrw_(pthread_mutexattr_init) (&__attr);
/usr/include/c++/4.8.2/x86_64-redhat-linux/32/bits/gthr-posix.h:__gthrw(pthread_mutexattr_init)
/usr/include/c++/4.8.2/x86_64-redhat-linux/32/bits/gthr-posix.h:      __r = __gthrw_(pthread_mutexattr_init) (&__attr);
/usr/include/c++/4.8.2/x86_64-redhat-linux/bits/gthr-default.h:__gthrw(pthread_mutexattr_init)
/usr/include/c++/4.8.2/x86_64-redhat-linux/bits/gthr-default.h:      __r = __gthrw_(pthread_mutexattr_init) (&__attr);
/usr/include/c++/4.8.2/x86_64-redhat-linux/bits/gthr-posix.h:__gthrw(pthread_mutexattr_init)
/usr/include/c++/4.8.2/x86_64-redhat-linux/bits/gthr-posix.h:      __r = __gthrw_(pthread_mutexattr_init) (&__attr);
```

**Comment by nocach** [comment]
This is the output

> grep -r pthread_mutexattr_init /usr/include/
> /usr/include/c++/9/x86_64-redhat-linux/32/bits/gthr-default.h:__gthrw(pthread_mutexattr_init)
> /usr/include/c++/9/x86_64-redhat-linux/32/bits/gthr-default.h:      __r = __gthrw_(pthread_mutexattr_init) (&__attr);
> /usr/include/c++/9/x86_64-redhat-linux/32/bits/gthr-posix.h:__gthrw(pthread_mutexattr_init)
> /usr/include/c++/9/x86_64-redhat-linux/32/bits/gthr-posix.h:      __r = __gthrw_(pthread_mutexattr_init) (&__attr);
> /usr/include/c++/9/x86_64-redhat-linux/bits/gthr-default.h:__gthrw(pthread_mutexattr_init)
> /usr/include/c++/9/x86_64-redhat-linux/bits/gthr-default.h:      __r = __gthrw_(pthread_mutexattr_init) (&__attr);
> /usr/include/c++/9/x86_64-redhat-linux/bits/gthr-posix.h:__gthrw(pthread_mutexattr_init)
> /usr/include/c++/9/x86_64-redhat-linux/bits/gthr-posix.h:      __r = __gthrw_(pthread_mutexattr_init) (&__attr);
> /usr/include/pthread.h:extern int pthread_mutexattr_init (pthread_mutexattr_t *__attr)


and 

> ldd /tmp/sqlite-3.32.3.2-43671722-090e-4788-aded-a4a0da4fdd9b-libsqlitejdbc.so
> 	linux-vdso.so.1 (0x00007ffcc596d000)
> 	libc.so.6 => /lib64/libc.so.6 (0x00007f67f1df4000)
> 	/lib64/ld-linux-x86-64.so.2 (0x00007f67f22c2000)

**Comment by michael-o** [comment]
Please try https://stackoverflow.com/q/2127797/696632.

**Comment by nocach** [comment]
As I stated in the openning I tried to use -pthread, but get another error:

`symbol lookup error: /tmp/jna-1659220596/jna5673263922947169578.tmp: undefined symbol: pthread_once`

I would also add that the problem occures only when launching jar from bundled java runtime. When using direct java -jar with same jdk applicaiton works as expected...

**Comment by michael-o** [comment]
What do you mean by "bundled Java runtime"=

**Comment by nocach** [comment]
Using https://docs.oracle.com/javase/8/docs/technotes/tools/windows/javapackager.html you can create executable (for windows, linux and macos) that includes java runtime - this way user can install application and does not have to worry if he has java installed.

**Comment by michael-o** [comment]
OK, there must be some issue with the native loading. This is out of scope here. You contact some OpenJDK mailing list about that. It is likely that the runtime linking is different then.

**Comment by nocach** [comment]
This resulted in jdk bug https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8257474.

**Comment by michael-o** [comment]
I assumed so!
