### ISSUE TITLE
 jdbc查询速度的问题 Query speed of JDBC

### ISSUE THREAD

**Issue by niocoders** [xerial/sqlite-jdbc#557]
I use java8 and SQLite v3.7.17. When I use JDBC query, the speed is particularly slow, but when I change the JDBC version, the speed will be better. I want to know which JDBC version my SQLite version is most suitable for. I look forward to your reply. Thank you!

**Comment by michael-o** [comment]
Upgrade SQLite first.

**Comment by niocoders** [comment]
Is there any solution without changing the version? Thank you

**Comment by gotson** [comment]
We only support latest versions.
