### ISSUE TITLE
v3.32.3.2's jar is not built on its source

### ISSUE THREAD

**Issue by bthulu** [xerial/sqlite-jdbc#560]
[click here to 3.32.3.2](https://github.com/xerial/sqlite-jdbc/releases/tag/3.32.3.2)
no armv6 exists in both zip source and tar.gz source, but it exists in jar, and some class is also modified
why don't release a jar based on its source? is there anything else needs to secure?

**Comment by michael-o** [comment]
??? the native component is compiled from code.

**Comment by xerial** [comment]
The source code of sqlite is downloaded in Makefile and it's not distributed through Maven.
