### ISSUE TITLE
Is't possible to upgrade CENTOS5 to 6/7/8 in build env?

### ISSUE THREAD

**Issue by wuhongzhi** [xerial/sqlite-jdbc#576]
@xerial, Is't possible to build sqlite-jdbc on CENTOS_6/7/8 in docker as, These release are very common.
The current version of linux_x86/64 based on  centos_5 which is very very old. 
```
docker run -ti xerial/centos5-linux-x86_64 gcc-version
gcc (GCC) 4.1.2 20080704 (Red Hat 4.1.2-55)
Copyright (C) 2006 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

docker run xerial/centos5-linux-x86 gcc --version
gcc (GCC) 4.1.2 20080704 (Red Hat 4.1.2-55)
Copyright (C) 2006 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by xerial** [comment]
A reason I'm using a very ancient CentOS to support various Linux versions. sqilte-jdbc embeds glibc to the native lib, and glibc is designed to be forward-compatible, that is, an older version of glibc works with the new version of glibc. 

If we upgrade the Linux version, a newer glibc will be embedded to sqlite-jdbc, and it will crash applications.

**Comment by wuhongzhi** [comment]
As my patch for string encoding in c has +40% performance boost compared with default gcc(see  https://github.com/wuhongzhi/sqlite-jdbc/commit/1061560d79779c835a574235b83c32b9ec13b6bd), that's way i ask this question.

Anyway it's reasonable for  your  consideration. I'll close this issue.
