### ISSUE TITLE
Compile native libs for Windows ARM 32 and 64

### ISSUE THREAD

**Issue by danysantiago** [xerial/sqlite-jdbc#577]
Hi - Can you please include binaries for the 32bit and 64bit ARM architectures for Windows so that devices such as the Microsoft Surface Pro X are compatible with the library.

```
Caused by: java.lang.Exception: No native library is found for os.name=Windows and os.arch=aarch64. path=/org/sqlite/native/Windows/aarch64
```

Thanks!

**Comment by xerial** [comment]
I own Surface Pro X, but in Windows, I usually use WSL2 (Linux), so I didn't need this support 😅 

Actually, for building sqlite-jdbc, I uses cross-compilers provided here https://github.com/dockcross/dockcross, but dockcross still doesn't have any images for Windows Arm64. I think we need them. 

I can build sqlite-jdbc as a one-shot using my Surface Pro X, but this approach makes maintaining this project difficult... Hopefully, dockcross have a cross-compiler for Windows Arm64. 

For Windows Arm32, I'm not sure it's worth doing.

**Comment by boswelja** [comment]
Unfortunately working in WSL isnt an option if an Android app depends on this. As far as I'm aware we can't emulate x86 within WSL and the Android SDK tools can't properly download & run in ARM64 Linux.
I'll make an issue over at Dockercross if it doesn't already exist.

**Comment by xerial** [comment]
Thanks for filing https://github.com/dockcross/dockcross/issues/463

**Comment by boswelja** [comment]
Seems like dockcross is waiting for https://github.com/mxe/mxe to add ARM/ARM64 support. Looks like there's a fork with LLVM working for ARM64 but still missing a fair bit to get an image up

**Comment by boswelja** [comment]
I've been doing some digging and came across https://github.com/mstorsjo/llvm-mingw
Had a look inside the prebuilt Docker images and it seems to include cross targets for aarch64 windows. Not sure on stability as haven't tried compiling anything but the possibility is there. Think we can use it?

**Comment by boswelja** [comment]
Dockcross now has a `windows-arm64` image, if you'd like to give that a try.

**Comment by gotson** [comment]
@boswelja are you able to test those dockcross images and if it works fine submit a PR?

**Comment by gotson** [comment]
I can try to add a PR for this, who would be able to test it?

**Comment by boswelja** [comment]
I've got Docker set up on my machine, so I can run dockerfiles for testing

**Comment by xerial** [comment]
@gotson I can also test it using my Surface Pro X :)

**Comment by gotson** [comment]
Please try the binaries added in https://github.com/xerial/sqlite-jdbc/pull/644

**Comment by xerial** [comment]
Confirmed it's working on Surface Pro X (Win - Arm64)!
