### ISSUE TITLE
Raspberry concurrency issue

### ISSUE THREAD

**Issue by DamianNP** [xerial/sqlite-jdbc#582]
I have a concurrency related issue involving queries.
Here is a code used for testing using an in Memory DB.
One thread making queries and another thread making inserts.
At some point, the thread making queries gets stucked and queries made from anywhere get stuck too.
Things get worse when writing to a file
With in memory db the problem is solved using a ReentrantLock but it doesn't help when using a file.
This level of concurrency is for testing purposes. The original application makes sporadic queries from any thread and the problem arise several times a day.

Xerial library: sqlite-jdbc-3.34.0.jar  (The problem is the same with previous versions too)

Model           : Raspberry Pi 3 Model B Rev 1.2
Hardware      : BCM2835
Revision        : a22082

Processor model name:  ARMv7  Rev. 4 (v7l)
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03

The right native library is automatically being used:
org/sqlite/native/Linux/armv7/libsqlitejdbc.so

OS: 32 bit. Linux raspberrypi 5.10.9-v7+ #1396

SQLite "Pragma" Compile Options:
COMPILER=gcc-6.3.1 20170109
DEFAULT_FILE_PERMISSIONS=0666
ENABLE_COLUMN_METADATA
ENABLE_FTS3
ENABLE_FTS3_PARENTHESIS
ENABLE_FTS5
ENABLE_JSON1
ENABLE_LOAD_EXTENSION
ENABLE_RTREE
ENABLE_STAT4
HAVE_ISNAN
JDBC_EXTENSIONS
MAX_MMAP_SIZE=1099511627776
MAX_VARIABLE_NUMBER=250000
THREADSAFE=1

Compile-time thead-safe parameter is in Serialized mode (THREADSAFE=1)

Kotlin code:
`val config = SQLiteConfig().apply{
    setOpenMode(SQLiteOpenMode.READWRITE)
    setOpenMode(SQLiteOpenMode.CREATE)
    setOpenMode(SQLiteOpenMode.FULLMUTEX) // "Serialized" threading mode (default)
    setOpenMode(SQLiteOpenMode.OPEN_MEMORY) // In Memory RAM
}
val conn = DriverManager.getConnection("jdbc:sqlite::memory:", config.toProperties())
val stm = conn.prepareStatement("CREATE TABLE Test (col1 TEXT)")
stm.execute()
stm.close()

var insert = 0
var query = 0
var insertElapsed = 0L
var queryElapsed = 0L
val queryStage = AtomicReference<String>()
val start = System.currentTimeMillis()
val lock = ReentrantLock()
val testTime = 5_000

val t1 = Thread {
	try {
		println("Insert start")
		while(insertElapsed < testTime){
//          lock.lock()
			val stm = conn.prepareStatement("INSERT INTO 'Test' (col1) VALUES (?)")
			stm.setString(1,"asdf")
			stm.executeUpdate()
			stm.close()
//          lock.unlock()
			insert++
			insertElapsed = System.currentTimeMillis() - start
		}
		println("Insert Ended $insert")
	} catch (e: Throwable){
		println(e.toString())
	}
}
val t2 = Thread{
	try{
		println("Query start")
		while(queryElapsed < testTime){
//          lock.lock()
			queryStage.set("Statement")
			val stm = conn.prepareStatement("SELECT * FROM 'Test' LIMIT 1")
			queryStage.set("Execute")
			val rs = stm.executeQuery()
			queryStage.set("ResultSet")
			val value = rs.getString(1)
			queryStage.set("Close")
			rs.close()
			stm.close()
//          lock.unlock()
			query++
			queryElapsed = System.currentTimeMillis() - start
		}
		queryStage.set("Ended")
		println("Query Ended $query")
	} catch (e: Throwable){
		println(e.toString())
	}
}
t1.start()
t2.start()
sleep(testTime+500)
println("Queries made: $query, time elapsed: $queryElapsed, last stage: ${queryStage.get()}")
println("Inserts made: $insert, time elapsed: $insertElapsed")`

**Comment by derreisende77** [comment]
You are using one JDBC connection in two threads. See [this link](https://stackoverflow.com/questions/1531073/is-java-sql-connection-thread-safe) for further information. You should use separate connections in the threads.
