### ISSUE TITLE
broken downloads page link

### ISSUE THREAD

**Issue by Vandivier** [xerial/sqlite-jdbc#585]
downloads page link in README.md under `https://github.com/xerial/sqlite-jdbc#download` links to a bitbucket url which displays "that link has now power here"

**Comment by T-Berger** [comment]
It still isn't fixed get nowe:

Repository not found
The requested repository either does not exist or you do not have access. If you believe this repository exists and you have access, make sure you're authenticated.

**Comment by gotson** [comment]
Duplicate of #544
