### ISSUE TITLE
Calling ResultSet.getBlob() results in an error

### ISSUE THREAD

**Issue by udittmer** [xerial/sqlite-jdbc#589]
even though "ResultSet.getMetaData().getColumnTypeName(1) = BLOB"

The issue surfaced when using SquirrelJDBC, but the folks over there think it's a driver issue; see [this ticket](https://sourceforge.net/p/squirrel-sql/bugs/1464/) for the details.

[ClassCastException.sqlite.zip](https://github.com/xerial/sqlite-jdbc/files/6139701/ClassCastException.sqlite.zip)

**Comment by gotson** [comment]
Is this still an issue ? Can you provide more details ?

**Comment by udittmer** [comment]
Yes, this still happens with sqlite-jdbc-3.36.0.3.jar

**Comment by gotson** [comment]
as indicated in #622 you can use `getBytes` to retrieve the whole blob as a `byte[]`.

Implementing `getBlob` is not required in the JDBC spec, so SquirrelJDBC should be able to catch that `SQLFeatureNotSupportedException` and try a `getBytes` instead.

**Comment by gotson** [comment]
Closing this in favor of #622
