### ISSUE TITLE
Incorrect column type detected after 3.25.2

### ISSUE THREAD

**Issue by R-One-Guy** [xerial/sqlite-jdbc#591]
Hello all,
Using squirrel, I read a table from a DB file. The schema is :

```sql
CREATE TABLE IF NOT EXISTS "rl_edd_journey" (
Ordre   REAL    not null,
JourneyId       STRING  ,
StartTime       REAL    ,
EndTime REAL    ,
PointDeDepart   STRING  not NULL,
PointDArrivee   STRING  not NULL,
Conducteur      STRING  not NULL,
OdometreDepart  INTEGER not NULL,
OdometreArrivee INTEGER not NULL,
OdometreArriveeDetail   REAL    ,
TripADepart     REAL    ,
TripAArrivee    REAL    ,
Commentaires    STRING  ,
IdPleinEss INTEGER,
IdPleinGPL INTEGER,
primary key (Ordre)
);
```

A select on that table may give errors on columns `JourneyId` and `Commentaires` after version 3.25.2 : they are detected as `BigDecimal` instead of `String` : `getColumnType` is 0 for that version, but 2 for newest ones, including 3.34.0.
This happens when the first row of those columns is NULL. When the first row value is not NULL, the value of `getColumnType` is 12.
Please help solving this prolem.
Kind regards,
/R One

**Comment by gotson** [comment]
This is the expected behaviour.

Check [here](https://www.sqlite.org/datatype3.html) for section _3.1. Determination Of Column Affinity_, rule 2 and 5:
>2. If the declared type of the column contains any of the strings "CHAR", "CLOB", or "TEXT" then that column has TEXT affinity. Notice that the type VARCHAR contains the string "CHAR" and is thus assigned TEXT affinity.
>5. Otherwise, the affinity is NUMERIC.

`STRING` will not yield a column affinity of `VARCHAR` but of `NUMERIC`
