### ISSUE TITLE
How do you compile the native SQLite?

### ISSUE THREAD

**Issue by KrKing12138** [xerial/sqlite-jdbc#599]
I modified part of the code of [SQLite](https://www.sqlite.org/2021/sqlite-amalgamation-3350500.zip) according to my need, and want to use my modified SQLite in Java. 
Could you please tell me how I should compile SQLite to get files like libsqlitejdbc.so and apply them to SQLite-JDBC?
By the way, my OS is Linux x86_64.

**Comment by gotson** [comment]
Check the makefile, the amalgamation is downloaded and unpacked before being built. You could modify the makefile to point to your own amalgamation instead.
