### ISSUE TITLE
UnitTests fail on Linux/Ubuntu 12.04 LTS 64 bits with UnsatisfiedLinkError

### ISSUE THREAD

**Issue by driekus77** [xerial/sqlite-jdbc#6]
I've cloned the sqlite-jdbc and tried to build it, but got an UnsatisfiedLinkError running the Unit Tests.

Removing -fvisibility=hidden from Makefile.common fixed it.

System info:
 - Linux msdes076 3.2.0-70-generic #105-Ubuntu SMP Wed Sep 24 19:49:16 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
 
- java version "1.6.0_33"
OpenJDK Runtime Environment (IcedTea6 1.13.5) (6b33-1.13.5-1ubuntu0.12.04)
OpenJDK 64-Bit Server VM (build 23.25-b01, mixed mode)

- gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5)

- Apache Maven 3.2.3 (33f8c3e1027c3ddde99d3cdebad2656a31e8fdf4; 2014-08-11T22:58:10+02:00)

**Comment by xerial** [comment]
Let me close this ticket since CFLAGS has already moved to the right position.
