### ISSUE TITLE
Release with SQLite 3.35.5

### ISSUE THREAD

**Issue by lasselindqvist** [xerial/sqlite-jdbc#600]
3.35.0 contained many new features, including math functions and RETURNING clause, which is really useful.
3.35.5 is the latest fix release after that.
Would be nice to release this with 3.35.5 bundled.

Release notes: https://www.sqlite.org/releaselog/3_35_5.html

**Comment by xerial** [comment]
done. I've confirmed RETURNING close works as expected

**Comment by 2938137849** [comment]
want the RETURNING clause. it is really useful
