### ISSUE TITLE
GetObject function and other functions in JDBC4ResultSet class are not implemented

### ISSUE THREAD

**Issue by ACCia** [xerial/sqlite-jdbc#601]
GetObject function and other functions in JDBC4ResultSet class are not implemented
![image](https://user-images.githubusercontent.com/19482891/116502598-87d8aa00-a8e6-11eb-89be-8c83eca6f371.png)

**Comment by gotson** [comment]
Can you provide more details on this?

**Comment by gotson** [comment]
From the Javadoc:
> At a minimum, an implementation must support the conversions defined in Appendix B, Table B-3 and conversion of appropriate user defined SQL types to a Java type which implements SQLData, or Struct. Additional conversions may be supported and are vendor defined.

I found the table mentioned in the JDBC 4.2 specification:

<img width="650" alt="image" src="https://user-images.githubusercontent.com/2139133/189801065-90ad1f39-78da-44c8-afc8-e2c2986532a6.png">
<img width="658" alt="image" src="https://user-images.githubusercontent.com/2139133/189801083-406014cd-8853-4345-9a51-4f7bae04b479.png">
<img width="646" alt="image" src="https://user-images.githubusercontent.com/2139133/189801094-4e06bf00-ac78-409c-8261-a7d0646031f8.png">

**Comment by ACCia** [comment]
Thank you for your response. Yes, we need to support specifications up to 4.0

**Comment by gotson** [comment]
> Thank you for your response. Yes, we need to support specifications up to 4.0

4.2 actually, which is what was introduced in Java 8
