### ISSUE TITLE
Possible to include decimal.c In Build?

### ISSUE THREAD

**Issue by austinarbor** [xerial/sqlite-jdbc#602]
Hello,
Would it be possible to include decimal.c in the compiled distribution? This enables arbitrary precision calculation using `decimal_add`, `decimal_sum`, etc  (see section 2.2 [here](https://www.sqlite.org/floatingpoint.html) ).  This extension is already included by default in the CLI

Thanks!

**Comment by austinarbor** [comment]
I tried including `decimal.c` in `src/main/ext` and I see it being included in the amalgation, however, I am still not able to use the extension's functions. Any ideas?

**Comment by austinarbor** [comment]
Was able to get help from sqlite forums https://sqlite.org/forum/forumpost/05982069ea to get things working

**Comment by gotson** [comment]
Closing this as it seems resolved.

**Comment by austinarbor** [comment]
@gotson its not resolved, I need to do a custom build to include the extension. I would like the extension included by default

**Comment by gotson** [comment]
We won't include every possible extension. If you can build with the extension on your side that should be sufficient for your use case.

**Comment by austinarbor** [comment]
@gotson now that I am on Mac ARM M1, I can't really do this process anymore without paying for CI since many of the builds require x86. As I mentioned in my first comment, this extension is already included in the sqlite CLI by default so it would be helpful to include here as well

**Comment by gotson** [comment]
> this extension is already included in the sqlite CLI by default so it would be helpful to include here as well

we don't include everything that is in the CLI AFAIK
