### ISSUE TITLE
Instant Support

### ISSUE THREAD

**Issue by dkfellows** [xerial/sqlite-jdbc#607]
It would be really nice if there was built-in support for the `java.time.Instant` type of Java 8, as that's a better match for what SQLite thinks of as timestamps (often Unix epoch seconds) than `java.util.Date`. It should, of course, Just Work&trade; for values passed to prepared statements, but it would be entirely acceptable to have it be something that has to be turned on for retrieval from result sets.

**Comment by gotson** [comment]
Is that part of JDBC, or would you expect the driver to perform the conversion?

**Comment by gotson** [comment]
Closing this as no feedback was received.
