### ISSUE TITLE
error: implicit declaration of function 'RegisterExtensionFunctions' is invalid in C99

### ISSUE THREAD

**Issue by guangwei-qiao** [xerial/sqlite-jdbc#610]
when I run makefile, one error ocured, log snippet as below:

target/sqlite-3.32.3-Mac-x86_64/sqlite3.c:163692:48: error: implicit declaration
      of function 'RegisterExtensionFunctions' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
  if(!db->mallocFailed && rc==SQLITE_OK){ rc = RegisterExtensionFunctions(db); }
                                               ^
1 error generated.

**Comment by gotson** [comment]
I don't think this error is blocking in any way. I've seen it or a variation of it in almost every compilation of the native lib to various platform.
