### ISSUE TITLE
Doesn't support JDBC outer joins?

### ISSUE THREAD

**Issue by Erhannis** [xerial/sqlite-jdbc#611]
Ubuntu 20.04.2 LTS
Java 8
sqlite-jdbc 3.34.0
org.eclipse.persistence.jpa (eclipselink) 3.0.1

I have a class `PostCreated`, which has a field of
```java
  @ElementCollection
  public Set<Handle> OPs;
```

And `Handle` is:
```java
@Embeddable
public class Handle implements Serializable {
  public String value;

  // ... bunch of constructors and equals/hash/toString methods ...
}
```
When I run the following JPQL query:
```
select pc.OPs from PostCreated pc
```
I expect a list of lists of `Handle`s, but instead I get this error:
```
jakarta.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 3.0.1.v202104070723): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (unrecognized token: "{")
Error Code: 1
Call: SELECT t0.VALUE FROM {oj EVENT t1 LEFT OUTER JOIN PostCreated_OPS t0 ON (t0.eventHandle = t1.eventHandle)}, POSTCREATED t3, POSTEVENT t2 WHERE (((t3.eventHandle = t1.eventHandle) AND ((t2.eventHandle = t1.eventHandle) AND (t2.eventHandle = t1.eventHandle))) AND (t1.DTYPE = ?))
	bind => [1 parameter bound]
Query: ReportQuery(referenceClass=PostCreated sql="SELECT t0.VALUE FROM {oj EVENT t1 LEFT OUTER JOIN PostCreated_OPS t0 ON (t0.eventHandle = t1.eventHandle)}, POSTCREATED t3, POSTEVENT t2 WHERE (((t3.eventHandle = t1.eventHandle) AND ((t2.eventHandle = t1.eventHandle) AND (t2.eventHandle = t1.eventHandle))) AND (t1.DTYPE = ?))")
```
It looks like "{" of "{oj" is causing an SQLiteException to be thrown.

[This link](https://stackoverflow.com/questions/37190529/jpa-criteria-join-what-does-oj-mean-in-sql) says `{oj ... }` is part of the JDBC spec, and is an outer join, and that "Drivers are expected to translate this to the database specific SQL."  This suggests that it's `sqlite-jdbc` causing the exception to be thrown, and does not support this syntax.  Is that true?  I believe this to be a bug, if the SO post is correct.

**Comment by lasselindqvist** [comment]
I think it is unlikely this escape syntax will be supported in Sqlite JDBC driver anytime soon, if ever.
EclipseLink does not support Sqlite (https://wiki.eclipse.org/EclipseLink/FAQ/JPA#What_databases_are_supported.3F)
and thus the problem seems to come from the default behavior in shouldUseJDBCOuterJoinSyntax (https://github.com/eclipse-ee4j/eclipselink/blob/master/foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/DatabasePlatform.java#L2349)
Consider trying to add some SQLite support to Eclipselink (https://github.com/eclipse-ee4j/eclipselink/issues?q=is%3Aissue+is%3Aopen+sqlite)?

**Comment by Erhannis** [comment]
Hmm, ok.  From the description, it still sounds like `{oj ... }` is part of JDBC, not EclipseLink, so it still seems to me like technically a Sqlite JDBC bug, but I'm not super clear on the details, so, whatever, I guess.

In the meantime, I've figured out the following workaround:
Rather than e.g.
`select pc.handle, pc.OPs from PostCreated pc`
do e.g.
`select pc.handle, op from PostCreated pc JOIN pc.OPs op`

**Comment by lasselindqvist** [comment]
You are right, it is part of JDBC as and thus a bug/missing feature. But I think it is unlikely to be solved here in near future, so it might be better to add the workaround to EclipseLink, like it has been added for many other JDBC drivers.
(Personally I think the whole escape syntax being in the JDBC specs is a mistake)

**Comment by Erhannis** [comment]
Makes sense.  Thanks
