### ISSUE TITLE
JDBC4Connection not JDBC-compliant

### ISSUE THREAD

**Issue by doe300** [xerial/sqlite-jdbc#62]
The org.sqlite.jdbc4.JDBC4Connection returns null for all the unsupported features, like XML, CLOB, BLOB, ....
The documentation for [java.sql.Connection](http://docs.oracle.com/javase/8/docs/api/java/sql/Connection.html#createSQLXML--) specifies, that these methods should throw **SQLFeatureNotSupportedException** instead of returning *null*.

**Comment by andyjefferson** [comment]
Pull request caters for those. There are likely methods in JDBC4PreparedStatement that similarly need an exception throwing rather than no-op. But then anyone can fork and provide a pull request to those in the same way I just did

**Comment by xerial** [comment]
Thanks for the fix!
