### ISSUE TITLE
sqlite-jdbc-*.jar can't support aix system

### ISSUE THREAD

**Issue by xiejie100000** [xerial/sqlite-jdbc#626]
No native library found for **os.name=AIX, os.arch=ppc64**. Details are as follows:
_Caused by: java.lang.Exception: No native library is found for os.name=AIX and os.arch=ppc64. path=/org/sqlite/native/AIX/ppc64 at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:335) at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:64) at org.sqlite.core.NativeDB.load(NativeDB.java:63) at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:235)_

### Questions are as follows:
1. Is the file path **/native/AIX/ppc64/libsqlitejdbc.so?
2. Could you please tell me how I compile SQLite to get  libsqlitejdbc.so?

Thanks vevy much~

**Comment by xiejie100000** [comment]
![image](https://user-images.githubusercontent.com/9943684/126040230-f8205672-da75-401b-a3a9-cc94a6fad896.png)

**Comment by xiejie100000** [comment]
Please help me. Thanks

**Comment by michael-o** [comment]
This is a dup of #588.
