### ISSUE TITLE
Some of new math function are missing

### ISSUE THREAD

**Issue by Tapac** [xerial/sqlite-jdbc#633]
Since [SQLite 3.35.0](https://www.sqlite.org/draft/releaselog/3_35_0.html) version there should be new math functions provided but  some of them are unsupported by Xerial implementation:
- [ceiling](https://www.sqlite.org/draft/lang_mathfunc.html#ceil)
- [ln](https://www.sqlite.org/draft/lang_mathfunc.html#ln)
- [log(b,x)](https://www.sqlite.org/draft/lang_mathfunc.html#log)
- [log2](https://www.sqlite.org/draft/lang_mathfunc.html#log2)
- [pow](https://www.sqlite.org/draft/lang_mathfunc.html#pow)
- [trunc](https://www.sqlite.org/draft/lang_mathfunc.html#trunc)

Please consider to add support for those functions.

**Comment by gotson** [comment]
Until now the native library was built by adding `extension-functions.c` (from https://sqlite.org/contrib), which contains some math functions, among others.

If we enable the new math functions it generates a conflict, so we need to adjust that `extension-functions.c` file.

There is one thing we need to be careful about, currently `log(X)` performs the natural logarithm `ln(X)`, but in the new math functions there is a dedicated `ln(X)`, as well as `log10(X)` and `log2(X)`. This will be a breaking change, so i will hold off on that until we release the next major version (3.40.0), and mark that down in the release notes.

**Comment by michael-o** [comment]
Note: This file (https://sqlite.org/contrib/download/extension-functions.c?get=25) is partially obsolete and included in SQLite. It needs to be revised first.

**Comment by michael-o** [comment]
> > Note: This file (https://sqlite.org/contrib/download/extension-functions.c?get=25) is partially obsolete and included in SQLite. It needs to be revised first.
> 
> It's still relevant for functions that are not natively in SQLite, and would still be needed when compiling without `SQLITE_ENABLE_MATH_FUNCTIONS`.

For the diff it makes sense, but why compile with and then add the extensions file?

**Comment by gotson** [comment]
> > > Note: This file (https://sqlite.org/contrib/download/extension-functions.c?get=25) is partially obsolete and included in SQLite. It needs to be revised first.
> > 
> > 
> > It's still relevant for functions that are not natively in SQLite, and would still be needed when compiling without `SQLITE_ENABLE_MATH_FUNCTIONS`.
> 
> For the diff it makes sense, but why compile with and then add the extensions file?

You can see my WIP [here](https://github.com/xerial/sqlite-jdbc/commit/55557293b8bd20ec54f679cac40b675daf400eaa), i've used `#ifndef SQLITE_ENABLE_MATH_FUNCTIONS` to skip stuff we don't need if the math functions will be enabled.
