### ISSUE TITLE
sqlite-jdbc-3.36.0.1.jar can't support mip64 system

### ISSUE THREAD

**Issue by xiaoliying0912** [xerial/sqlite-jdbc#634]
Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Error opening connection] with root cause
java.lang.Exception: No native library found for os.name=Linux, os.arch=mips64el, paths=[/usr/java/packages/lib/mips64el:/lib:/usr/lib]
        at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:389)

**Comment by michael-o** [comment]
dup of #624. Compile yourself.
