### ISSUE TITLE
sqlite with graalvm native image

### ISSUE THREAD

**Issue by budduedgar** [xerial/sqlite-jdbc#635]
I am using sqlite 'org.xerial:sqlite-jdbc:3.36.0.1'  in graalvm native-image using build.gradle ...
the image is created successfully but when i run the application, i get the following error whenever i try to do the database connection.

java.sql.SQLException: Error opening connection
at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:244)
Caused by: java.lang.Exception: No native library is found for os.name=Linux, os.arch=aarch64, path=[]
Any working trick I can use/follow to have a solution to this problem?

**Comment by gotson** [comment]
Did you check #631?

**Comment by budduedgar** [comment]
Thx gotson, I followed that thread (thoroughly though I don't understand clojars),
using  build.gradle . 
```
implementation 'org.xerial:sqlite-jdbc:3.36.0.1'
compileOnly("com.oracle.substratevm:svm:19.2.1")
implementation("org.graalvm.sdk:graal-sdk:21.1.0")
```
and to some degree managed to successfully generate the native image  with the following parameters..
```
"--no-fallback",
"--enable-all-security-services",
"--report-unsupported-elements-at-runtime",
"--initialize-at-build-time=java.sql.DriverManager",
"--initialize-at-build-time=org.sqlite.JDBC",
"--initialize-at-build-time=org.sqlite.core.DB$ProgressObserver",
"--initialize-at-build-time=org.sqlite.core.DB",
"--initialize-at-build-time=org.sqlite.core.NativeDB",
"--initialize-at-build-time=org.sqlite.ProgressHandler",
"--initialize-at-build-time=org.sqlite.Function",
"--initialize-at-build-time=org.sqlite.Function$Aggregate",
"--initialize-at-build-time=org.sqlite.Function$Window"
```
and with the right JNIReflectionClasses.java (as shown in the thread)..

My only problem just occurs at runtime when the system is to make the connection... when the system fails to load the sqlitejdbc.so library ...

**Comment by gotson** [comment]
Maybe @ericdallo can give you some advice, he managed to build this into a graalvm project.

**Comment by ericdallo** [comment]
Yep, good news, #631 was merged, this means you don't need to do anything more if using the sqlite with those changes, but we need a new release of sqlite-jdbc.
WDYT @xerial can we have a new minor release with that change?

**Comment by budduedgar** [comment]
I am just stampeded now, any available patch I can apply as we wait for the another release of sqlite-jdbc?.. 
 @xerial, @ericdallo

**Comment by ericdallo** [comment]
@budduedgar, until the release, you can use the graal configurations from [this project](https://github.com/ericdallo/sqlite-graalvm-sample/tree/master/resources/META-INF/native-image/sqlite-graalvm-sample/sqlite-graalvm-sample) and it should work.

**Comment by budduedgar** [comment]
Caused by: java.lang.Exception: No native library found for os.name=Linux, os.arch=aarch64, paths=[/org/sqlite/native/Linux/aarch64]

**Comment by gotson** [comment]
@budduedgar is this still a problem?

**Comment by gotson** [comment]
Closing this as no feedback was received.
