### ISSUE TITLE
(amd64) JVM crashes on FreeBSD (java/openjdk16)

### ISSUE THREAD

**Issue by andrew121410** [xerial/sqlite-jdbc#646]
When running my Minecraft server the JVM crashes due to SQLite-JDBC I suppose. I said suppose because that's what someone said on FreeBSD bugzilla. I'm not a very technical person lol so you gotta bare with me.

The SQLite version used is 3.34.0

Command used to start the Minecraft server: -Xms512m -Xmx3G Server.jar --nogui
Host: Intel(R) Core(TM) i3-2120 CPU @ 3.30GHz amd64, 4 cores, 11G, FreeBSD 13.0-RELEASE

[hs_err_pid3452.log](https://github.com/xerial/sqlite-jdbc/files/7024699/hs_err_pid3452.log)

Bug report for java/openjdk16 port that I made on the FreeBSD bugzilla website: [The report](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=257962)

**Comment by gotson** [comment]
The bundled freebsd x86_64 is 5 years old, you may need to wait for the next release, which will have newly compiled freebsd native libs bundled.

**Comment by michael-o** [comment]
https://github.com/xerial/sqlite-jdbc/pull/494#issuecomment-643482994
Compile yourself, straight forward and retry. I have modified this driver recently to load from `LD_LIBRARY_PATH` . The JNI shim will dynamically link against libsqlite and avoid any amalgamation. Thus, if SQLite in FreeBSD is updated, you are uptodate too.

**Comment by andrew121410** [comment]
Alrighty, thanks!
