### ISSUE TITLE
[IO performance] setDefaultUseCaches(false) impacts all URL connections

### ISSUE THREAD

**Issue by gwenn** [xerial/sqlite-jdbc#656]
Using [setDefaultUseCaches(false)](https://github.com/xerial/sqlite-jdbc/blob/master/src/main/java/org/sqlite/SQLiteJDBCLoader.java#L276) impacts all URL connections.
Because [defaultUseCaches](https://github.com/openjdk/jdk/blob/739769c8fc4b496f08a92225a12d07414537b6c0/src/java.base/share/classes/java/net/URLConnection.java#L226) is static (see [setDefaultUseCaches](https://github.com/openjdk/jdk/blob/739769c8fc4b496f08a92225a12d07414537b6c0/src/java.base/share/classes/java/net/URLConnection.java#L1064) implementation).
Maybe you should use [setUseCaches](https://github.com/openjdk/jdk/blob/739769c8fc4b496f08a92225a12d07414537b6c0/src/java.base/share/classes/java/net/URLConnection.java#L1000) instead.

For example, after `setDefaultUseCaches(false)`, each time a new class is loaded from a signed JAR, [initializeVerifier](https://github.com/openjdk/jdk/blob/c36755dedf1a0d7ce0aeadd401e0c70ff84185e7/src/java.base/share/classes/java/util/jar/JarFile.java#L738) is recomputed.

Regards.

**Comment by gotson** [comment]
FYI this was done as part of https://github.com/xerial/sqlite-jdbc/pull/578 IIRC

**Comment by AuroraLS3** [comment]
`setDefaultUseCaches(false)` causes class loading to fail & crash in some Minecraft server implementations since many use URLClassLoader for loading plugins/mods

**Comment by gotson** [comment]
Anyone willing to submit a PR for this?

**Comment by AuroraLS3** [comment]
Opened a PR.

**Comment by gotson** [comment]
This is available in the latest snapshot, please give it a try.
