### ISSUE TITLE
The org/sqlite/native/DragonFlyBSD/x86_64/libsqlitejdbc.so is still exist in sqlite-jdbc-3.36.0.3.jar

### ISSUE THREAD

**Issue by myfirenze** [xerial/sqlite-jdbc#663]
The org/sqlite/native/DragonFlyBSD/x86_64/libsqlitejdbc.so is still exist in sqlite-jdbc-3.36.0.3.jar, although it has been deleted from the source code 
[#640](https://github.com/xerial/sqlite-jdbc/pull/640)  
[#641](https://github.com/xerial/sqlite-jdbc/pull/641)
 
 
![image](https://user-images.githubusercontent.com/37723136/133063452-289daa49-5155-48cb-aa4a-6cb45dc77515.png)

**Comment by gotson** [comment]
Someone didn't run `mvn clean` before releasing? 🙈

**Comment by fireflo** [comment]
When is the next release planned? Thanks!

**Comment by zionjo89757** [comment]
It would be good to release a new version of the jdbc driver with deleted this file libsqlitejdbc.so. Thanks!

**Comment by gotson** [comment]
We are working to automate releases from CI, which should fix this.

**Comment by gotson** [comment]
Can you check the latest snapshot to see if that's resolved?

**Comment by gotson** [comment]
Resolved in `3.39.2.0`
