### ISSUE TITLE
Publish snapshot from github action

### ISSUE THREAD

**Issue by gotson** [xerial/sqlite-jdbc#668]
Hi @xerial,

Would you be interested in having github action automatically build and publish the snapshots to ~~maven central~~ sonatype?

I was checking the snapshot repo and some versions are missing, which makes me think that it's done manually.

I could submit a PR, but you would also need to add some secrets into the repo for this to work.

**Comment by michael-o** [comment]
Snapshots to Maven Central? I guess you mess up here something...

**Comment by gotson** [comment]
I meant https://oss.sonatype.org/content/repositories/snapshots/org/xerial/sqlite-jdbc/

**Comment by michael-o** [comment]
> 
> 
> I meant https://oss.sonatype.org/content/repositories/snapshots/org/xerial/sqlite-jdbc/

This is Sonatype OSS Repository Hosting. There is also https://repository.sonatype.org/. Don't confuse.

**Comment by gotson** [comment]
> > I meant https://oss.sonatype.org/content/repositories/snapshots/org/xerial/sqlite-jdbc/
> 
> This is Sonatype OSS Repository Hosting. There is also https://repository.sonatype.org/. Don't confuse.

The link I provided is the one from the Readme. Not sure what's confusing you.

**Comment by xerial** [comment]
@gotson Yes. In some of my OSS projects, a snapshot version is deployed to Sonatype for each master branch commit. An example workflow https://github.com/wvlet/airframe/blob/master/.github/workflows/snapshot.yml

It would be useful for early adopters :)

**Comment by xerial** [comment]
I'll add SONATYPE_USER, SONATYPE_PASSWORD secretes later :)
