### ISSUE TITLE
Most pragmas cannot be set with `SQLiteConfig(Properties)`

### ISSUE THREAD

**Issue by soc** [xerial/sqlite-jdbc#669]
While `SQLiteConfig.Pragma` lists dozens of possible values, `SQLiteConfig(Properties)` reads and applies only a handful of those pragmas.

More specifically, `"case_sensitive_like" = true` cannot be set via properties, which is very unfortunate.

Is this intentional?

Background: the alternative of calling `SQLiteConfig#enableCaseSensitiveLike` is rather difficult if you also have a connection pooling library and perhaps some abstraction that supports more than one database.

**Comment by soc** [comment]
@xerial @gotson would a PR that added general support for setting pragmas with properties be accepted?

**Comment by gotson** [comment]
My understanding is that it's applied all right.

All the pragma that were not processed before are processed [here](https://github.com/xerial/sqlite-jdbc/blob/1481bf24e8774d2022bd9f1a086c229dcddb6d8d/src/main/java/org/sqlite/SQLiteConfig.java#L212).

**Comment by gotson** [comment]
Closing this as no feedback was received.
