### ISSUE TITLE
Does sqlite-jdbc supports the `file:memdb1?mode=memory` DB URL format?

### ISSUE THREAD

**Issue by guizmaii** [xerial/sqlite-jdbc#676]
In http://www.sqlite.org/c3ref/enable_shared_cache.html, it is described that we can create an in-memory SQLite instance by defining the DB URL in three ways: 
  1. `:memory:`
  2. `file::memory:`
  3. `file:memdb1?mode=memory`
  
Does this lib support the second and third ways? I tried it and it creates files on my system so doesn't seem to work.

**Comment by gotson** [comment]
Seems like it's covered by tests: https://github.com/xerial/sqlite-jdbc/blob/3d04d7df0c89240add2c92189adb30b6cb7e6ae0/src/test/java/org/sqlite/ConnectionTest.java#L282

**Comment by gotson** [comment]
> @gotson Why is it creating files on my computer when I run my test with this configuration?

when you run the test i have pointed at, or some test in your own code?

**Comment by guizmaii** [comment]
> or some test in your own code?

My code
