### ISSUE TITLE
JVM crash due to sqllite jdbc 3.36.0.3

### ISSUE THREAD

**Issue by zaidsultan** [xerial/sqlite-jdbc#680]
Hello, The JVM has crashed multiple times due to sqlite jdbc latest version 3.36.0.3. Please check the crash log.
[hs_err_pid54421.log](https://github.com/xerial/sqlite-jdbc/files/7375931/hs_err_pid54421.log)

**Comment by pyckle** [comment]
Hey. I see that the seg fault happened in the free native methods. Is it possible that you have a thread trying to close a prepared statement at the same time another is closing a connection? This could result in a double free (and subsequent seg fault)

See: https://github.com/xerial/sqlite-jdbc/issues/509 and https://github.com/xerial/sqlite-jdbc/pull/685

**Comment by gotson** [comment]
@zaidsultan can you try the latest snapshot as it contains the fix from #685

**Comment by gotson** [comment]
Should be closed by #685, released as part of `3.39.2.0`. I will be closing this, please comment if the problem happens again on `3.39.2.0`.
