### ISSUE TITLE
SQL query length default changed in 3.36

### ISSUE THREAD

**Issue by kanishkachat** [xerial/sqlite-jdbc#681]
Hi,
In SQLite 3.36, the default max SQL length has regressed from 1,000,000,000 bytes --> 1073741824 bytes

This was introduced in https://github.com/xerial/sqlite-jdbc/pull/568/commits/57d597ef21e8e3d613e5c625f01b45b6bd1ca1de

I believe we may have picked up this limit from SQLite documentation which states it as so: https://www.sqlite.org/rescode.html#toobig , however the real limit is actually larger and documented here: https://www.sqlite.org/limits.html#max_sql_length

I was able to validate the same in SQLite code as well: https://sqlite.org/src/file?name=src/sqliteLimit.h&ci=trunk

We can get around this by setting the limit via the SQLiteConfig, so not blocking in any manner. This was an FYI for this behavior.

Getting around it: 
```
 SQLITE_CONFIG.setPragma(SQLiteConfig.Pragma.LIMIT_SQL_LENGTH, "1000000000");
```

Regards,
Kanishka

**Comment by gotson** [comment]
The defaults in [the driver](https://github.com/xerial/sqlite-jdbc/blob/1481bf24e8774d2022bd9f1a086c229dcddb6d8d/src/main/java/org/sqlite/SQLiteConfig.java#L46) are the same as the one in SQLite.

**Comment by mrckzgl** [comment]
I've come across the same issue and was glad to find this issue towards getting the cuase of my problem.
What I wonder is the following. @gotson you write:

> The defaults in [the driver](https://github.com/xerial/sqlite-jdbc/blob/1481bf24e8774d2022bd9f1a086c229dcddb6d8d/src/main/java/org/sqlite/SQLiteConfig.java#L46) are the same as the one in SQLite.

But I am unable to find any mention of the `DEFAULT_MAX_SQL_LENGTH = 1000000` 1M bytes default max sql statement length in sqlite. The [docs](https://www.sqlite.org/limits.html) you refer to only mention this:
```
Maximum Length Of An SQL Statement

The maximum number of bytes in the text of an SQL statement is limited to SQLITE_MAX_SQL_LENGTH which defaults to 1,000,000,000.

If an SQL statement is limited to be a million bytes in length, then obviously you will not be able to insert multi-million byte strings by embedding them as literals inside of INSERT statements. But you should not do that anyway. Use host [parameters](https://www.sqlite.org/lang_expr.html#varparam) for your data. Prepare short SQL statements like this:

    INSERT INTO tab1 VALUES(?,?,?); 

Then use the [sqlite3_bind_XXXX()](https://www.sqlite.org/c3ref/bind_blob.html) functions to bind your large string values to the SQL statement. The use of binding obviates the need to escape quote characters in the string, reducing the risk of SQL injection attacks. It also runs faster since the large string does not need to be parsed or copied as much.

The maximum length of an SQL statement can be lowered at run-time using the [sqlite3_limit](https://www.sqlite.org/c3ref/limit.html)(db,[SQLITE_LIMIT_SQL_LENGTH](https://www.sqlite.org/c3ref/c_limit_attached.html#sqlitelimitsqllength),size) interface.
```
This mentions a default of 1G. So I wonder where the 1M default actually comes from? Is there any documentation of this in sqlite? If not, this may also be an issue for the sqlite docs. Well, reading a bit deeper an odd mention is this sentence

> If an SQL statement is limited to be a million bytes in length, [...]

but this also does not state that there *is* a default limit of 1M bytes...
