### ISSUE TITLE
Inconsistency between autoCommit property and SQLite transaction status

### ISSUE THREAD

**Issue by dkfellows** [xerial/sqlite-jdbc#683]
If (using 3.36.0.3, platform independent code) I have:
```java
connection.setAutoCommit(false);
```
in my code and that throws an exception (e.g., because the database is locked), it is then not safe to retry calling `setAutoCommit` again using that connection. This is because the state of the auto-commit flag is set _before_ finding out whether the database engine itself is happy with commencing a transaction, and attempting to retry the operation afterwards is a no-op (supposedly the DB connection is not in auto-commit mode) despite no transaction actually being open. This is not nice at all; the auto-commit flag should only actually be set to false if a transaction is genuinely open.

Once the system is in an inconsistent state, the only recovery strategy is to completely throw away the connection as instructions to get the state consistent also throw and things just get weird and crazy. That's highly disruptive to the connection/thread pooling system I'm using. Note that this can interact really strangely with timeouts to produce bugs that are insanely difficult to hunt down because they're parachuted into other parts of the code that expect the database connections to be in a consistent state!

**Comment by dkfellows** [comment]
It turns out this is more of an issue with immediate transactions, and changing the transaction type to deferred reduces the frequency of problems below a level at which it is acceptable to have for production code, but even so; the commit mode as understood by SQLite itself and as understood by the driver absolutely should match to prevent chaos.

**Comment by gotson** [comment]
https://github.com/xerial/sqlite-jdbc/blob/1481bf24e8774d2022bd9f1a086c229dcddb6d8d/src/main/java/org/sqlite/SQLiteConnection.java#L342-L345

Do you mean we should perform the `db.exec` first, then update the `connectionConfig.setAutoCommit(ac)` ?

**Comment by gotson** [comment]
Closing this as no feedback was received.
