### ISSUE TITLE
Memory leak when attaching busy handlers

### ISSUE THREAD

**Issue by wassinki** [xerial/sqlite-jdbc#684]
We discovered a memory leak when a busy handler is attached. The code attached shows the way to reproduce it. When we attach the mission control to the vm and count the number of instances of the busyhandlers, it is equal to the number of times the while loop has been executed.

Because the busy handler is detached every time, I expected the number of instances of  both the busyhandler to be at most 1. Am I doing something wrong, or is it really a bug?
[Tester.java.txt](https://github.com/xerial/sqlite-jdbc/files/7473838/Tester.java.txt)

**Comment by wassinki** [comment]
I checked a heap dump in jvisualvm. This one tells that the busy handlers are refrenced by JNI global (native code).

**Comment by pyckle** [comment]
Please see https://github.com/xerial/sqlite-jdbc/pull/707 - I think I fixed this bug.

**Comment by gotson** [comment]
Closing this as #707 has been merged and is available in the latest SNAPSHOT.
