### ISSUE TITLE
Unable to run spatiaLite extension

### ISSUE THREAD

**Issue by meilleureVie** [xerial/sqlite-jdbc#690]
How to load spatiaLite extension for spatial query ?

**Comment by Iceforgedmvp** [comment]
It works like this:

1. At first, you have to enable the function load_extension(..):
- If you use DriverManager: Set up SQLiteConfig as described under [Configure Connections](https://github.com/xerial/sqlite-jdbc/blob/master/Usage.md#configure-connections) and call `config.enableLoadExtension(true)`
- If you use an connection pool like Hikari: Make sure you set the following property on the Properties object that you pass to the pool:
`config.setProperty("dataSource.enable_load_extension", Boolean.toString(true));`

2. Execute `SELECT load_extension('mod_spatialite')` (replace 'mod_spatiallite' with the actual name of the library. File extension can be omitted).

Further reading:
https://sqlite.org/loadext.html
http://www.gaia-gis.it/gaia-sins/splite-doxy-5.0.1/index.html

**Comment by gotson** [comment]
@meilleureVie can this be closed?
