### ISSUE TITLE
MetaData.getImportedKeys fails if table not found

### ISSUE THREAD

**Issue by rjahn** [xerial/sqlite-jdbc#693]
If you try to getImportedKeys from a table with wrong referenced table, the method will fail with table not found exception.

The table definition:

```
CREATE TABLE "server" (
	"id"	INTEGER NOT NULL,
	"user_id"	INTEGER NOT NULL,
	"servergroup_id"	INTEGER NOT NULL,
	"name"	VARCHAR(128) NOT NULL,
	"host"	VARCHAR(128),
...
	PRIMARY KEY("id"),
	FOREIGN KEY("user_id") REFERENCES "user_old"("id"),
	FOREIGN KEY("servergroup_id") REFERENCES "servergroup"("id")
);
```

The table user_old doesn't exist.

```
java.sql.SQLException: Table not found: 'user_old'
	at org.sqlite.jdbc3.JDBC3DatabaseMetaData$PrimaryKeyFinder.<init>(JDBC3DatabaseMetaData.java:2011)
	at org.sqlite.jdbc3.JDBC3DatabaseMetaData.getImportedKeys(JDBC3DatabaseMetaData.java:1598)
```

The FK is not a primary key.

It's not my table, it's the bundled database of an installed pgAdmin4 6.2 and I can't change the database on my own.

**Comment by gotson** [comment]
Would you know what's the behaviour on other drivers like PostgreSQL / MySQL ? I can't say whether it's a bug or expected.

**Comment by rjahn** [comment]
First, it's possible to get the same configuration in other database - a FK without FK table. In some databases it's easy to create such configuration if you set "wrong" permissions on tables... means the user doesn't have the right to access the FK table...

I didn't test such situations in other DB systems, but I had a similar problem in PostgreSQL and in this case, the driver returned the "wrong key" but had an exception while accessing metadata with this key.

In my opinion: The JDBC driver should return the configured keys, also if it's invalid or don't return invalid keys, but it should not fail.

**Comment by gotson** [comment]
I was checking the Javadoc for `DatabaseMetaData.getImportedKeys` and it says:

> Throws: SQLException – if a database access error occurs

I think you are right, it should not throw an exception in that case.
