### ISSUE TITLE
I have two linux aarch64 system,one success and another is failed.

### ISSUE THREAD

**Issue by xiaoliying0912** [xerial/sqlite-jdbc#695]
use maven version is 3.36.0.3
<dependency>
	<groupId>org.xerial</groupId>
	<artifactId>sqlite-jdbc</artifactId>
	<version>3.36.0.3</version>
</dependency>

Caused by: java.lang.Exception: No native library is found for os.name=Linux and os.arch=aarch64. paths=/org/sqlite/native/Linux/aarch64:/opt/test/:/lib/aarch64-linux-gnu:/usr/lib

who please tell me why?

**Comment by gotson** [comment]
Could it be that one system is using libc and the other musl?

**Comment by ecool2011** [comment]
@xiaoliying0912 Did you solve this issue?

**Comment by gotson** [comment]
Closing this as no feedback was received.
