### ISSUE TITLE
How to change the temporary directory of SQLite JDBC / tmp

### ISSUE THREAD

**Issue by xiaoliying0912** [xerial/sqlite-jdbc#699]

**Comment by xiaoliying0912** [comment]
![image](https://user-images.githubusercontent.com/25734880/146340389-b37c1dc2-06a8-4b31-8242-591b622b9238.png)

**Comment by xiaoliying0912** [comment]
> https://github.com/xerial/sqlite-jdbc#configuration

sudo java -jar -Djava.io.tmpdir=/opt/appfiles/hello  -Dorg.sqlite.tmpdir=/opt/appfiles/hello test.war

**Comment by michael-o** [comment]
@xiaoliying0912 Please stop coding if you aren't able to copy terminal output to this issue. Photo of the screen...

**Comment by ecool2011** [comment]
@xiaoliying0912 I also meet same issue, seems it's SELinuex is enabled??  
If you have slove this issue, can you share your solution for me?
