### ISSUE TITLE
Support for alpine with aarch64

### ISSUE THREAD

**Issue by lavifb** [xerial/sqlite-jdbc#703]
I am trying to run an application that runs inside an alpine container that runs on aarch64 (aws graviton nodes)

I am getting this exception:
`Caused by: java.lang.Exception: No native library found for os.name=Linux-Alpine, os.arch=aarch64, paths=[/usr/lib/jvm/java-1.8-openjdk/jre/lib/aarch64/server:/usr/lib/jvm/java-1.8-openjdk/jre/lib/aarch64:/usr/lib/jvm/java-1.8-openjdk/jre/../lib/aarch64:/usr/java/packages/lib/aarch64:/lib:/usr/lib]`

It seems that there is support for Linux-Alpine but only for x86. Could we add Linux-Alpine aarch64 as a target?

**Comment by gotson** [comment]
I see dockcross now has musl versions of most of the arm images, I will try those and see if I can make it work.

**Comment by gotson** [comment]
I created a PR to fix this.

Since xerial is on leave and won't merge this soon you could try to build it yourself. Just clone my PR, and run `mvn package`.

**Comment by lavifb** [comment]
Wow thanks for the quick response here. I'm not working over the holiday but I'll try it out next week.

**Comment by lavifb** [comment]
This looks to be working for me. Thank you very much!
