### ISSUE TITLE
add support for Android/aarch64

### ISSUE THREAD

**Issue by Hax4us** [xerial/sqlite-jdbc#709]

**Comment by gotson** [comment]
It's already been added in #662

**Comment by Hax4us** [comment]
but i am unable to find it in `jar` file.

![IMG_20220107_153358](https://user-images.githubusercontent.com/30441647/148527745-cd2aca9c-4d45-4d40-9708-dc5c5a50c273.jpg)

**Comment by gotson** [comment]
No release has been done yet with those changes.

**Comment by gotson** [comment]
This is available in the latest snapshot, please give it a try.

**Comment by gotson** [comment]
Released as part of `3.39.2.0`
