### ISSUE TITLE
The REGEXP is used to access a user defined function. I got some code from a stackoverflow answer, as below. I just found this minutes ago, and haven't yet used the regex search (middle of refactoring), but it did get rid of the exception.

### ISSUE THREAD

**Issue by danielfcastro** [xerial/sqlite-jdbc#718]
The REGEXP is used to access a user defined function. I got some code from a stackoverflow answer, as below. I just found this minutes ago, and haven't yet used the regex search (middle of refactoring), but it did get rid of the exception.

http://stackoverflow.com/questions/25786996/sqlite-query-with-regex

``` java
Function.create(connection, "REGEXP", new Function() {
                    @Override
                    protected void xFunc() throws SQLException {
                        String expression = value_text(0);
                        String value = value_text(1);
                        if (value == null)
                            value = "";

                        Pattern pattern=Pattern.compile(expression);
                        result(pattern.matcher(value).find() ? 1 : 0);
                    }
                });
```

_Originally posted by @everbeek in https://github.com/xerial/sqlite-jdbc/issues/60#issuecomment-152668620_

**Comment by gotson** [comment]
You define `public static void createREGEXP(Connection connection) throws SQLException` but it's never called, at least in the code you pasted.

**Comment by gotson** [comment]
You can also check https://github.com/xerial/sqlite-jdbc/issues/429#issuecomment-934354138

Since you are using Spring that should help you.

**Comment by gotson** [comment]
Closing this, please reopen if needed.
