### ISSUE TITLE
JDBC4ResultSet.getClob() should return null if the data is null

### ISSUE THREAD

**Issue by lukaseder** [xerial/sqlite-jdbc#722]
The `JDBC4ResultSet::getClob` methods never return `null`, even when the `ResultSet`'s string data is `null`:

https://github.com/xerial/sqlite-jdbc/blob/3d04d7df0c89240add2c92189adb30b6cb7e6ae0/src/main/java/org/sqlite/jdbc4/JDBC4ResultSet.java#L378-L384

That's quite contrary to the expectation, or the behaviour of any other JDBC driver I've seen so far. The expectation is for the method to return a `null` value. The `Clob` API doesn't have any good ways to check for content `null`-ness. The only thing that could be done is to check one of the stream methods (e.g. `Clob::getCharacterStream`) if that returns `null`.

**Comment by gotson** [comment]
> The expectation is for the method to return a `null` value

Hi Lukas, would you be able to share a bit more on that expectation? The ResultSet interface doesn't mention anything.

I know you have worked with pretty much all the drivers out there, but it might be good to share a bit more if you can.

**Comment by lukaseder** [comment]
Indeed, neither the `ResultSet` Javadoc, nor the JDBC spec are explicit about this, regrettably. Perhaps take the `CallableStatement::getClob` Javadoc as an inspiration? I don't see a reason why the two behaviours should be different in those cases. It says: 

> the parameter value as a Clob object in the Java programming language. If the value was SQL NULL, thevalue null is returned.

Think about it this way: All non-primitive type returning `ResultSet.getXYZ()` methods return either a `null` value meaning SQL NULL, or some non-null value meaning SQL NOT NULL. Except this particular `JDBC4ResultSet.getClob()` method, which never returns `null` in sqlite-jdbc's case. So, how can we detect whether the `Clob` value had been null?

We could call `ResultSet::wasNull`, of course, but that seems weird, because the simplest way for a `ResultSet` to indicate that a returned reference type was `null` is simply to return `null`. We could call some derived method, like `Clob::getCharacterStream`, but that seems kind of clever. If the `java.sql.Clob` API (and the other resource wrappers, including `Blob`, `Array`, `SQLXML`) were meant to contain SQL `NULL` values, then there would be a `Clob::isNull` method, in my opinion.
