### ISSUE TITLE
Does 3.36.0.3  support Java 17 and above ?

### ISSUE THREAD

**Issue by goxr3plus** [xerial/sqlite-jdbc#729]
Hello we just migrated our [project-XR3Player](https://github.com/goxr3plus/XR3Player) from Java 11  to Java 17+ 

Is [sqlite-jdbc](https://github.com/xerial/sqlite-jdbc) supporting that version ? We got some errors but i don't know if we did something wrong or it doesn't support it.

**Comment by johannespostler** [comment]
We are using it in production with Java 17. No problems specific to Java 17 so far.

**Comment by gotson** [comment]
It's not explicitly supported, I will need to add it in CI to make sure it's working.
