### ISSUE TITLE
impossible to connect my table's details on sqlite studio 3 via netbeans.

### ISSUE THREAD

**Issue by RAMI-spec** [xerial/sqlite-jdbc#730]
I can't find the details of my table on netbeans, which I created on sqlite studio 3, although I connect well to the database via the dedicated driver jdbc:sqlite:C:\Users\pop\Documents\NetBeansProjects\ LoginRegister_2\LogingAccountsDB2.db [ on Default schema]
Can someone help me please?

I thank you very much

**Comment by michael-o** [comment]
Wrong project to ask

**Comment by gotson** [comment]
Please ask on stackoverflow.com or at NetBeans.
