### ISSUE TITLE
Support for `executeLargeUpdate`

### ISSUE THREAD

**Issue by tdudzik** [xerial/sqlite-jdbc#735]
Does `sqlite-jdbc` currently supports `PreparedStatement#executeLargeUpdate`? I'm trying to use Helidon along with SQLite and I'm getting `java.lang.UnsupportedOperationException: executeLargeUpdate not implemented` so I suppose the default implementation of that method is used (which is throwing the exception). I've also browsed the code and it seems this method is not implemented. Are there any plans to do so (or some reasons for which e.g. it's not possible)?

**Comment by gotson** [comment]
I was looking at that, seems like the only difference between the normal and `Large` methods is the return type changing from `int` to `long`.

[This](https://github.com/gotson/sqlite-jdbc/blob/20227527c6b36f6fcb5cc512b625dc2a005bcffe/src/main/java/org/sqlite/jdbc3/JDBC3Statement.java#L94-L94) returns an `int`, we would need to have the `long` equivalent, and it has an impact on JNI [here](https://github.com/gotson/sqlite-jdbc/blob/20227527c6b36f6fcb5cc512b625dc2a005bcffe/src/main/java/org/sqlite/core/NativeDB.c#L773-L773) as we would [need to use](https://www.sqlite.org/c3ref/total_changes.html) `sqlite3_int64 sqlite3_total_changes64(sqlite3*)` instead.
