### ISSUE TITLE
Last pure-java supported version 3.7.2 which doesn't support open a database from Chinese file path

### ISSUE THREAD

**Issue by ecool2011** [xerial/sqlite-jdbc#740]
For example:
 connection = DriverManager.getConnection("jdbc:sqlite:c:\\test\\测试sample.db", prop);

this command will throw out of memory exception.

However,
 connection = DriverManager.getConnection("jdbc:sqlite:c:\\temp\\sqlite\\sample.db", prop);
this commaond is ok.

I think you will answer me why  don't use latest verson?
Exactrally, we have some target servers which run under Loongson CPU (MIPS Arch), and we alreay built the native library for this CPU. However, some special servers has SELinux enabled and cannot be disabled, that cause the app cannot load the native library because the SELinux denied this action.

So we have to conside use the old version 3.7.2 instead, but after many tests, find it doesn't support chinese dabasebase path. 
Can you consider fix it ? or tell me where is wrong so that I can fix it by myself. 

Thanks very much!

**Comment by gotson** [comment]
We only support latest versions.
