### ISSUE TITLE
PreparedStatement setTimestamp() binding broken for TIMESTAMP column in WHERE clause

### ISSUE THREAD

**Issue by barrycaceres** [xerial/sqlite-jdbc#742]
I have a simple SQLite database with a simple table:

```sql
CREATE TABLE IF NOT EXISTS test_timestamp (
        id INTEGER PRIMARY KEY,
        description TEXT, 
        created_on TIMESTAMP NOT NULL DEFAULT (STRFTIME('%Y-%m-%d %H:%M:%f', 'NOW'))
)
```

I populate the table with a single column:
```sql
INSERT INTO test_timestamp (description) VALUES ('test');
```

If I query this table using the query below with a `setTimestamp()` binding, then the WHERE clause matches ZERO rows regardless of how many that match.

```java
      final Calendar UTC_CALENDAR = Calendar.getInstance(TimeZone.getTimeZone("UTC"));
      PreparedStatement ps = conn.prepareStatement(
          "SELECT id, description, created_on FROM test_timestamp WHERE created_on < ?");
      Timestamp timestamp = new Timestamp(System.currentTimeMillis() + 100000L);
      ps.setTimestamp(1, timestamp, UTC_CALENDAR);
      ResultSet rs = ps.executeQuery();  // NO ROWS MATCH QUERY
```

However, if I change the query and use `setString()` binding instead, then the WHERE clause DOES MATCH the appropriate rows:
```java
      final String DATE_TIME_PATTERN = "yyyy-MM-dd HH:mm:ss.SSS";
      final ZoneId UTC_ZONE = ZoneId.of("UTC");
      final DateTimeFormatter DATE_TIME_FORMATTER = DateTimeFormatter.ofPattern(DATE_TIME_PATTERN);

      PreparedStatement ps = conn.prepareStatement(
        "SELECT id, description, created_on FROM test_timestamp "
        + "WHERE created_on < (STRFTIME('%Y-%m-%d %H:%M:%f', ?))");

      Instant instant  = Instant.ofEpochMilli(timestamp.getTime());  // use the exact same time as above

      ZonedDateTime  zonedDateTime   = instant.atZone(UTC_ZONE);

      ps.setString(1, DATE_TIME_FORMATTER.format(zonedDateTime));
      ResultSet rs = ps.executeQuery();  // ALL EXISTING ROWS MATCH
```

This seems like a bug to me.  I have tried `setTimestamp()` with and without the `Calendar` parameter and either way it fails.

I am attaching the code to reproduce the issue.

      

[sqlite-test.zip](https://github.com/xerial/sqlite-jdbc/files/8960350/sqlite-test.zip)

**Comment by chris-mosher** [comment]
You are telling SQLite to compare a TEXT date-time to an INTEGER value when you use setTimestamp, so it converts milliseconds to a string and compares that to your formatted date-time string. That's causing the behavior you see. If you force the driver to use TEXT, like you want, then it works fine. Configure the date_class property like this:

```java
Properties props = new Properties();
props.setProperty("date_class", "text");
conn = DriverManager.getConnection(jdbcUrl, props);
```

Then your test program works as you expect.

**Comment by gotson** [comment]
Seems like this has been answered, closing.
