### ISSUE TITLE
Setting busy_timeout

### ISSUE THREAD

**Issue by calippo** [xerial/sqlite-jdbc#75]
I'm having issues using sqlite with multithreading. In particular I'm receiving a `[SQLITE_BUSY] the database file is locked (database is locked)` error.

I'm using sqlite-jdbc 3.8.11.2 on redhat 6.3.

I'm trying to set busy_timeout with no success. I'm using slick 3.1.0-RC2 for this.
I tried both using a simple query `sqlu"pragma busy_timeout=10000"` and from configuration like:

```
properties {
  busy_timeout=10000
}
```

In both approaches querying sqlite from the same _thread and connection_ I get `busy_timeout=0`
I can successfuly set journal_mode = wal with this approach, I expected it to be the same with busy_timeout.

So I have 2 questions:
1) Is `busy_timeout=0` a reasonable default? 
2) Am I doing something wrong?

**Comment by cpmcdaniel** [comment]
I believe #158 is related. Are you running in a VM?

This may be an old issue, but I believe it is still relevant. We see this quite often in our project.

**Comment by gotson** [comment]
Closing this as it's very old. Comment if necessary.
