### ISSUE TITLE
default support of json1 extension

### ISSUE THREAD

**Issue by PavelPolyakov** [xerial/sqlite-jdbc#76]
Hi,

Are there any plans to integrate json1 extension to the library?
https://www.sqlite.org/json1.html

As I see, some libraries have already done that:
https://github.com/mapbox/node-sqlite3/pull/538

My case is the next, I use 0xDBE, installed the driver from the downloads page: https://bitbucket.org/xerial/sqlite-jdbc/downloads , however the ```json``` functions are not yet there.

Do we have any plans to integrate them? Or it is already somehow possible to use the ```json``` methods?

Regards,

**Comment by gitblit** [comment]
PR #127, which should be merged this month, adds support for the JSON1 extension.

**Comment by gitblit** [comment]
This is supported by default. Release to follow when @xerial is ready but I expect it soon.
