### ISSUE TITLE
JDBC URL for encrypted databases

### ISSUE THREAD

**Issue by wise-coders** [xerial/sqlite-jdbc#773]
I have a Sqlite database encrypted using [SEE](https://sqlite.org/com/see.html) 

Which is the correct URL to access it?
I tried something like :
jdbc:sqlite:/Users/md/test.db?cipher=sqlcipher&legacy=0&kdf_iter=4000&textkey="aes256:pm17fybae"

but it is not working.

**Comment by gotson** [comment]
Did you check https://github.com/xerial/sqlite-jdbc/blob/master/USAGE.md#how-to-use-encrypted-databases ?

**Comment by wise-coders** [comment]
May I ask, where can be found the sqlite_cryption_support.dll file on Mac? Does it work there?

**Comment by gotson** [comment]
SEE ships as native code, you need to build the project yourself with that code.

Check https://github.com/xerial/sqlite-jdbc/issues/530
