### ISSUE TITLE
max attached database increase doesn't work

### ISSUE THREAD

**Issue by mhanna** [xerial/sqlite-jdbc#776]
Recompile the sqlite with max attached database to 125 doesn't work
Using the branch 3.39.2.0, with the default Makefile that includes the option
-DSQLITE_MAX_ATTACHED=125

I still see error of max attached - 10
org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (too many attached databases - max 10)

 - OS: Linux 583b7ecd7230 5.10.76-linuxkit #1 SMP Mon Nov 8 10:21:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
 - sqlite-jdbc version 3.39.2.0

**Comment by gotson** [comment]
Limits are managed at runtime now, not compile time. See https://github.com/xerial/sqlite-jdbc/pull/568#issue-772387173 for details.

**Comment by mhanna** [comment]
Thanks!
