### ISSUE TITLE
I want to know how to set the password and obtain how to encrypt

### ISSUE THREAD

**Issue by liangke21** [xerial/sqlite-jdbc#787]
I want to know how to set the password and obtain how to encrypt

**Comment by gotson** [comment]
Try reading the documentation

**Comment by liangke21** [comment]
> 尝试阅读文档
![DP7HC%J03HYH{% 6G)CXZDG](https://user-images.githubusercontent.com/33193340/190637009-a47bde25-f915-4c1a-9191-50e1e3babf65.jpg)
