### ISSUE TITLE
sqlite memory statistics

### ISSUE THREAD

**Issue by mhanna** [xerial/sqlite-jdbc#798]
I see that sqlite supports sqlite_status function as well memstat extension
https://www.sqlite.org/memstat.html

I'm wondering if there's anyway it can be invoked from the jdbc

**Comment by gotson** [comment]
You would need to compile the loadable extension and load it at runtime, then you could use the virtual table.

**Comment by mhanna** [comment]
I have added the source code as memstat.c to src/main/ext
And recompiled with enabling the sqlite_memstat_...

Assuming that at startup the jdbc will be loading the sqlite native library including its extensions.

**Comment by mhanna** [comment]
I managed to load it in runtime

**Comment by whatify-io** [comment]
@mhanna Can you outline the steps you did to get this working?

**Comment by mhanna** [comment]
1. compile the memstat.c extension for the relevant OS.
2. compile the sqlite-jdbc by enabling -DENABLE_LOAD_EXTENSION -DSQLITE_DEFAULT_MEMSTATUS -DSQLITE_ENABLE_MEMSTATVTAB
3. bundle the compiled extension with the sqlite-jdbc to the relevant os path org/sqlite/native/<OS>/<arch>/<compiled_extension>
4. load the extension at runtime by using select load_extension('path-to-the-compiled-extension')

**Comment by mhanna** [comment]
@whatify-io 

I tried that approach first thing but wasn't able to make it working
