### ISSUE TITLE
Remove use of standard streams - introduce logging framework?

### ISSUE THREAD

**Issue by gotson** [xerial/sqlite-jdbc#802]
The existing code relies of `System.err` and `e.printStackTrace()` to output errors:
- mostly in `SQLiteJDBCLoader`
- there is some usage in `OSInfo`, but this can run as a command line so it should not be a problem
- in some places in `JDBC3DatabaseMetaData`

In some places we also use `DriverManager.println` which seems to be the correct way to print JDBC connection related logs.

I would be enclined to remove the use of standard streams, and use a logging framework instead. Given we support Java 8, SLF4J is probably the best bet, though i noticed they finally released their 2.0 version, which kinda breaks existing apps.

Comments are welcome.

**Comment by michael-o** [comment]
You have basically two options: SLF4J 1.7.x or JUL (the API, not the implementation). Have you checked with other popular JDBC drivers?

**Comment by gotson** [comment]
I think i have read somewhere that JUL before 1.9 was a no-no, but can't remember the details. Would need to investigate further.

**Comment by gotson** [comment]
> Have you checked with other popular JDBC drivers?

- pgjdbc [uses JUL](https://jdbc.postgresql.org/documentation/logging/)
- H2 [uses SLF4J](https://www.h2database.com/html/features.html?highlight=logging&search=logging#other_logging)
- MySQL [uses SLF4J](https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-logging-slf4j.html)

**Comment by gotson** [comment]
> I think i have read somewhere that JUL before 1.9 was a no-no, but can't remember the details. Would need to investigate further.

Actually it's not about JUL, but JDK9 introduced `System.Logger`, which is akin to SLF4J. Some resources i found about it:
- https://renato.athaydes.com/posts/java-system-logging.html
- https://dzone.com/articles/system-logger
- https://stackoverflow.com/questions/11359187/why-not-use-java-util-logging

**Comment by gotson** [comment]
> In some places we also use `DriverManager.println` which seems to be the correct way to print JDBC connection related logs.

I checked on the web and could not find any good source of information about this. It's not used in pgjdbc nor H2 either.

If anyone has some information on that, i am quite interested.
