### ISSUE TITLE
SQLite JDBC: inconsistent internal state when trying to access ResultSetMetaData past reading the last row

### ISSUE THREAD

**Issue by lukaseder** [xerial/sqlite-jdbc#808]
**Describe the bug**

When consuming a `ResultSet` entirely, but before closing it, it is no longer possible to access `ResultSet.getMetaData()` content.

**To Reproduce**

```java
try (Statement s = connection.createStatement();
    ResultSet rs = s.executeQuery("select 1")) {

    rs.next();
    rs.next();
    System.out.println(rs.getMetaData().getColumnCount());
}
```

**Expected behavior**

print 1

**Logs**

```
Exception in thread "main" java.lang.IllegalStateException: SQLite JDBC: inconsistent internal state
	at org.sqlite.core.CoreResultSet.checkCol(CoreResultSet.java:95)
	at org.sqlite.jdbc3.JDBC3ResultSet.getColumnCount(JDBC3ResultSet.java:602)
	at org.jooq.testscripts.JDBC.main(JDBC.java:70)
```

**Environment (please complete the following information):**

 - OS: Microsoft Windows [Version 10.0.22000.1219]
 - CPU architecture: x86_64
 - sqlite-jdbc version: 3.39.4.0

**Additional observations**

The current behaviour is explained by `org.sqlite.jdbc3.JDBC3ResultSet.next()`, see:

```java
        switch (statusCode) {
            case SQLITE_DONE:
                close(); // aggressive closing to avoid writer starvation
                return false;
```

This then resets the `ResultSetMetaData` content, which I think isn't correct. You can argue that `ResultSet::getMetaData` should throw:

> SQLException - if a database access error occurs or this method is called on a closed result set

But I (the user) didn't close the result set. I'm closing it right after in try-with-resources. In fact, this still reproduces the problem:

```java
try (Statement s = connection.createStatement();
    ResultSet rs = s.executeQuery("select 1")) {

    rs.next();
    ResultSetMetaData meta = rs.getMetaData();
    rs.next();
    meta.getColumnCount();
}
```

Despite the fact that `ResultSet::close` says:

> When a ResultSet is closed, any ResultSetMetaData instances that were created by calling the getMetaData method remain accessible.

**Comment by lukaseder** [comment]
Either way, the exception that is thrown is `IllegalStateException`, when it should be at least a `SQLException`

**Comment by gotson** [comment]
Thanks Lukas for the detailed report. I've fixed this and added some tests.

**Comment by lukaseder** [comment]
Thanks a lot!

**Comment by gotson** [comment]
> Thanks a lot!

Well thank you sir, i'm a big fan of jOOQ and use it too, so it comes back to me in the end :)

**Comment by lukaseder** [comment]
Hah, great to hear! :)
