### ISSUE TITLE
Cannot reuse static Statement for second query execution

### ISSUE THREAD

**Issue by lukaseder** [xerial/sqlite-jdbc#809]
**Describe the bug**

A static `Statement` should be reusable for several query executions. It no (longer?) is

**To Reproduce**

```java
try (Statement s = connection.createStatement()) {
    for (int i = 0; i < 2; i++) {
        System.out.println("iteration " + (i + 1));
        System.out.println(s.execute("select 1"));

        try (ResultSet rs = s.getResultSet()) {
            System.out.println(rs.next());
            System.out.println(rs.getInt(1));
            System.out.println(rs.next());
        }

        System.out.println(s.getMoreResults());
        System.out.println(s.getUpdateCount());
    }
}
```

**Expected behavior**

This should print:

```
iteration 1
true
true
1
false
false
-1
iteration 2
true
true
1
false
false
-1
```

But it prints:

```
iteration 1
true
true
1
false
false
-1
iteration 2
true
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.sql.ResultSet.next()" because "rs" is null
	at org.jooq.testscripts.JDBC.main(JDBC.java:71)
```

**Environment (please complete the following information):**

 - OS: Microsoft Windows [Version 10.0.22000.1219]
 - CPU architecture: x86_64
 - sqlite-jdbc version: 3.39.4.0

**Comment by lukaseder** [comment]
This seems to be a regression. With 3.36.0.3, this problem doesn't appear yet

**Comment by lukaseder** [comment]
Probably a regression introduced with https://github.com/xerial/sqlite-jdbc/commit/79365322acfcc871ab33ca703865e4484bc51892 to fix https://github.com/xerial/sqlite-jdbc/issues/458 ?

**Comment by gotson** [comment]
Thanks @lukaseder for the report and the investigation, you were right it's a regression. I have added tests based on your sample and found a way to fix it.

**Comment by gotson** [comment]
@lukaseder if you could test this and #808 with the latest snapshot, that would be awesome. I would like to ship those fixes in the 3.39 version before updating to the recently released 3.40 version of SQLite. Thanks.

**Comment by lukaseder** [comment]
This issue here and #808 seem to have been fixed, thank you. I've noticed a few other regressions related to this issue here, which I thought were related. Will report separate issues shortly.

**Comment by gotson** [comment]
> This issue here and #808 seem to have been fixed, thank you. I've noticed a few other regressions related to this issue here, which I thought were related. Will report separate issues shortly.

good to know, thanks

**Comment by lukaseder** [comment]
Here's one of them: https://github.com/xerial/sqlite-jdbc/issues/810

**Comment by lukaseder** [comment]
And the other one: https://github.com/xerial/sqlite-jdbc/issues/811

**Comment by lukaseder** [comment]
I believe that's all of them, looking at the jOOQ integration test suite. Will be happy to report again on a future snapshot, if you're interested.

**Comment by gotson** [comment]
> I believe that's all of them, looking at the jOOQ integration test suite. Will be happy to report again on a future snapshot, if you're interested.

All closed, a new snapshot was published. I would definitely appreciate if you could retry your test suite on the latest snapshot !

**Comment by lukaseder** [comment]
Can confirm, #810 is also fixed, no new regressions, only https://github.com/xerial/sqlite-jdbc/issues/811 left.

**Comment by gotson** [comment]
> Can confirm, #810 is also fixed, no new regressions, only #811 left.

I fixed #811 too, maybe the snapshot takes time to update.

**Comment by gotson** [comment]
No worries, I'll cut a release then

**Comment by lukaseder** [comment]
> Maybe I did something wrong. I'll look into it again when this is released.

Ah yes, it's because I'm getting `java.lang.Object` instead of `java.lang.Integer`. I'll note that in the right issue

**Comment by gotson** [comment]
> > Maybe I did something wrong. I'll look into it again when this is released.
> 
> Ah yes, it's because I'm getting `java.lang.Object` instead of `java.lang.Integer`. I'll note that in the right issue

It's normal. Before you would always get `java.lang.Object`, but we added better support in #541. But since SQLite is not typed, when you get the column type before execution, SQLite cannot provide the actual storage type (which would be INT). In case it can't do that, it would look for the column definition, but in that test you do `select 1`, so there's nothing to help guessing the type.

You would probably get `java.lang.Integer` with a proper table definition, or `select CAST(1 as INT)`.
