### ISSUE TITLE
Question About DatabaseMetaData.getImportedKeys() and getPrimaryKeys()

### ISSUE THREAD

**Issue by NoAnyLove** [xerial/sqlite-jdbc#81]
Currently(v3.8.11.2), `DatabaseMetaData.getImportedKeys()` always return empty string on FK_NAME column, even if FKCOLUMN_NAME column is not empty. Is it better to return some non-empty string in FK_NAME column, especially if there exists more than one foreign keys.

Besides, `DatabaseMetaData.getPrimaryKeys()` always return null string on PK_NAME column, even if there exists primary key.

**Comment by sualeh** [comment]
Fixed in the latest release.
