### ISSUE TITLE
Regression when calling PreparedStatement::getMetaData on not yet executed statements

### ISSUE THREAD

**Issue by lukaseder** [xerial/sqlite-jdbc#811]
**Describe the bug**

It used to be possible in version 3.36.0.3 to call `PreparedStatement::getMetaData` on a not yet executed `PreparedStatement`. This should be possible in principle, given the JDBC Spec, as you can see in its Javadoc:

> Because a PreparedStatement object is precompiled, it is possible to know about the ResultSet object that it will return without having to execute it. Consequently, it is possible to invoke the method getMetaData on a PreparedStatement object rather than waiting to execute it and then invoking the ResultSet.getMetaData method on the ResultSet object that is returned. 
> 
> NOTE: Using this method may be expensive for some drivers due to the lack of underlying DBMS support.

I'm assuming the `NOTE` hints at the fact that the statement must be executed if a driver doesn't really support preparing statements. Personally, I would be fine with that.

However, this no longer works in 3.39.4.1-SNAPSHOT

**To Reproduce**

```java
try (PreparedStatement s = connection.prepareStatement("select 1")) {
    System.out.println(s.getMetaData().getColumnCount());
    System.out.println(s.getMetaData().getColumnClassName(1));
}
```

It used to produce

```
1
java.lang.Object
```

(though `Object` was wrong in my opinion)

But now it throws:

```
1
Exception in thread "main" java.sql.SQLException: ResultSet closed
	at org.sqlite.core.CoreResultSet.checkOpen(CoreResultSet.java:84)
	at org.sqlite.core.CoreResultSet.markCol(CoreResultSet.java:113)
	at org.sqlite.jdbc3.JDBC3ResultSet.getColumnClassName(JDBC3ResultSet.java:581)
	at org.jooq.testscripts.JDBC.main(JDBC.java:67)
```

Given that `getColumnCount()` still works (possibly after fixing https://github.com/xerial/sqlite-jdbc/issues/808), I assume that this is just a bug, not by design?

**Expected behavior**

The behaviour should be the same as when I manually execute the query:

```sql
try (PreparedStatement s = connection.prepareStatement("select 1")) {
    s.executeQuery();
    System.out.println(s.getMetaData().getColumnCount());
    System.out.println(s.getMetaData().getColumnClassName(1));
}
```

Producing:

```
1
java.lang.Integer
```

**Environment (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.22000.1219]
 - CPU architecture: x86_64
 - sqlite-jdbc version: 3.39.4.1-SNAPSHOT

**Comment by lukaseder** [comment]
> We are maintaining code that is extremely old, and is in dire need of a good revamp!

Well, step 1, add more tests, e.g. for this case :)

**Comment by gotson** [comment]
> > We are maintaining code that is extremely old, and is in dire need of a good revamp!
> 
> Well, step 1, add more tests, e.g. for this case :)

yeap, that's what i do since i took the maintenance of the project :)

**Comment by lukaseder** [comment]
For the record, the exception is now gone, but I'm still getting this result:

```
1
java.lang.Object
```

This is what the older driver versions used to produce. I still think this is wrong, given that it switches to this, once executed:

```
1
java.lang.Integer
```

But that's a different bug from this one, if it is a bug at all.

**Comment by gotson** [comment]
I doubt you ever got something else than `java.lang.Object` before [3.39.3.0](https://github.com/xerial/sqlite-jdbc/tree/3.39.3.0), as the return value was hardcoded:

```java
public String getColumnClassName(int col) throws SQLException { 
     checkCol(col); 
     return "java.lang.Object"; 
 } 
```

See #541

**Comment by lukaseder** [comment]
> I doubt you ever got something else than `java.lang.Object` before [3.39.3.0](https://github.com/xerial/sqlite-jdbc/tree/3.39.3.0), as the return value was hardcoded:

Yes, I never got `Integer` at all in 3.36.0.3. But I do get `Integer` now, *after* executing the query. That's what I meant.

**Comment by gotson** [comment]
> > I doubt you ever got something else than `java.lang.Object` before [3.39.3.0](https://github.com/xerial/sqlite-jdbc/tree/3.39.3.0), as the return value was hardcoded:
> 
> Yes, I never got `Integer` at all in 3.36.0.3. But I do get `Integer` now, _after_ executing the query. That's what I meant.

So all good now ?



> You would probably get `java.lang.Integer` with a proper table definition, or `select CAST(1 as INT)`.

I just tested that and actually it's not how it works. We do check the column definition in `getColumnType`, but since `getColumnClassName` need to report what type would be returned by `getObject`, we can't assume and return a potentially incorrect type. So `Object` is the catch-all if we can't know.

**Comment by lukaseder** [comment]
> So all good now ?

Yeah
