### ISSUE TITLE
Breaking change should be better documented

### ISSUE THREAD

**Issue by jdev-2020** [xerial/sqlite-jdbc#814]
The change is documented on the commit message only: https://github.com/xerial/sqlite-jdbc/commit/0f41f46ca81f05a3979de49f68e9db64473201e6

> BREAKING-CHANGE: previously log() computed the natural logarithm, now it computes a base-10 logarithm

**Comment by gotson** [comment]
There's a 🚨 icon in the release notes, generated by JReleaser

**Comment by petitJAM** [comment]
It would be handy to update the changelog on the [3.40.0.0](https://github.com/xerial/sqlite-jdbc/releases/tag/3.40.0.0) release to note the breaking change if possible. The :rotating_light: icon doesn't really mean anything to someone not familiar with jreleaser or this project.

**Comment by gotson** [comment]
> It would be handy to update the changelog on the [3.40.0.0](https://github.com/xerial/sqlite-jdbc/releases/tag/3.40.0.0) release to note the breaking change if possible. The 🚨 icon doesn't really mean anything to someone not familiar with jreleaser or this project.

done
