### ISSUE TITLE
Memory Leak in JDBC driver?

### ISSUE THREAD

**Issue by 29swastik** [xerial/sqlite-jdbc#817]
We are using Xerial-JDBC driver with Spring boot and hibernate (with the help of [gwenn sqlite-dialect](https://github.com/gwenn/sqlite-dialect) ). We are seeing the our Java process is taking huge memory(~1.9 GB), but when we see our Java app heap and non-heap usage it is very less. As we can see below avg.heap.memory ~ 150MB & avg.non.heap.memory ~ 200MB. But when we check memory usage of the same App using top command we found that app was taking  ~1.9GB (49.5% of 3.8GB).

Our AWS instance has 4GB of memory and this java app has started to take more half of the memory within 24hrs of deployment

**Top command o/p**
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                          
25359 ec2-user  20   0 4918.3m   1.9g   8.3m S 100.7 49.5 741:29.97 /usr/bin/java -javaagent:/opt/elastic-apm/apm-agent-1.24.0.jar -Delastic.apm.config_file=/opt/elastic-apm/my-java-app.p+
22059 ec2-user  20   0 5760.8m 452.1m   8.1m S   0.7 11.8 751:36.03 java -Xms256M -Xmx1g -server -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35 -XX:+ExplicitGCInvokesCo+
```

**Avg Heap & Non Heap memory usage**
<img width="920" alt="image" src="https://user-images.githubusercontent.com/65583094/204993296-e9a0486b-3b9b-4efe-9894-5208746aca99.png">

**Environment**
 - OS: `Amazon Linux 2 (centos rhel fedora)`
 - CPU architecture: `aarch64`
 - sqlite-jdbc version: `implementation("org.xerial:sqlite-jdbc:3.39.4.0")`
 - gwenn sqlite-dialect: `implementation("com.github.gwenn:sqlite-dialect:0.1.2")`
 
 Is there any internal memory leak in the driver? or Am I missing something here?

**Comment by 29swastik** [comment]
SQLite PRAGMA used in the APP
```
pragma journal_mode=wal
pragma synchronous=normal
pragma temp_store=memory
pragma threads=8
pragma cache_size=128000
```

**Comment by gotson** [comment]
> Is there any internal memory leak in the driver?

not that we know of, but there may be.

> Am I missing something here?

if you want anything done on that front, you will need to perform your own debugging to show that a memory leak is coming from the library.

**Comment by gotson** [comment]
> But when we check memory usage of the same App using top command we found that app was taking ~1.9GB (49.5% of 3.8GB)

> Our AWS instance has 4GB of memory and this java app has started to take more half of the memory within 24hrs of deployment

Reading this i have the feeling you don't know very well how the JVM manages memory.

**Comment by gotson** [comment]
To be clear, memory leak means that memory is not properly released, and lost over time, so the memory used increases over time. That usually doesn't happen in the Java code, because the JVM handles the memory for you. It can happen in the C code (JNI part).

What you seem to be referring to is memory consumption, and is not specific to this library, it's how the JVM works. The JVM by default reserves half of the available memory, and manages that internally. Looking at the memory consumption from the OS perspective is never relevant.

**Comment by 29swastik** [comment]
> The JVM by default reserves half of the available memory

So the ~1.9GB of memory consumption we are seeing in the top command output is expected?
