### ISSUE TITLE
[SQLITE_ERROR] SQL error or missing database (no such function: UNIXEPOCH)

### ISSUE THREAD

**Issue by liangsai12** [xerial/sqlite-jdbc#820]
**Describe the bug**
JDBC Driver Error: [SQLITE_ERROR] SQL error or missing database (no such function: UNIXEPOCH)

**To Reproduce**
SELECT UNIXEPOCH();

**Expected behavior**
SQLite 3.38.0 was released on 2nd February 2022. With it came some enhancement to the date and time functions.

**Logs**
JDBC Driver Error: [SQLITE_ERROR] SQL error or missing database (no such function: UNIXEPOCH)

**Environment (please complete the following information):**
 - OS: [Win10]
 - CPU architecture: [x86_64,]
 - sqlite-jdbc version [3.40.0.0]

**Additional context**
https://database.guide/sqlite-introduces-the-unixepoch-function/

**Comment by gotson** [comment]
I can't reproduce, it works fine on my side.

**Comment by gotson** [comment]
I [added a test](https://github.com/xerial/sqlite-jdbc/commit/3904e83bf0b2e9d9ab2019f8c8bf49f567fb74ac) for this, it works fine [in CI on Windows](https://github.com/xerial/sqlite-jdbc/actions/runs/3713315827/jobs/6295819540).
