### ISSUE TITLE
Errorcode is not filled.

### ISSUE THREAD

**Issue by CecilWesterhof** [xerial/sqlite-jdbc#83]
I have the following code:

``` java
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.SQLException;


public class CheckProverbsLocked {
    private CheckProverbsLocked() {
    }

    public static void main(String [] args) throws Exception {
        Connection   conn;
        Statement    stmt;

        Class.forName("org.sqlite.JDBC");
        conn = DriverManager.getConnection("jdbc:sqlite:proverbs.sqlite");
        stmt  = conn.createStatement();
        try {
            stmt.executeUpdate("begin immediate");
        } catch (SQLException e) {
            System.out.println(e.getErrorCode());
            System.out.println(e.getMessage());
            System.out.println(e.getSQLState());
        }
        stmt.close();
        conn.close();
    }

}
```

​I get the following output when the database is locked:
0
database is locked
null

​I would expect the first one to be 5​.

**Comment by CecilWesterhof** [comment]
I would not mind to look into the problem myself. If somebody could give me pointers where to look, I could give it a try.

**Comment by compengi** [comment]
Look here: https://github.com/xerial/sqlite-jdbc/blob/master/src/main/java/org/sqlite/jdbc3/JDBC3Statement.java at #executeUpdate() method.

It seems it could be coming from either ext.execute(db); or db._exec(sql); where both call the native implementation of sqlite.

I hope I could help you further.

**Comment by auntyellow** [comment]
`SQLException.getSQLState()` is a more common code (5 digits) for an exception. Most JDBC Drivers like MySQL, PostgreSQL, DB2, Apache Derby, H2 support this. e.g. `23505` means a violation of the constraint imposed by a unique index or a unique constraint occurred (MySQL only matches first 2 digits). See:

- https://www.ibm.com/support/knowledgecenter/en/SSEPEK_11.0.0/codes/src/tpc/db2z_sqlstatevalues.html
- https://en.wikipedia.org/wiki/SQLSTATE

**Comment by gotson** [comment]
Closing this as it's very old. Comment if necessary.
