### ISSUE TITLE
arm64 couldn't find "libsqlitejdbc.so" 

### ISSUE THREAD

**Issue by mironoff2007** [xerial/sqlite-jdbc#833]
Please advise if this is a mistake or if I did something wrong.

java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/app.text-y0ZqgH1vwIgRDVtkTETz7g==/base.apk"],nativeLibraryDirectories=[/data/app/app.text-y0ZqgH1vwIgRDVtkTETz7g==/lib/arm64, /system/lib64, /system/product/lib64]]] couldn't find "libsqlitejdbc.so"

Libs from Linux/Android are located here in project - https://github.com/mironoff2007/xerial_test
xerial = "3.40.0.0"

<img src="https://user-images.githubusercontent.com/18057056/215289316-a9330f67-8dce-49b6-b9c9-bbb8fa3129f7.png" width="250" height="250">
 
device info
<img src="https://user-images.githubusercontent.com/18057056/215289324-6733c5ea-f6e1-4ccc-b823-5b31b1c088ac.png" width="250" height="350">

x86 emulator works fine

**Comment by gotson** [comment]
did you read https://github.com/xerial/sqlite-jdbc/blob/master/USAGE.md#how-to-use-with-android ?

**Comment by mironoff2007** [comment]
> did you read https://github.com/xerial/sqlite-jdbc/blob/master/USAGE.md#how-to-use-with-android ?

Sorry, but I missed that. Thank you very much.
