### ISSUE TITLE
Is there a way to connect and read SQLite db from buffer (byte[]) ?

### ISSUE THREAD

**Issue by lisaied** [xerial/sqlite-jdbc#834]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by gotson** [comment]
Please fill the issue

**Comment by lisaied** [comment]
hi Gotson,
I'm checking here if the current JDBC SQLite Drive can connect to an existing SQLite database located at memory as byte[] (no written into a file on the disk)

**Comment by gotson** [comment]
no, that's not possible, because the database is managed in the SQLite C library, loaded via JNI. What you can do is write that byte buffer to a temp file, and open the temp file.
