### ISSUE TITLE
Missing junit-jupiter-params artifact in the dependencies with test scope

### ISSUE THREAD

**Issue by pgrt** [xerial/sqlite-jdbc#838]
Hello,

On Debian unstable, the build of version 3.40.1.0 of sqlite-jdbc is failing as the junit-jupiter-params is missing in the dependencies with a test scope. Two of its classes are imported from org.sqlite.DBMetaDataTest.java.

Thanks a lot,

Best,
Pierre

**Comment by gotson** [comment]
how do you build it?
