### ISSUE TITLE
Sqlite JDBC driver returning error for table having more than 2000 Columns

### ISSUE THREAD

**Issue by saif-17** [xerial/sqlite-jdbc#840]
**Describe the bug**
When querying a table that has more than 2000 columns an error is returned. Even though only a few columns are queried.

`[SQLITE_CORRUPT] The database disk image is malformed (malformed database schema (TableName) - too many columns on TableName)`

**To Reproduce**
- Recompile the Sqlite Source code to support more than 2000 columns by giving the flag `-DSQLITE_MAX_COLUMN=32767`.
- Create a table having more than 2000 Columns
- Query or insert data to the created table.
- Error would be returned when Querying the table with more than 2000 columns.

**Expected behavior**
Data should be returned

**Logs**
`[SQLITE_CORRUPT] The database disk image is malformed (malformed database schema (TableName) - too many columns on TableName)`

**Environment (please complete the following information):**
 - OS: `CentOS 7.9.2009`
 - CPU architecture: `x86_64`
 - sqlite-jdbc version `3.39.3.0`
 - `Temurin OpenJDK 8u332b09`

**Comment by gotson** [comment]
The libs are already compiled with the upper limit: https://github.com/xerial/sqlite-jdbc/blob/78633768a40c13d244799c2527f5cf20eb8ba3af/Makefile#L94-L94

You also need to set the runtime limit, see https://www.sqlite.org/c3ref/limit.html and https://www.sqlite.org/c3ref/c_limit_attached.html

There's a pragma for that: https://github.com/xerial/sqlite-jdbc/blob/78633768a40c13d244799c2527f5cf20eb8ba3af/src/main/java/org/sqlite/SQLiteConfig.java#L130-L132

https://github.com/xerial/sqlite-jdbc/blob/78633768a40c13d244799c2527f5cf20eb8ba3af/src/main/java/org/sqlite/SQLiteConfig.java#L475-L478

The default value for `DEFAULT_MAX_COLUMN` is `2000`: https://github.com/xerial/sqlite-jdbc/blob/78633768a40c13d244799c2527f5cf20eb8ba3af/src/main/java/org/sqlite/SQLiteConfig.java#L48-L48

**Comment by saif-17** [comment]
https://github.com/xerial/sqlite-jdbc/blob/78633768a40c13d244799c2527f5cf20eb8ba3af/src/main/java/org/sqlite/SQLiteConfig.java#L48-L48

Changing the `DEFAULT_MAX_COLUMN` and recompiling the JDBC driver should suffice.
Can you please also provide the commands to compile the JDBC driver?

**Comment by gotson** [comment]
> Changing the `DEFAULT_MAX_COLUMN` and recompiling the JDBC driver should suffice.

no, as i just explained

> Can you please also provide the commands to compile the JDBC driver?

https://github.com/xerial/sqlite-jdbc/blob/master/CONTRIBUTING.md#how-to-compile-the-native-libraries
