### ISSUE TITLE
SQLite driver support for CLOBs and BLOBs

### ISSUE THREAD

**Issue by andreaformica** [xerial/sqlite-jdbc#85]
Dear all, first of all thanks a lot for your efforts in the development of this driver.
I need to use it in a system in which it is mandatory to provide support for CLOBs and BLOBs data types.
I was wondering if you have any plans for supporting them and eventually what are the timescales.
Thanks a lot in advance,
Andrea

**Comment by jtrunick** [comment]
+1

**Comment by gitblit** [comment]
AFAIK this should work.  Can you provide a unit test which demonstrates what you think may be missing?
