### ISSUE TITLE
Empty ResultSet doesn't auto close

### ISSUE THREAD

**Issue by Gypopo** [xerial/sqlite-jdbc#867]
**Describe the bug**
Using SQLLite 3.36.0 seems to close the ResultSet automatically when the query has no results, however using version 3.41.2.1(latest as of now) this doesn't automaticcaly close the ResultSet. I could just check if `rs.next() == true` but my code depends on the exception as of now and Im not sure if this is a issue with SQLLite or something Im missing.

**To Reproduce**
Supose I have a **empty** table called 'transactions' with a uuid and trans_id row.

Executing the following code when using SQLLite 3.36.0 returns `rs.isClosed(): true`
```
Statement stmt = conn.createStatement();
ResultSet rs = stmt.executeQuery("SELECT uuid FROM transactions WHERE trans_id = 'test';");
System.out.println("rs.isClosed(): " + rs.isClosed());
```
but executing the same code on SQLLite 3.41.2.1 returns `rs.isClosed(): false`.

**Expected behavior**
Im expecting the ResultSet to still autoclose.

**Logs**
//

**Environment (please complete the following information):**
Same for linux/docker aswell as windows.

**Additional context**
Like I sayd, Im not sure if this is supposed to happen but quickly looking at the changelogs this hasn't changed, correct me if Im wrong.

**Comment by gotson** [comment]
I think it was a bug fixed in https://github.com/xerial/sqlite-jdbc/pull/764

**Comment by gotson** [comment]
> I could just check if `rs.next() == true`

Note that you should always check this before consuming a result set

The javadoc says :

> A ResultSet object maintains a cursor pointing to its current row of data. Initially the cursor is positioned before the first row. The next method moves the cursor to the next row, and because it returns false when there are no more rows in the ResultSet object, it can be used in a while loop to iterate through the result set.

**Comment by gotson** [comment]
> quickly looking at the changelogs this hasn't changed, correct me if Im wrong

This was part of https://github.com/xerial/sqlite-jdbc/releases/tag/3.39.2.1

**Comment by Gypopo** [comment]
> > quickly looking at the changelogs this hasn't changed, correct me if Im wrong
> 
> This was part of https://github.com/xerial/sqlite-jdbc/releases/tag/3.39.2.1

So why did this change in the first place? It always throwed an error on empty result sets(not only 3.36, I think all versions before that tho), it would be an easy fix on my side but the reason it threw errors before and now doesn't raised a question for me.

**Comment by Gypopo** [comment]
> > I could just check if `rs.next() == true`
> 
> Note that you should always check this before consuming a result set
> 
> The javadoc says :
> 
> > A ResultSet object maintains a cursor pointing to its current row of data. Initially the cursor is positioned before the first row. The next method moves the cursor to the next row, and because it returns false when there are no more rows in the ResultSet object, it can be used in a while loop to iterate through the result set.

Nevertheless, thanks for the clarification. Guess I should change my code.

**Comment by gotson** [comment]
> So why did this change in the first place?

Read the original issue https://github.com/xerial/sqlite-jdbc/issues/744
