### ISSUE TITLE
Assertion failure with `-DSQLITE_DEBUG=1` build flag

### ISSUE THREAD

**Issue by DerZc** [xerial/sqlite-jdbc#874]
**Describe the bug**
I build the jar package with `export CFLAGS="-DSQLITE_DEBUG=1"`, then run the following java program with `target/sqlite-jdbc-3.41.2.2-SNAPSHOT.jar` and meet an assertion failure. but I run these query with sqlite CLI, there is no assertion failure.

```
package reproduce;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

public class reproduce {
    private static final String DRIVER_NAME = "org.sqlite.JDBC";
    private static final String URL = "jdbc:sqlite:test.db";
    private static Connection connection;
    public static void main(String[] args) throws Exception {
        try {
            Class.forName(DRIVER_NAME);
            connection = DriverManager.getConnection(URL);
        } catch (Exception e) {
            e.printStackTrace();
            connection = null;
        }
        List<String> program = new ArrayList<>();
        program.add("PRAGMA encoding = 'UTF-16';");
        program.add("CREATE TABLE t0 (c1 TEXT );");
        program.add("INSERT INTO t0 VALUES ('');");
        program.add("CREATE INDEX i0 ON t0(c1);");
        program.add("ANALYZE;");
        program.add("SELECT * FROM t0 WHERE t0.c1 BETWEEN '' AND (ABS(''));");

        try (Statement statement = connection.createStatement()){
            for(String script: program) {
                try {
                    statement.execute(script);
                } catch (Exception e) {
                    System.out.println(e.getMessage());
                }
            }
        }catch (Exception e) {
            e.printStackTrace();
        }
    }
}

```

**To Reproduce**
`export CFLAGS="-DSQLITE_DEBUG=1"`

**Expected behavior**
No assertion failure.

**Logs**
`java: target/sqlite-3.41.2-Linux-x86_64/sqlite3.c:81897: valueFromFunction: Assertion `enc==pVal->enc || (pVal->flags & MEM_Str)==0 || db->mallocFailed' failed.`

**Environment (please complete the following information):**
 - OS: [Ubuntu 22.04]
 - CPU architecture: [x86_64]
 - sqlite-jdbc version [76b90f7](https://github.com/xerial/sqlite-jdbc/commit/76b90f7be018ddd98978e9f60a5fd7fff68ed916)

**Comment by gotson** [comment]
I don't quite understand what you are doing.  `SQLITE_DEBUG` is a compile time option for Sqlite. Building the jar with this option would have no effect, as the native libraries are already compiled in the repo.

**Comment by DerZc** [comment]
I want to test Sqlite3 and modify this line https://github.com/xerial/sqlite-jdbc/blob/master/Makefile#L40 to download the latest commit version of Sqlite3. So I will build the Sqlite3 and `SQLITE_DEBUG` will have effect.

**Comment by gotson** [comment]
> I want to test Sqlite3 and modify this line https://github.com/xerial/sqlite-jdbc/blob/master/Makefile#L40 to download the latest commit version of Sqlite3. So I will build the Sqlite3 and `SQLITE_DEBUG` will have effect.

That is not at all what you explained in the first message. If you can't explain what you do, how can you expect people to help?

Anyhow the failures are in the C code, so nothing related to sqlite-jdbc.

**Comment by DerZc** [comment]
Thank you for your reply! This only occurs with JDBC driver, but I tried it with latest source code and can not reproduce, maybe it has been fixed. I close this issue.
