### ISSUE TITLE
Different behavior from Sqlite3 CLI because of default configuration

### ISSUE THREAD

**Issue by DerZc** [xerial/sqlite-jdbc#891]
**Describe the bug**

The following program has different behavior from Sqlite3, in CLI it will report an error, but with JDBC, it will return `NULL`, which might be an unexpected result.

```
CREATE TABLE vt0(c0);
CREATE VIRTUAL TABLE rt1 USING rtree_i32(c0, c1, c2, +c3);

CREATE VIEW v0(c0) AS SELECT (rt1.c0) FROM rt1;

INSERT INTO vt0(c0) VALUES (1);
INSERT INTO rt1(c0) VALUES (1);

SELECT rt1.c0  FROM v0 INNER JOIN vt0 FULL OUTER JOIN rt1;
```

**To Reproduce**

I write a java program to reproduce this: 

```
package reproduce;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;

public class reproduce14 {
    public static void main(String[] args) throws Exception {
        try {
            String cmd = "rm ./test.db";
            Runtime.getRuntime().exec(cmd);
        } catch (Exception e) {
            e.printStackTrace();
        }

        String DRIVER_NAME = "org.sqlite.JDBC";
        String URL = "jdbc:sqlite:test.db";
        Connection connection = null;
        try {
            Class.forName(DRIVER_NAME);
            connection = DriverManager.getConnection(URL);
        } catch (Exception e) {
            e.printStackTrace();
            connection = null;
        }

        ArrayList<String> sqls = new ArrayList<>();
        sqls.add("CREATE TABLE vt0(c0);");
        sqls.add("CREATE VIRTUAL TABLE rt1 USING rtree_i32(c0, c1, c2, +c3 INTEGER);");
        sqls.add("CREATE VIEW v0(c0) AS SELECT (rt1.c0) FROM rt1;");
        sqls.add("INSERT INTO vt0(c0) VALUES (1);");
        sqls.add("INSERT INTO rt1(c0) VALUES (1);");
        sqls.add("SELECT rt1.c3  FROM v0 INNER JOIN vt0 FULL OUTER JOIN rt1;");

        try (Statement statement = connection.createStatement()){
            for(String script: sqls) {
                System.out.println("Query: " + script);
                try {
                    if (script.startsWith("SELECT")) {
                        try (ResultSet rs = statement.executeQuery(script)) {
                            while (rs.next()) {
                                System.out.println(Long.valueOf((Integer) rs.getObject(1)));
                            }
                        }
                    }
                    statement.execute(script);
                } catch (SQLException e) {
                    System.out.println(e.getMessage());
                } catch (Exception e) {
                    System.out.println(e.getMessage());
                }
            }
        }catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
}
```

I report this to [Sqlite3 forum](https://sqlite.org/forum/forumpost/6fc9f669c9), the developer said this is because the different default value of configuration [SQLITE_DBCONFIG_TRUSTED_SCHEMA](https://sqlite.org/c3ref/c_dbconfig_defensive.html#sqlitedbconfigtrustedschema), I tried to add `PRAGMA trusted_schema = boolean;` in program and found it will have the same results in CLI and JDBC. 

I am not sure which one is the best configuration, so this is just a hint of a potential problem.

**Expected behavior**
Report an error on this program

**Environment (please complete the following information):**
 - OS: [Ubuntu 22.04]
 - CPU architecture: [x86_64]
 - sqlite-jdbc version [3.41.2.1]

**Comment by gotson** [comment]
we don't set that pragma, but the website says that the default behaviour is that it is ON. However the CLI has it off.

This pragma is not in the supported list, you can send a PR to add it.

**Comment by DerZc** [comment]
Hi @gotson, thank you for your reply. As stated in this [document](https://sqlite.org/pragma.html#pragma_trusted_schema), the default value for this configuration is `ON` for maintaining backwards compatibility, and it is only set to OFF by default in the CLI. Therefore, I believe that leaving it unchanged may be a better option to avoid any compatibility issues.

**Comment by gotson** [comment]
> Hi @gotson, thank you for your reply. As stated in this [document](https://sqlite.org/pragma.html#pragma_trusted_schema), the default value for this configuration is `ON` for maintaining backwards compatibility, and it is only set to OFF by default in the CLI. Therefore, I believe that leaving it unchanged may be a better option to avoid any compatibility issues.

yes, we don't handle this. If you want to be able to set the PRAGMA in sqlite-jdbc, it needs to be handled in the code (like all other pragmas). We would accept a PR for this.
