### ISSUE TITLE
My project throws an error when I try to connect to my database

### ISSUE THREAD

**Issue by TechPro424** [xerial/sqlite-jdbc#895]
**Describe the bug**
My project throws an error `No suitable driver found for C:\Users\TechPro424\Coding\Auction House\run\config/auction-house/database/auction-house.db` when I try to connect to my database

**To Reproduce**
https://gist.github.com/TechPro424/796873f47e5851f46808c498db99925f

**Expected behavior**
I expected it to connect to my database and log the following message: `Connection to SQLite has been established.`

**Logs**
[latest.log](https://github.com/xerial/sqlite-jdbc/files/11342537/latest.log)

**Environment (please complete the following information):**
 - OS: `Windows 11`
 - CPU architecture: `x64`
 - sqlite-jdbc version: `3.41.2.1`

**Additional context**
This probelem occurs in a Minecraft mod that I am making

**Comment by gotson** [comment]
better suited for Stackoverflow.com

**Comment by TechPro424** [comment]
Found the solution
In `Database.java`, replace
```java
connection = DriverManager.getConnection(url);
```
with
```java
connection = DriverManager.getConnection("jdbc:sqlite:config/auction-house/database/auction-house.db");
