### ISSUE TITLE
Define used glibc version for ppc64le

### ISSUE THREAD

**Issue by snoerenberg** [xerial/sqlite-jdbc#913]
**Is your feature request related to a problem? Please describe.**
We want to use the newest version of the library but struggle with the GLibC version used for compiling.

On SLES 15 SP3 the version from OS is:
```
ldd --version
ldd (GNU libc) 2.31
```

using the newest driver returns:
```
Failed to load native library:sqlite-3.42.0.0-2b3cf3f6-bade-4f72-a1a0-e7c80ad6ce62-libsqlitejdbc.so. osinfo: Linux/ppc64
java.lang.UnsatisfiedLinkError: /tmp/sqlite-3.42.0.0-2b3cf3f6-bade-4f72-a1a0-e7c80ad6ce62-libsqlitejdbc.so (/lib64/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/sqlite-3.42.0.0-2b3cf3f6-bade-4f72-a1a0-e7c80ad6ce62-libsqlitejdbc.so))
        at java.lang.ClassLoader.loadLibraryWithPath(ClassLoader.java:1460)
```

**Describe the solution you'd like**
Is it possible to use GLIBC 2.31 for compiling the native driver? 

**Describe alternatives you've considered**
I'm struggeling to modify dockcross with the required version, would this be the most suitable way?
https://github.com/dockcross/dockcross/blob/master/linux-ppc64le/crosstool-ng.config#L416

Thanks a lot for your support
Stephan

**Comment by gotson** [comment]
This is a question for the dockcross folks, we use it but i have no idea how to modify it. You may need to ask for an `-lts` version of the dockcross container that would use an older glibc version.

**Comment by snoerenberg** [comment]
Thanks a lot for the confirmation.
