### ISSUE TITLE
JDBC3PreparedStatement.setObject(int pos, Object value) when on unknow type should be throw SQLFeatureNotSupportedException not toString()

### ISSUE THREAD

**Issue by scx567888** [xerial/sqlite-jdbc#916]
**Is your feature request related to a problem? Please describe.**
If i have a LocalDateTime , When i use PreparedStatement(JDBC3PreparedStatement).setObject(int pos, Object value) , is should throw SQLFeatureNotSupportedException not call LocalDateTime.toString()

**Describe the solution you'd like**
JDBC3PreparedStatement.setObject(int pos, Object value) when on unknow type should be throw SQLFeatureNotSupportedException not toString()

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by gotson** [comment]
Can you explain why?

**Comment by scx567888** [comment]
Because most of the time, toString() cannot represent the truly useful information of the data, and if an exception is thrown, I can perform special processing after catching the exception.

**Comment by gotson** [comment]
The spec says :

> SQLException - if parameterIndex does not correspond to a parameter marker in the SQL statement; if a database access error occurs; this method is called on a closed PreparedStatement or the type of the given object is ambiguous

I think we recently added support to return LocalDateTime, thus it should not be ambiguous, and should not throw an exception.

**Comment by scx567888** [comment]
I know this may break some code that use on it.  How about make it configurable

**Comment by gotson** [comment]
We can add support for Java 8 date and time in a next release.

**Comment by gotson** [comment]
I looked into that, and it works as expected. `toString` for `LocalDateTime` is an acceptable representation of a timestamp for SQLite.

I don't understand what is your problem with this.

**Comment by scx567888** [comment]
I don't know why you always persist in LocalDateTime I'm just using LocalDateTime as an example. The essence of the problem is that SQLFeatureNotSupportedException should be thrown for unknown types.

**Comment by gotson** [comment]
> I don't know why you always persist in LocalDateTime I'm just using LocalDateTime as an example. The essence of the problem is that SQLFeatureNotSupportedException should be thrown for unknown types.

you need to state the problem correctly in that case. You clearly mentioned LocalDateTime in the issue, which works fine with the existing code, so it is a badly chosen example.
