### ISSUE TITLE
I found a Dos in sqlite-jdbc

### ISSUE THREAD

**Issue by yuansec** [xerial/sqlite-jdbc#917]
https://github.com/xerial/sqlite-jdbc/security/advisories/GHSA-rch7-2fqx-g298

**Comment by gotson** [comment]
You can report a vulnerability, see https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing/privately-reporting-a-security-vulnerability#privately-reporting-a-security-vulnerability

**Comment by yuansec** [comment]
hi,I have submitted according to the link on June 2nd(https://github.com/xerial/sqlite-jdbc/security/advisories/GHSA-rch7-2fqx-g298).Only the author can see it,but no one has replied.Please tell me what to do
![image](https://github.com/xerial/sqlite-jdbc/assets/18318654/3243a5f8-88ee-4cd3-af2a-2e0ea78a506d)
