### ISSUE TITLE
Performance issue after upgrading sqlite-jdbc driver version from 3.39.4.1 to 3.40.0.0 and onwards

### ISSUE THREAD

**Issue by mukeshsharma8** [xerial/sqlite-jdbc#919]
**Describe the bug**
Basic SELECT queries taking too long and queries with multiple operations like JOINS etc hanging infinitely when we have recored around 100K after upgrading sqlite-jdbc version from 3.39.4.1 to 3.40.0.0 and onwards

**To Reproduce**
We are using it as maven dependency https://mvnrepository.com/artifact/org.xerial/sqlite-jdbc though we have tested it with jar from maven as well from https://jar-download.com/artifact-search/sqlite-jdbc , so having same problem with both sources.

**Expected behavior**
Queries are working fine with sqlite-jdbc version 3.39.4.1 , so expecting the same behaviour in latest versions with out degrading the performance

**Logs**
There is no exception in the console logs  , queries are hanging infinitely .

**Environment (please complete the following information):**
 - OS: Mac
 - CPU architecture: 
 - sqlite-jdbc version 3.40.0.0  and onwards 

**Additional context**

**Comment by gotson** [comment]
Honestly what do you expect from such a ticket? You provide zero details on your application, no benchmark, no code, nothing.
