### ISSUE TITLE
Native crash - 

### ISSUE THREAD

**Issue by SalkinD** [xerial/sqlite-jdbc#92]
Hi!

I have quite a rare bug, only occurring after a long runtime of my server app. As it is a native crash I can't handle this exception nicely.  Does anyone know what happens here?

And a small "feature request": an exception would be very nice :)

It happens at a standard JDBC3ResultSet.getLong call. 

---

Java Code (simplified):
 stm = db.getStatement();
rs = stm.executeQuery("SELECT \* FROM 'Images' WHERE sha256 = '"+sha+"'");
 if(rs.next()){ // This file already exists
    if(maintenance.get()){
       if(rs.getLong("IndexingTimestamp") < (new Date().getTime()-240000)){
                        //do something here... 
       }
##    }

EDIT: Some more crash information:
siginfo: ExceptionCode=0xc0000005, reading address 0x1a431bc4

Registers:
EAX=0x70fa0020, EBX=0x1a431bb0, ECX=0x00000000, EDX=0x0000000d
ESP=0x1a2df370, EBP=0x1a2df3f8, ESI=0x1a2df3e4, EDI=0x169a2c00
EIP=0x70f2962f, EFLAGS=0x00010202

Top of Stack: (sp=0x1a2df370)
0x1a2df370:   169715a6 169715a6 1a2df390 6ffb267e
0x1a2df380:   1685981c 1a2df3ec 169a2c00 169a2c00
0x1a2df390:   169a2c00 1a2df3bc 1a431bb0 70f2979d
0x1a2df3a0:   00000000 1a2df3e4 169a2c00 70f02837
0x1a2df3b0:   1a431bb0 0000000d 0a27c608 1a2df3f8
0x1a2df3c0:   0249eafd 0a3a9708 1a2df3ec 0249e9f7
0x1a2df3d0:   169a2d40 1a2df3e4 1a431bb0 00000000
0x1a2df3e0:   0000000d 0a3a9708 1a2df74c 00000003 

Instructions: (pc=0x70f2962f)
0x70f2960f:   37 fe ff 8b 54 24 1c 89 c7 89 83 e0 00 00 00 eb
0x70f2961f:   92 53 89 c3 83 ec 28 85 db b8 20 00 fa 70 74 45
0x70f2962f:   8b 43 14 85 c0 74 04 85 d2 79 46 8b 13 b8 20 00
0x70f2963f:   fa 70 85 d2 74 2f 8b 42 0c 85 c0 74 0b 89 04 24 

Register to memory mapping:

EAX=0x70fa0020 is an unknown value
EBX=0x1a431bb0 is an unknown value
ECX=0x00000000 is an unknown value
EDX=0x0000000d is an unknown value
ESP=0x1a2df370 is pointing into the stack for thread: 0x169a2c00
EBP=0x1a2df3f8 is pointing into the stack for thread: 0x169a2c00
ESI=0x1a2df3e4 is pointing into the stack for thread: 0x169a2c00
EDI=0x169a2c00 is a thread

Stack: [0x1a290000,0x1a2e0000],  sp=0x1a2df370,  free space=316k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [sqlite-3.8.6-x86-sqlitejdbc.dll+0x2962f]
J 1598 C1 org.sqlite.jdbc3.JDBC3ResultSet.getLong(Ljava/lang/String;)J (10 bytes) @ 0x02496dbc [0x02496d30+0x8c]
J 1596 C1 qdicomserver.pacs.FileIndexer.indexFile(Ljava/io/File;)V (1184 bytes) @ 0x02487094 [0x02486ab0+0x5e4]
J 1425 C1 qdicomserver.pacs.FileIndexer.run()V (153 bytes) @ 0x02435e28 [0x02435ac0+0x368]
v  ~StubRoutines::call_stub
V  [jvm.dll+0x155cb5]
V  [jvm.dll+0x21b12e]
V  [jvm.dll+0x155d4e]
V  [jvm.dll+0x155ed6]
V  [jvm.dll+0x155f47]
V  [jvm.dll+0xfb0cf]
V  [jvm.dll+0x17901c]
V  [jvm.dll+0x17910a]
V  [jvm.dll+0x1bd6e6]
C  [msvcr100.dll+0x5c556]
C  [msvcr100.dll+0x5c600]
C  [KERNEL32.DLL+0x17c04]
C  [ntdll.dll+0x5ad1f]
C  [ntdll.dll+0x5acea]
C  0x00000000

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 1624  org.sqlite.core.NativeDB.column_long(JI)J (0 bytes) @ 0x0249e8f1 [0x0249e8a0+0x51]
J 1598 C1 org.sqlite.jdbc3.JDBC3ResultSet.getLong(Ljava/lang/String;)J (10 bytes) @ 0x02496dbc [0x02496d30+0x8c]
J 1596 C1 qdicomserver.pacs.FileIndexer.indexFile(Ljava/io/File;)V (1184 bytes) @ 0x02487094 [0x02486ab0+0x5e4]
J 1425 C1 qdicomserver.pacs.FileIndexer.run()V (153 bytes) @ 0x02435e28 [0x02435ac0+0x368]
v  ~StubRoutines::call_stub

Internal exceptions (10 events):
Event: 288036.651 Thread 0x169a0000 Exception <a 'java/net/SocketTimeoutException': Accept timed out> (0x04905c98) thrown at [C:\re\workspace\8-2-build-windows-i586-cygwin\jdk8u45\3627\hotspot\src\share\vm\prims\jni.cpp, line 735]
Event: 288036.851 Thread 0x169a0000 Exception <a 'java/net/SocketTimeoutException': Accept timed out> (0x04906070) thrown at [C:\re\workspace\8-2-build-windows-i586-cygwin\jdk8u45\3627\hotspot\src\share\vm\prims\jni.cpp, line 735]
Event: 288037.051 Thread 0x169a0000 Exception <a 'java/net/SocketTimeoutException': Accept timed out> (0x049554d8) thrown at [C:\re\workspace\8-2-build-windows-i586-cygwin\jdk8u45\3627\hotspot\src\share\vm\prims\jni.cpp, line 735]
Event: 288037.252 Thread 0x169a0000 Exception <a 'java/net/SocketTimeoutException': Accept timed out> (0x049558b0) thrown at [C:\re\workspace\8-2-build-windows-i586-cygwin\jdk8u45\3627\hotspot\src\share\vm\prims\jni.cpp, line 735]
Event: 288037.452 Thread 0x169a0000 Exception <a 'java/net/SocketTimeoutException': Accept timed out> (0x04981110) thrown at [C:\re\workspace\8-2-build-windows-i586-cygwin\jdk8u45\3627\hotspot\src\share\vm\prims\jni.cpp, line 735]
Event: 288037.653 Thread 0x169a0000 Exception <a 'java/net/SocketTimeoutException': Accept timed out> (0x04228918) thrown at [C:\re\workspace\8-2-build-windows-i586-cygwin\jdk8u45\3627\hotspot\src\share\vm\prims\jni.cpp, line 735]
Event: 288037.853 Thread 0x169a0000 Exception <a 'java/net/SocketTimeoutException': Accept timed out> (0x04228cf0) thrown at [C:\re\workspace\8-2-build-windows-i586-cygwin\jdk8u45\3627\hotspot\src\share\vm\prims\jni.cpp, line 735]
Event: 288038.053 Thread 0x169a0000 Exception <a 'java/net/SocketTimeoutException': Accept timed out> (0x042290c8) thrown at [C:\re\workspace\8-2-build-windows-i586-cygwin\jdk8u45\3627\hotspot\src\share\vm\prims\jni.cpp, line 735]
Event: 288038.188 Thread 0x169a2800 Exception <a 'java/lang/InterruptedException': sleep interrupted> (0x04229568) thrown at [C:\re\workspace\8-2-build-windows-i586-cygwin\jdk8u45\3627\hotspot\src\share\vm\prims\jvm.cpp, line 3211]
Event: 288038.253 Thread 0x169a0000 Exception <a 'java/net/SocketTimeoutException': Accept timed out> (0x042513c8) thrown at [C:\re\workspace\8-2-build-windows-i586-cygwin\jdk8u45\3627\hotspot\src\share\vm\prims\jni.cpp, line 735]

Events (10 events):
Event: 288014.906 Executing VM operation: GenCollectForAllocation done
Event: 288026.028 Executing VM operation: GenCollectForAllocation
Event: 288026.031 Executing VM operation: GenCollectForAllocation done
Event: 288037.616 Executing VM operation: GenCollectForAllocation
Event: 288037.618 Executing VM operation: GenCollectForAllocation done
Event: 288038.186 Thread 0x169a3800 Thread added: 0x169a3800
Event: 288038.203 Executing VM operation: RevokeBias
Event: 288038.203 Executing VM operation: RevokeBias done
Event: 288038.203 Thread 0x169a3400 Thread exited: 0x169a3400
Event: 288038.310 Executing VM operation: RevokeBias

**Comment by testn** [comment]
Can you repro it with latest library?

**Comment by SalkinD** [comment]
Just updated. It will need some time(~a week), this error is very rare. (thought happened about 20 times through the months)

**Comment by testn** [comment]
Every time with the exact same stack trace? You should try to configure windows to dump a core dump into a file so that it can be investigated.

**Comment by SalkinD** [comment]
Yes this error stays the same. I think minidumps are enabled now.

**Comment by testn** [comment]
Is there a specific reason to use 32-bit version instead of 64-bit version?

**Comment by SalkinD** [comment]
Yes, the app is designed multi-platform and works well on win32/64 and several linux distributions.

Maybe I found the problem, a pity there is no error thrown I'd have found it earlier: The database is located on a network drive, maybe it is a connection loss problem. The app reconnects automatically, but this thread wasn't interrupted fast enough in this case. (When it happens between Statement.execute and ResultSet.getLong) The native crash also prevented the logs for reconnection ...bad luck.

There isn't a reliable solution so this problem would cause a java exception instead of a native crash? (Though stabilizing network would be a better solution :) )

**Comment by xerial** [comment]
Yes. I also don't recommend using sqlite-jdbc on NFS....

**Comment by danielcompton** [comment]
See [How to corrupt an SQLite database file](https://sqlite.org/howtocorrupt.html#_filesystems_with_broken_or_missing_lock_implementations) on using NFS for SQLite dbs.
