### ISSUE TITLE
sqlite_schema returned by connection DatabaseMetaData

### ISSUE THREAD

**Issue by yuvalp-k2view** [xerial/sqlite-jdbc#929]
Now that sqlite added sqlite_schema as an alias to sqlite_master, the connection DatabaseMetaData implementation is returning it in all relevant metadata queries.

```java
		try (Connection c = DriverManager.getConnection("jdbc:sqlite:file:k2memdb?mode=memory");
			 ResultSet rs = c.getMetaData().getTables(null, null, null, null)) {

			//assertFalse(rs.next());

			rs.next();
			assertEquals("sqlite_schema", rs.getString("TABLE_NAME"));
		}
```

This table should be filtered out, in every place sqlite_master is filtered.

 - OS: Mac
 - CPU architecture: arm64
 - sqlite-jdbc version: 3.42.0.0

**Comment by gotson** [comment]
i don't quite understand what you are saying, can you explain more in details?

**Comment by gotson** [comment]
If you don't want to select system tables, you need to specify the `types` parameter of `getTables`, see https://github.com/xerial/sqlite-jdbc/blob/d76c9330d447cef58740c98abb3dec79c8849ed5/src/test/java/org/sqlite/DBMetaDataTest.java#L94-L97

**Comment by yuvalp-k2view** [comment]
It's a change in behavior since sqlite_master is not shown regardless. I'm fine with it though.

**Comment by gotson** [comment]
sqlite_master is not shown anymore because the standard is to use sqlite_schema, see https://www.sqlite.org/schematab.html

**Comment by yuvalp-k2view** [comment]
I understand. Just saying that previous versions didn't shown anything (master or schema). All well.

**Comment by gotson** [comment]
> I understand. Just saying that previous versions didn't shown anything (master or schema). All well.

True, it was added recently as a system table.
