### ISSUE TITLE
Driver not working with JamVM

### ISSUE THREAD

**Issue by merdes** [xerial/sqlite-jdbc#93]
Hello,
I'm using this driver in a embedded system. If i launch it with `java -jar MyProgramm.jar` it is working (but really slow)
I chose JamVM for performance reasons, but when i invoke it with: `java -jamvm -jar MyProgramm.jar`
i get the exception not found `java.lang.ClassNotFoundException: org.sqlite.JDBC`. The library is in the package inside MyProgramm.jar. I also tried giving the -classpath with `-classpath ".:sqlite-jdbc-3.8.11.2.jar"` but is also not working.

Any experience with JamVM and this library ? Or any idea why is it not working?

Thank you

**Comment by gitblit** [comment]
I like the juxtaposition of these two phrases....

>  ... this driver ...  is working (but really slow)
> I chose JamVM for performance reasons

Sorry, I have no experience with JamVM.  Clearly this sounds like a JamVM issue.  Is that even actively developed anymore?

**Comment by DanielJoyce** [comment]
JamVm is compact but slow. Its a bytecode interpreter. So it doesn't surprise me if your code is slow.

**Comment by xerial** [comment]
I'm afraid, but I think we won't solve this issue.
