### ISSUE TITLE
Sqlite-Jdbc Build Issue: SQL query does not return ResultSet

### ISSUE THREAD

**Issue by ankita-gupta-05** [xerial/sqlite-jdbc#95]
In building the sqlite-jdbc 3.8.11.2-2 from SRPM
I am getting error in one test case src/test/java/org/sqlite/DBMetaDataTest.java

DBMetaDataTest.getIndexInfoOnTest:675 ? SQL query does not return ResultSet

@Test
    public void getIndexInfoOnTest() throws SQLException {
          ResultSet rs = meta.getIndexInfo(null,null,"test",false,false);
         assertNotNull(rs);
}

And if I comment this test case, I am able to build successfully.

Pls. provide suggestions.

**Comment by gitblit** [comment]
That unit test works fine when built & run from the repo source on Ubuntu 14.04/x64 with Oracle JDK.

**Comment by gotson** [comment]
Closing this as it's very old. Comment if necessary.
