### ISSUE TITLE
Enabling SQLITE_CONFIG_MEMSTATUS is a disaster

### ISSUE THREAD

**Issue by mhanna** [xerial/sqlite-jdbc#953]
**Describe the bug**
When enabling the parameter SQLITE_CONFIG_MEMSTATUS at compile time, the performance (read/write) is more than 2x slower

**To Reproduce**
compile with -DSQLITE_CONFIG_MEMSTATUS=1

**Expected behavior**
I would like to have a way to disable this parameter at runtime as the native code already support it by sqlite3_config(SQLITE_CONFIG_MEMSTATUS,0)

**Logs**
If applicable, provide logs.

**Environment (please complete the following information):**
 - OS: centos
 - CPU architecture: x86_64
 - sqlite-jdbc version 3.42

**Additional context**

**Comment by gotson** [comment]
> When enabling the parameter SQLITE_CONFIG_MEMSTATUS at compile time, the performance (read/write) is more than 2x slower

how does that have anything to do with the JDBC driver ? This is a SQLite option.

> I would like to have a way to disable this parameter at runtime as the native code already support it by sqlite3_config(SQLITE_CONFIG_MEMSTATUS,0)

open a feature request in that case, not a bug

**Comment by mhanna** [comment]
A feature request opened

However, I think something needs to be addressed here
I just got a reply from the sqlite support, i quote them

**Is your app calling sqlite3_soft_heap_limit64(), sqlite3_hard_heap_limit64(), or sqlite3_soft_heap_limit? Or is it compiled with the SQLITE_MAX_MEMORY option set to some value?

These interfaces are used to specify a global limit to the amount of memory used by the library, but they only work if memstats are enabled. If one of these limits was enabled by SQLITE_DEFAULT_MEMSTATUS=1 it might slow the application down to the extent you're seeing.**
