### ISSUE TITLE
Enabling SQLITE_CONFIG_MEMSTATUS is oveloading sqlite

### ISSUE THREAD

**Issue by mhanna** [xerial/sqlite-jdbc#955]
**Describe the bug**
When enabling the parameter SQLITE_CONFIG_MEMSTATUS at compile time, the performance (read/write) is more than 2x slower

**To Reproduce**
compile with -DSQLITE_CONFIG_MEMSTATUS=1

**Expected behavior**
A seamless way of using the sqlite memory status without hitting the performance at least 2x times.

**Logs**
If applicable, provide logs.

**Environment (please complete the following information):**
OS: centos
CPU architecture: x86_64
sqlite-jdbc version 3.42

**Additional context**
A reply from the sqlite support:

Is your app calling sqlite3_soft_heap_limit64(), sqlite3_hard_heap_limit64(), or sqlite3_soft_heap_limit? Or is it compiled with the SQLITE_MAX_MEMORY option set to some value?

These interfaces are used to specify a global limit to the amount of memory used by the library, but they only work if memstats are enabled. If one of these limits was enabled by SQLITE_DEFAULT_MEMSTATUS=1 it might slow the application down to the extent you're seeing.

**Comment by gotson** [comment]
I don't quite understand what you expect from this ticket tbh.

> Is your app calling sqlite3_soft_heap_limit64(), sqlite3_hard_heap_limit64(), or sqlite3_soft_heap_limit? Or is it compiled with the SQLITE_MAX_MEMORY option set to some value?

We don't use any of this.

**Comment by mhanna** [comment]
I expect to have the ability to get memory statistice from sqlite without more than 2x reduction in performance.
So i don't know where the issue is, sqlite or the jdbc, i will try to involve sqlite developers into this.

**Comment by gotson** [comment]
I will close this, there's nothing pointing to any fault of the driver itself.
