### ISSUE TITLE
Android binaries missing `SONAME`

### ISSUE THREAD

**Issue by 05nelsonm** [xerial/sqlite-jdbc#960]
**Describe the bug**
Android showing a linker warning in Logcat about `DT_SONAME` missing when running tests.

See: [https://android.googlesource.com/...](https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md#missing-soname-enforced-for-api-level-23)

**To Reproduce**
1. Run on Android (after moving binaries to appropriate `jniLibs` directory)
2. See Logcat

**Expected behavior**
`libsqlitejdbc.so` file should contain `SONAME`

**Logs**
```
W linker  : Warning: "/data/app/~~zcxv3TIBZ-Oa1_orVxLcwQ==/io.toxicity.core.data.cipher.driver.test.test-kS081-J0c1_WfBlGIntTzg==/lib/x86_64/libsqlitejdbc.so" has no DT_SONAME (will use libsqlitejdbc.so instead) and will not work when the app moves to API level 23 or later (https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md#missing-soname-enforced-for-api-level-23) (allowing for now because this app's target API level is still 21)
```

**Environment (please complete the following information):**
 - OS: `Android (Emulators API 24, 28, 33)`
 - CPU architecture: `x86`
 - sqlite-jdbc version: `3.41.2.1`

**Comment by gotson** [comment]
Hi, in the link you provided it mentions `SONAME` but you mention`DT_SONAME`. So which one should it be, and what should it contain for Android, would you know?

**Comment by 05nelsonm** [comment]
Unsure. Logcat error uses `DT_SONAME`

**Comment by gotson** [comment]
> Unsure. Logcat error uses `DT_SONAME`

Do you think you can find out? We would need more details to be able to fix it.

**Comment by 05nelsonm** [comment]
> Do you think you can find out? We would need more details to be able to fix it.

Think we have our answer >> https://stackoverflow.com/questions/41255199/warning-libcryptopp-so-is-missing-dt-soname-will-use-basename-as-a-replacement/41278924#41278924

**Comment by gotson** [comment]
I tried various linker options without success, the attribute is not added.

Here is what i tried:
```
-soname,libsqlitejdbc.so
-install_name,libsqlitejdbc.so
-Wl-soname,libsqlitejdbc.so
-Wl-install_name,libsqlitejdbc.so
-Wl-soname
```

**Comment by gotson** [comment]
I was using the arguments incorrectly, it seems the following works: `-Wl,-soname,libsqlitejdbc.so`

```
readelf --dynamic libsqlitejdbc.so | grep SONAME
 0x000000000000000e (SONAME)             Library soname: [libsqlitejdbc.so]
```

**Comment by gotson** [comment]
@05nelsonm you can try the latest snapshot which contains the SONAME

**Comment by 05nelsonm** [comment]
> @05nelsonm you can try the latest snapshot which contains the SONAME

Tried out `3.43.0.1-SNAPSHOT`; no more warnings in Logcat.

Tested on x86 emulator for Android API 23, 24, 27, 33.

Seems fixed to me, thanks @gotson !
