### ISSUE TITLE
How can I set Lookaside memory?

### ISSUE THREAD

**Issue by qiaoyuang** [xerial/sqlite-jdbc#964]
Hi, I want to set the [lookaside memory](https://www.sqlite.org/malloc.html) (see 3.3) in runtime. How can I do it? I didn't find the related API.

**Comment by gotson** [comment]
> To change the default size of the lookaside memory pool at compile-time, use the [-DSQLITE_DEFAULT_LOOKASIDE=SZ,N](https://www.sqlite.org/compile.html#default_lookaside) option. To change the default size of the lookaside memory pool at start-time, use the [sqlite3_config()](https://www.sqlite.org/c3ref/config.html) interface.

We don't support `sqlite3_config`, but you could recompile.

**Comment by qiaoyuang** [comment]
Thanks for your reply. Would you have any plan to support `sqlite3_config` in the future ?

**Comment by gotson** [comment]
https://github.com/xerial/sqlite-jdbc#project-status

> New features are driven by pull requests
