### ISSUE TITLE
Unsigned binaries (macOS)

### ISSUE THREAD

**Issue by 05nelsonm** [xerial/sqlite-jdbc#970]
**Describe the bug**
Binaries for macOS `aarch64` and `x86_64` are unsigned.

**To Reproduce**
- Extract Mac binaries from latest release
- Check code signatures (requires a mac)
  ```
  spctl --assess --type install --context context:primary-signature -v /path/to/libsqlitejdbc.dylib
  ```
- Witness rejection output from `spctl --assess`
  ```
  libsqlitejdbc.dylib: rejected
  ```

**Expected behavior**
native binaries should be signed and stapled
`spctl --assess` output should show the following:
```
libsqlitejdbc.dylib: accepted
source=Notarized Developer ID
```

**Environment (please complete the following information):**
 - OS: `macOS BigSur`
 - CPU architecture: `x86_64`
 - sqlite-jdbc version: `3.43.0.0`

**Additional context**
Using `rcodesign` one can sign and notarize the Mach-O binaries via bundle submission:

```sh
WORK_DIR="/path/to/work"
BUNDLE="$WORK_DIR/sqlite-jdbc.app"
BUNDLE_MACOS="$BUNDLE/Contents/MacOS/"
BUNDLE_LIB="$BUNDLE_MACOS/sqlite-jdbc/"
mkdir -p "$BUNDLE_LIB"

touch "$BUNDLE/Contents/Info.plist"
echo '<?xml version="1.0" encoding="UTF-8"?>
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key>
    <string>sqlitejdbc.program</string>
    <key>CFBundleIdentifier</key>
    <string>org.xerial</string>     <<<< or whatever your team id is for your developer cert
    <key>LSUIElement</key>
    <true/>
</dict>
</plist>' > "$BUNDLE/Contents/Info.plist"

# Copying the same binary into the bundle with .program suffix (as
# defined in the Info.plist) ensures no errors due to architecture mismatches
# when submitting for signing/notarization. There needs to be an executable
# there for the CFBundleExecutable definition, so can just use the same binaries
cp /path/to/unsigned/Mac/aarch64/libsqlitejdbc.dylib "$BUNDLE_MACOS/sqlitejdbc.program"

# Copy the .dylib we actually care about into separate dir within the bundle.
# Once bundle is signed and notarized, this is all that we care about and everything else
# can be dropped. The entire contents of the bundle will be recursively signed, so.
cp /path/to/unsigned/Mac/aarch64/libsqlitejdbc.dylib "$BUNDLE_LIB"

rcodesign sign --p12-file "/path/to/key.p12" --code-signature-flags runtime "$BUNDLE"
rcodesign notary-submit --api-key-path "/path/to/apikey.json" --staple "$BUNDLE"

mv "$BUNDLE_LIB/libsqlitejdbc.dylib" /path/to/signed/Mac/aarch64/

# repeat for x86_64
```

**Comment by 05nelsonm** [comment]
For windows binaries (which are also unsigned and can make problems for users of applications utilizing `sqlite-jdbc`), can use [osslsigncode](https://github.com/mtrojnar/osslsigncode).

Here's my signing scripts that I use for distributing tor binaries. https://github.com/05nelsonm/kmp-tor-binary/blob/master/library/binary-build/scripts/detached_sig_create.sh

It's a little more in-depth b/c I wanted to preserve the reproducible builds, so had to make a tool to create detached signatures (it just diffs the unsigned binary with the signed binary which can be applied later), but should get you 99% of the way.

**Comment by gotson** [comment]
We don't have certificates to sign binaries. The macos binaries are signed with an ad-hoc signature, else gatekeeper won't even run them.

Signing with your own certs is a packaging / distribution concern, and should not be managed here.

Certs are also expensive.

Some tools like Conveyor from Hydraulic can perform in-jar signing too.

**Comment by michael-o** [comment]
Signing for macOS requires a developer ID, right? Which requires a Mac and $$$, no?

**Comment by gotson** [comment]
> Signing for macOS requires a developer ID, right? Which requires a Mac and $$$, no?

Yes. Signing for windows also requires an authenticode certificate which is even more expensive.

**Comment by michael-o** [comment]
> > Signing for macOS requires a developer ID, right? Which requires a Mac and $$$, no?
> 
> Yes. Signing for windows also requires an authenticode certificate which is even more expensive.

So this is unreachable for an OSS dev then...

**Comment by 05nelsonm** [comment]
Yes, an apple developer account is $USD 99/yr. Windows cert varies, but I got mine from comodosslstore[dot]com for I believe $USD 179/yr.

I'm certain a sponsor can be found to cover the cost given the popularity of this library. If there is a will to add code signing for mac/windows binaries (it is some legwork), I can kick things off and reach out to some contacts of mine for sponsorship.

**Comment by gotson** [comment]
> Yes, an apple developer account is $USD 99/yr. Windows cert varies, but I got mine from comodosslstore[dot]com for I believe $USD 179/yr.
> 
> I'm certain a sponsor can be found to cover the cost given the popularity of this library. If there is a will to add code signing for mac/windows binaries (it is some legwork), I can kick things off and reach out to some contacts of mine for sponsorship.

Out of curiosity, why do you need signing of the lib itself?

I understand you already sign it for the app you're building, so what's the need? Simplicity?

As I mentioned some tools will do in jar signing without any problems too.

**Comment by 05nelsonm** [comment]
> I understand you already sign it for the app you're building, so what's the need? Simplicity?

Distributing of already signed binaries to library consumers is a big convenience. It's only needed for libs that have executable code (.dylib/.dll) as the OS flags them when the end consumer application runs (if it's an invalid signature).

Windows Defender can sometimes show popups for the application being installed, or inhibit it from running entirely w/o even notifying the user. Also depending on the user settings for Windows Defender, may result in an application being flagged as malware which is submitted to Microsoft and is bad news bears.

macOS just straight up does not allow it to run (even adhoc signatures). Also, when an application developer submits their app for signing/notarization, it will fail unless the `.dylib`s are signed.

Me personally, I have my code signing setup for `kmp-tor-binary` because I package all binaries gzipped to reduce the `.jar` size (resulting in a smaller app download size for consumers of `kmp-tor-binary` library). So, signing sort of needs to happen before gzip + release occurs.

**Comment by 05nelsonm** [comment]
> Signing for macOS requires a developer ID, right? Which requires a Mac and $$$, no?

I believe the only need for a mac is to generate the csr via keychain, and then to export the `.p12` key. After that, all signing can be done using `rcodesign`. Windows, everything can be done using `osslcodesign`. I do everything from linux, so.

**Comment by gotson** [comment]
> > Signing for macOS requires a developer ID, right? Which requires a Mac and $$$, no?
> 
> I believe the only need for a mac is to generate the csr via keychain, and then to export the `.p12` key. After that, all signing can be done using `rcodesign`. Windows, everything can be done using `osslcodesign`. I do everything from linux, so.
> 
> **EDIT:** This can be done on a VM if you don't have a mac available. See https://github.com/kholia/OSX-KVM

It's not much a tooling issue, but a money issue.

**Comment by michael-o** [comment]
> > > Signing for macOS requires a developer ID, right? Which requires a Mac and $$$, no?
> > 
> > 
> > I believe the only need for a mac is to generate the csr via keychain, and then to export the `.p12` key. After that, all signing can be done using `rcodesign`. Windows, everything can be done using `osslcodesign`. I do everything from linux, so.
> > **EDIT:** This can be done on a VM if you don't have a mac available. See https://github.com/kholia/OSX-KVM
> 
> It's not much a tooling issue, but a money issue.

I'd also say the overhead for it.

**Comment by 05nelsonm** [comment]
> It's not much a tooling issue, but a money issue.

If money was not an issue, would adding codesigning be something you'd be willing to do?

> I'd also say the overhead for it.

Yes it is a lift, initially. Once it is done though, that's it.

**Comment by gotson** [comment]
It's not my project, it would be upon xerial to setup the necessary things to receive funding, and disburse it. Given he hasn't been looking much at this for the past few years, I would say the chances are extremely slim.

**Comment by 05nelsonm** [comment]
> It's not my project, it would be upon xerial to setup the necessary things to receive funding, and disburse it. Given he hasn't been looking much at this for the past few years, I would say the chances are extremely slim.

Completely understandable. Will close the issue then.

If you ever reconsider, I am 100% certain I would be able to find you (as the current maintainer) funding for this endeavor. Just hit me up.

:clinking_glasses:
