### ISSUE TITLE
ROUND function not working as expected

### ISSUE THREAD

**Issue by joc-a** [xerial/sqlite-jdbc#974]
**Describe the bug**
ROUND function is not working as expected. More details below.

**To Reproduce**
Run this in DataGrip with driver Xerial SQLiteJDBC v0.43.0.0
```
DROP TABLE IF EXISTS fakeTable;
CREATE TABLE IF NOT EXISTS fakeTable (id INTEGER PRIMARY KEY AUTOINCREMENT);
INSERT INTO fakeTable  DEFAULT VALUES;
SELECT ROUND(10.555, 2) FROM fakeTable;
```

**Expected behaviour**
Expected result: 10.56.
Actual result: 10.55

**Logs**
If applicable, provide logs.

**Environment (please complete the following information):**
 - OS: macOS
 - CPU architecture: ARM64
 - sqlite-jdbc version: 3.43.0.0

**Additional context**
Tested using DataGrip with driver Xerial SQLiteJDBC v0.43.0.0
<img width="548" alt="Screenshot 2023-09-12 at 3 37 28 PM" src="https://github.com/xerial/sqlite-jdbc/assets/38375996/24a2c108-78a4-453a-b523-5275f0256fca">

**Comment by gotson** [comment]
Not sure to understand, your issue doesn't mention or show any sqlite-jdbc code, only sqlite sql.

**Comment by joc-a** [comment]
> Not sure to understand, your issue doesn't mention or show any sqlite-jdbc code, only sqlite sql.

@gotson Sorry, I added more info under **Additional context**.

**Comment by gotson** [comment]
Still doesn't explain what it has to do with the driver itself. 

Do you get same results in sqlite cli?

**Comment by joc-a** [comment]
Apologies for jumping to the conclusion that there is a problem with the driver. It appears to be a problem with SQLite and [someone has already reported it](https://www.sqlite.org/forum/forumpost/2801f84063). Here is the comparison between the CLI results for v3.39.5 and v3.43.1.
<img width="591" alt="Screenshot 2023-09-12 at 4 30 25 PM" src="https://github.com/xerial/sqlite-jdbc/assets/38375996/76e353e0-a65f-40ce-b55b-4c6a96877647">
vs
<img width="537" alt="Screenshot 2023-09-12 at 4 37 08 PM" src="https://github.com/xerial/sqlite-jdbc/assets/38375996/b0aac143-052e-4537-ac25-1f52fd771374">
