### ISSUE TITLE
Add support for data change notification callbacks

### ISSUE THREAD

**Issue by archiecobbs** [xerial/sqlite-jdbc#98]
SQLite data change notification callbacks are functions registered on a connection that are invoked whenever a specific table row is modified.

See feature description here: http://www.sqlite.org/c3ref/update_hook.html

This is a valuable feature that should be fairly straightforward to expose at the Java layer.

Sketch of how this could be done:
- Define callback interface, with method that takes the rowid and mutation type (insert, delete, update)
- Add methods to `SQLiteConnection` to add/remove callback registrations on that connection
- Each `SQLiteConnection` maintains an internal bi-directional mapping from the `void *` handles passed to `update_hook.html()`, which could just be an incrementing counter value cast to `void *`, and the callback instance(s) registered on the corresponding rowid.

**Comment by Rodrigo-Sodre** [comment]
Would use it right now if it existed.

**Comment by gitblit** [comment]
I agree, that would be a nice addition.  We're looking for someone to open a PR.
