### ISSUE TITLE
Support for sqlite3_serialize/deserializae

### ISSUE THREAD

**Issue by yuvalp-k2view** [xerial/sqlite-jdbc#988]
Our use cases require us to quickly load/save database schemas and store/restore them.
Today, if we want this to work fast, we create the files on memory mapped disks and use ATTACH/DETACH.

We benchmarked using C and found out that sqlite3_serialize/deserialize are faster than attach/detach, offer better scalability (no global mutex) and the resulting in-memory database is significantly faster than the memory mapped file system.

We would like to add this as a xerial api. I believe the best way would be using InputStream/OutputStream based API.

If this makes sense, we would gladly contribute the code under some guidance and agreement of where it should go as well as the correct place for the unit tests.

**Comment by yuvalp-k2view** [comment]
@gotson 

I have the code ready along with unit tests. Turned our very nice and fast.
Do I need a permission to create a branch and pull request?

**Comment by yuvalp-k2view** [comment]
Just wanted to add that Working with the team of maintainers @gotson, @kkriske has been a real pleasure. Reviews and discussion were very good. Thank you!

**Comment by gotson** [comment]
Thanks for a quality PR!
