### ISSUE TITLE
Since 3.43.2.0 No suitable driver found for jdbc:sqlite::memory:

### ISSUE THREAD

**Issue by NSP-0123456** [xerial/sqlite-jdbc#997]
**Describe the bug**
Since VERSION 3.43.2.0
I cannot create anymore in memory database.
java.sql.SQLException: No suitable driver found for jdbc:sqlite::memory:

**To Reproduce** 
_(import java.sql.*)_
          Connection  conn = DriverManager.getConnection("jdbc:sqlite::memory:");
          Statement stmt = conn.createStatement();
            

**Expected behavior**
No exception...

**Logs**
If applicable, provide logs.

**Environment (please complete the following information):**
 - OS: Windows 10
 - CPU architecture:  x86_64
 - sqlite-jdbc version 3.43.2.1

**Additional context**

**Comment by gotson** [comment]
Can you provide a repro?

**Comment by NSP-0123456** [comment]
I'm using java 11 on windows 64bit. 
To reproduce just use this simple test class.
`import java.sql.*;

public class test {

public static void main(String args[]){
  try{
  Connection conn = DriverManager.getConnection("jdbc:
  } catch (Throwable t){
    t.printStackTrace();
  }
  }
}
`
i run with`java -cp .;sqlite-jdbc-3.43.2.1.jar testjava -cp .;sqlite-jdbc-3.43.2.1.jar test`

result is:
`java.sql.SQLException: No suitable driver found for jdbc:sqlite::memory:
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:702)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
        at test.main(test.java:7)

`

**Comment by gotson** [comment]
You are probably missing slf4j-api on the classpath, which prevents the driver from loading?

**Comment by NSP-0123456** [comment]
I do not use slf4j and it was not needed in previous releases at least until 3.43.0.0. Why do you add such dependency as all was working fine before !

**Comment by gotson** [comment]
> I do not use slf4j and it was not needed in previous releases at least until 3.43.0.0. Why do you add such dependency as all was working fine before !

Read the Changelog, and check the sample in the Readme.
